enum 77 "Report Selection Usage"
{
    Extensible = true;
    AssignmentCompatibility = true;

    value(0; "S.Quote") { Caption = 'S.Quote'; }
    value(1; "S.Order") { Caption = 'S.Order'; }
    value(2; "S.Invoice") { Caption = 'S.Invoice'; }
    value(3; "S.Cr.Memo") { Caption = 'S.Cr.Memo'; }
    value(4; "S.Test") { Caption = 'S.Test'; }
    value(5; "P.Quote") { Caption = 'P.Quote'; }
    value(6; "P.Order") { Caption = 'P.Order'; }
    value(7; "P.Invoice") { Caption = 'P.Invoice'; }
    value(8; "P.Cr.Memo") { Caption = 'P.Cr.Memo'; }
    value(9; "P.Receipt") { Caption = 'P.Receipt'; }
    value(10; "P.Ret.Shpt.") { Caption = 'P.Ret.Shpt.'; }
    value(11; "P.Test") { Caption = 'P.Test'; }
    value(12; "B.Stmt") { Caption = 'B.Stmt'; }
    value(13; "B.Recon.Test") { Caption = 'B.Recon.Test'; }
    value(14; "B.Check") { Caption = 'B.Check'; }
    value(15; "Reminder") { Caption = 'Reminder'; }
    value(16; "Fin.Charge") { Caption = 'Fin.Charge'; }
    value(17; "Rem.Test") { Caption = 'Rem.Test'; }
    value(18; "F.C.Test") { Caption = 'F.C.Test'; }
    value(19; "Prod.Order") { Caption = 'Prod.Order'; }
    value(20; "S.Blanket") { Caption = 'S.Blanket'; }
    value(21; "P.Blanket") { Caption = 'P.Blanket'; }
    value(22; "M1") { Caption = 'M1'; }
    value(23; "M2") { Caption = 'M2'; }
    value(24; "M3") { Caption = 'M3'; }
    value(25; "M4") { Caption = 'M4'; }
    value(26; "Inv1") { Caption = 'Inv1'; }
    value(27; "Inv2") { Caption = 'Inv2'; }
    value(28; "Inv3") { Caption = 'Inv3'; }
    value(29; "SM.Quote") { Caption = 'SM.Quote'; }
    value(30; "SM.Order") { Caption = 'SM.Order'; }
    value(31; "SM.Invoice") { Caption = 'SM.Invoice'; }
    value(32; "SM.Credit Memo") { Caption = 'SM.Credit Memo'; }
    value(33; "SM.Contract Quote") { Caption = 'SM.Contract Quote'; }
    value(34; "SM.Contract") { Caption = 'SM.Contract'; }
    value(35; "SM.Test") { Caption = 'SM.Test'; }
    value(36; "S.Return") { Caption = 'S.Return'; }
    value(37; "P.Return") { Caption = 'P.Return'; }
    value(38; "S.Shipment") { Caption = 'S.Shipment'; }
    value(39; "S.Ret.Rcpt.") { Caption = 'S.Ret.Rcpt.'; }
    value(40; "S.Work Order") { Caption = 'S.Work Order'; }
    value(41; "Invt.Period Test") { Caption = 'Invt.Period Test'; }
    value(42; "SM.Shipment") { Caption = 'SM.Shipment'; }
    value(43; "S.Test Prepmt.") { Caption = 'S.Test Prepmt.'; }
    value(44; "P.Test Prepmt.") { Caption = 'P.Test Prepmt.'; }
    value(45; "S.Arch.Quote") { Caption = 'S.Arch.Quote'; }
    value(46; "S.Arch.Order") { Caption = 'S.Arch.Order'; }
    value(47; "P.Arch.Quote") { Caption = 'P.Arch.Quote'; }
    value(48; "P.Arch.Order") { Caption = 'P.Arch.Order'; }
    value(49; "S.Arch.Return") { Caption = 'S.Arch.Return'; }
    value(50; "P.Arch.Return") { Caption = 'P.Arch.Return'; }
    value(51; "Asm.Order") { Caption = 'Asm.Order'; }
    value(52; "P.Asm.Order") { Caption = 'P.Asm.Order'; }
    value(53; "S.Order Pick Instruction") { Caption = 'S.Order Pick Instruction'; }
    value(84; "P.V.Remit.") { Caption = 'P.V.Remit.'; }
    value(85; "C.Statement") { Caption = 'C.Statement'; }
    value(86; "V.Remittance") { Caption = 'V.Remittance'; }
    value(87; "JQ") { Caption = 'Job Queue'; }
    value(88; "S.Invoice Draft") { Caption = 'S.Invoice Draft'; }
    value(89; "Pro Forma S. Invoice") { Caption = 'Pro Forma S. Invoice'; }
    value(90; "S.Arch.Blanket") { Caption = 'S.Arch.Blanket'; }
    value(91; "P.Arch.Blanket") { Caption = 'P.Arch.Blanket'; }
    value(92; "Phys.Invt.Order Test") { Caption = 'Phys.Invt.Order Test'; }
    value(93; "Phys.Invt.Order") { Caption = 'Phys.Invt.Order'; }
    value(94; "P.Phys.Invt.Order") { Caption = 'P.Phys.Invt.Order'; }
    value(95; "Phys.Invt.Rec.") { Caption = 'Phys.Invt.Rec.'; }
    value(96; "P.Phys.Invt.Rec.") { Caption = 'P.Phys.Invt.Rec.'; }
}