// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Finance.Analysis;

using Microsoft.Foundation.NoSeries;
using System.Utilities;

table 687 "Payment Practice Header"
{
    DataClassification = CustomerContent;

    fields
    {
        field(1; "No."; Integer)
        {
            AutoIncrement = true;
        }
        field(2; "Starting Date"; Date)
        {
            trigger OnValidate()
            begin
                ValidateDates();
            end;
        }
        field(3; "Ending Date"; Date)
        {
            trigger OnValidate()
            begin
                ValidateDates();
            end;
        }
        field(4; "Aggregation Type"; Enum "Paym. Prac. Aggregation Type")
        {
            InitValue = 1;

            trigger OnValidate()
            begin
                ValidateFieldChange(Rec."Aggregation Type");
                Rec.CalcFields("Lines Exist");
                if not Rec."Lines Exist" then
                    exit;

                if ConfirmManagement.GetResponseOrDefault(StrSubstNo(ClearHeaderQst, FieldCaption("Aggregation Type")), true) then
                    ClearHeader()
                else
                    "Aggregation Type" := xRec."Aggregation Type";
            end;
        }
        field(5; "Header Type"; Enum "Paym. Prac. Header Type")
        {
            InitValue = 1;

            trigger OnValidate()
            begin
                ValidateFieldChange(Rec."Aggregation Type");
                Rec.CalcFields("Lines Exist");
                if not Rec."Lines Exist" then
                    exit;

                if ConfirmManagement.GetResponseOrDefault(StrSubstNo(ClearHeaderQst, FieldCaption("Header Type")), true) then
                    ClearHeader()
                else
                    "Header Type" := xRec."Header Type";
            end;
        }
        field(6; "Average Agreed Payment Period"; Integer)
        {
            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(7; "Average Actual Payment Period"; Integer)
        {
            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(8; "Pct Paid on Time"; Decimal)
        {
            AutoFormatType = 0;

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(9; "Generated On"; DateTime)
        {

        }
        field(10; "Generated By"; Code[20])
        {

        }
        field(11; "Lines Exist"; Boolean)
        {
            CalcFormula = exist("Payment Practice Line" where("Header No." = field("No.")));
            FieldClass = FlowField;
        }
        field(12; "Modified Manually"; Boolean)
        {

        }
        field(15; "Reporting Scheme"; Enum "Paym. Prac. Reporting Scheme")
        {
            Editable = false;
            ToolTip = 'Specifies which reporting scheme is used, such as Standard, Dispute & Retention, or Small Business. Controls which fields and calculations apply.';
        }
        field(20; "Total Number of Payments"; Integer)
        {
            Editable = false;
            ToolTip = 'Specifies the total number of payments made during the reporting period.';
        }
        field(21; "Total Amount of Payments"; Decimal)
        {
            Editable = false;
            AutoFormatType = 1;
            AutoFormatExpression = '';
            ToolTip = 'Specifies the total value of payments made during the reporting period.';
        }
        field(22; "Total Amt. of Overdue Payments"; Decimal)
        {
            Editable = false;
            AutoFormatType = 1;
            AutoFormatExpression = '';
            ToolTip = 'Specifies the total value of payments not made within the agreed payment terms.';
        }
        field(23; "Pct Overdue Due to Dispute"; Decimal)
        {
            Editable = false;
            AutoFormatType = 0;
            ToolTip = 'Specifies the percentage of payments not made within agreed terms that are due to disputes.';
        }
        field(24; "Mode Payment Time"; Integer)
        {
            ToolTip = 'Specifies the most frequently occurring number of days taken to pay invoices during the reporting period.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(25; "Mode Payment Time Min."; Integer)
        {
            ToolTip = 'Specifies the lowest mode payment time, in days, found across all vendors in the reporting period. The value is calculated by determining the mode payment time for each vendor, which is the most frequently occurring number of days taken to pay invoices for that vendor during the reporting period, and then finding the lowest value among those.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(26; "Mode Payment Time Max."; Integer)
        {
            ToolTip = 'Specifies the highest mode payment time, in days, found across all vendors in the reporting period. The value is calculated by determining the mode payment time for each vendor, which is the most frequently occurring number of days taken to pay invoices for that vendor during the reporting period, and then finding the highest value among those.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(27; "Median Payment Time"; Decimal)
        {
            AutoFormatType = 0;
            DecimalPlaces = 2;
            ToolTip = 'Specifies the median number of days taken to pay invoices during the reporting period.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(28; "80th Percentile Payment Time"; Integer)
        {
            ToolTip = 'Specifies the number of days within which 80 percent of invoices were paid during the reporting period.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(29; "95th Percentile Payment Time"; Integer)
        {
            ToolTip = 'Specifies the number of days within which 95 percent of invoices were paid during the reporting period.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(30; "Pct Peppol Enabled"; Decimal)
        {
            AutoFormatType = 0;
            DecimalPlaces = 2;
            ToolTip = 'Specifies the percentage of invoices that were PEPPOL enabled. An invoice is considered PEPPOL enabled if the vendor has a GLN.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
        field(31; "Pct Small Business Payments"; Decimal)
        {
            AutoFormatType = 0;
            DecimalPlaces = 2;
            ToolTip = 'Specifies the value of payments made to small business vendors as a percentage of total payments in the reporting period, including partial payments. A vendor is classified as a small business based on the company size code on the vendor record.';

            trigger OnValidate()
            begin
                Rec."Modified Manually" := true;
            end;
        }
    }

    keys
    {
        key(Key1; "No.")
        {
            Clustered = true;
        }
    }

    trigger OnInsert()
    begin
        UpdateNo();
        DetectReportingScheme();
    end;

    trigger OnDelete()
    begin
        DeleteLinkedRecords();
    end;

    var
        ConfirmManagement: Codeunit "Confirm Management";
        ClearHeaderQst: Label 'Changing %1 will delete existing lines. Do you want to continue?', Comment = '%1 = Field name';
        DateValidationErr: Label 'Starting Date must be less than or equal to Ending Date.';

    procedure UpdateNo(): Integer
    var
        SequenceNoMgt: Codeunit "Sequence No. Mgt.";
    begin
        if Rec."No." = 0 then
            Rec.Validate("No.", SequenceNoMgt.GetNextSeqNo(Database::"Payment Practice Header"));
    end;

    local procedure DeleteLinkedRecords()
    var
        PaymentPracticeLine: Record "Payment Practice Line";
        PaymentPracticeData: Record "Payment Practice Data";
    begin
        PaymentPracticeLine.SetRange("Header No.", "No.");
        PaymentPracticeLine.DeleteAll();
        PaymentPracticeData.SetRange("Header No.", "No.");
        PaymentPracticeData.DeleteAll();
        Rec.CalcFields("Lines Exist");
    end;

    procedure ClearHeader()
    begin
        "Generated On" := 0DT;
        "Generated By" := '';
        DeleteLinkedRecords();
    end;

    local procedure ValidateFieldChange(PaymentPracticeLinesAggregator: Interface PaymentPracticeLinesAggregator)
    begin
        PaymentPracticeLinesAggregator.ValidateHeader(Rec);
    end;

    local procedure ValidateDates()
    begin
        if (Rec."Starting Date" <> 0D) and (Rec."Ending Date" <> 0D) then
            if Rec."Starting Date" > Rec."Ending Date" then
                Error(DateValidationErr);
    end;

    local procedure DetectReportingScheme()
    var
        PaymentPractices: Codeunit "Payment Practices";
    begin
        "Reporting Scheme" := PaymentPractices.DetectReportingScheme();
    end;

}