permissionset 617 "D365 DYN CRM MGT"
{
    Assignable = true;

    Caption = 'Dynamics 365 Dynamics CRM Mgt.';
    Permissions = tabledata "CDS Company" = RIMD,
                  tabledata "CDS Connection Setup" = RIMD,
                  tabledata "CDS Coupled Business Unit" = RIMD,
                  tabledata "CDS Environment" = RIMD,
                  tabledata "CDS Failed Option Mapping" = RIMD,
                  tabledata "CDS Solution" = RIMD,
                  tabledata "CDS Teammembership" = RIMD,
                  tabledata "CDS Teamroles" = RIMD,
                  tabledata "Coupling Field Buffer" = RIMD,
                  tabledata "Coupling Record Buffer" = RIMD,
                  tabledata "CRM Account" = RIMD,
                  tabledata "CRM Account Statistics" = RIMD,
                  tabledata "CRM Annotation" = RIMD,
                  tabledata "CRM Annotation Buffer" = RIMD,
                  tabledata "CRM Annotation Coupling" = RIMD,
                  tabledata "CRM Appmodule" = RIMD,
                  tabledata "CRM Businessunit" = RIMD,
                  tabledata "CRM Contact" = RIMD,
                  tabledata "CRM Contract" = RIMD,
                  tabledata "CRM Customeraddress" = RIMD,
                  tabledata "CRM Discount" = RIMD,
                  tabledata "CRM Discounttype" = RIMD,
                  tabledata "CRM Full Synch. Review Line" = RIMD,
                  tabledata "CRM Incident" = RIMD,
                  tabledata "CRM Incidentresolution" = RIMD,
                  tabledata "CRM Integration Record" = RIMD,
                  tabledata "CRM Invoice" = RIMD,
                  tabledata "CRM Invoicedetail" = RIMD,
                  tabledata "CRM NAV Connection" = RIMD,
                  tabledata "CRM Opportunity" = RIMD,
                  tabledata "CRM Option Mapping" = RIMD,
                  tabledata "CRM Organization" = RIMD,
                  tabledata "CRM Post" = RIMD,
                  tabledata "CRM Post Buffer" = RIMD,
                  tabledata "CRM Pricelevel" = RIMD,
                  tabledata "CRM Product" = RIMD,
                  tabledata "CRM Productpricelevel" = RIMD,
                  tabledata "CRM Quote" = RIMD,
                  tabledata "CRM Quotedetail" = RIMD,
                  tabledata "CRM Redirect" = R,
                  tabledata "CRM Role" = RIMD,
                  tabledata "CRM Salesorder" = RIMD,
                  tabledata "CRM Salesorderdetail" = RIMD,
                  tabledata "CRM Synch Status" = RIMD,
                  tabledata "CRM Synch. Conflict Buffer" = RIMD,
                  tabledata "CRM Synch. Job Status Cue" = RIMD,
                  tabledata "CRM Systemuser" = RIMD,
                  tabledata "CRM Systemuserroles" = RIMD,
                  tabledata "CRM Team" = RIMD,
                  tabledata "CRM Transactioncurrency" = RIMD,
                  tabledata "CRM Uom" = RIMD,
                  tabledata "CRM Uomschedule" = RIMD,
                  tabledata "Customer Templ." = Rimd,
#if not CLEAN18
                  tabledata "Customer Template" = Rimd,
#endif
                  tabledata "Integration Field Mapping" = RIMD,
                  tabledata "Integration Synch. Job" = RIMD,
                  tabledata "Integration Synch. Job Errors" = RIMD,
                  tabledata "Integration Table Mapping" = RIMD,
                  tabledata "Interaction Template" = Rimd,
                  tabledata "Temp Integration Field Mapping" = RIMD;
}
