permissionset 8787 "D365 FA, EDIT"
{
    Assignable = true;

    Caption = 'Dyn. 365 Create Fixed Assets';
    Permissions = tabledata "Depreciation Book" = Rm,
                  tabledata "Depreciation Table Buffer" = RIMD,
                  tabledata "Depreciation Table Header" = R,
                  tabledata "Depreciation Table Line" = R,
                  tabledata "FA Allocation" = R,
                  tabledata "FA Buffer Projection" = RIMD,
                  tabledata "FA Class" = R,
                  tabledata "FA Date Type" = R,
                  tabledata "FA Depreciation Book" = Rim,
                  tabledata "FA G/L Posting Buffer" = RIMD,
                  tabledata "FA Journal Batch" = RIMD,
                  tabledata "FA Journal Line" = RIMD,
                  tabledata "FA Journal Setup" = R,
                  tabledata "FA Journal Template" = R,
                  tabledata "FA Ledger Entry" = Rimd,
                  tabledata "FA Location" = R,
                  tabledata "FA Matrix Posting Type" = R,
                  tabledata "FA Posting Group" = R,
                  tabledata "FA Posting Group Buffer" = RIMD,
                  tabledata "FA Posting Type" = R,
                  tabledata "FA Posting Type Setup" = R,
                  tabledata "FA Reclass. Journal Batch" = RIMD,
                  tabledata "FA Reclass. Journal Line" = RIMD,
                  tabledata "FA Reclass. Journal Template" = R,
                  tabledata "FA Register" = Rimd,
                  tabledata "FA Setup" = R,
                  tabledata "FA Subclass" = R,
                  tabledata "Fixed Asset" = RIMD,
                  tabledata "Ins. Coverage Ledger Entry" = Rimd,
                  tabledata Insurance = RIMD,
                  tabledata "Insurance Journal Batch" = RIMD,
                  tabledata "Insurance Journal Line" = RIMD,
                  tabledata "Insurance Journal Template" = R,
                  tabledata "Insurance Register" = Rimd,
                  tabledata "Insurance Type" = R,
                  tabledata "Main Asset Component" = RIMD,
                  tabledata Maintenance = R,
                  tabledata "Maintenance Ledger Entry" = Rimd,
                  tabledata "Maintenance Registration" = RIMD,
                  tabledata "Total Value Insured" = RIMD;
}
