permissionset 5729 "D365 CUSTOMER, EDIT"
{
    Assignable = true;
    Caption = 'Dynamics 365 Create customers';

    IncludedPermissionSets = "D365 CUSTOMER, VIEW";

    Permissions = tabledata "Bank Account Ledger Entry" = rm,
                  tabledata Bin = R,
                  tabledata "Check Ledger Entry" = r,
                  tabledata "Cont. Duplicate Search String" = RIMD,
                  tabledata Contact = RIMD,
                  tabledata "Contact Business Relation" = RImD,
                  tabledata "Contact Duplicate" = R,
                  tabledata "Contact Industry Group" = Rd,
                  tabledata "Contact Job Responsibility" = Rd,
                  tabledata "Contact Mailing Group" = Rd,
                  tabledata "Contact Profile Answer" = d,
                  tabledata "Contact Web Source" = Rd,
                  tabledata "Contract Gain/Loss Entry" = rm,
                  tabledata Currency = RM,
                  tabledata "Cust. Invoice Disc." = IMD,
                  tabledata "Cust. Ledger Entry" = M,
                  tabledata Customer = RIMD,
                  tabledata "Customer Bank Account" = IMD,
                  tabledata "Customer Discount Group" = RIMD,
                  tabledata "Customer Templ." = rm,
#if not CLEAN20
                  tabledata "Customer Template" = r,
#endif
                  tabledata "Detailed Cust. Ledg. Entry" = Rimd,
                  tabledata "Dtld. Price Calculation Setup" = Rid,
                  tabledata "Duplicate Price Line" = Rid,
                  tabledata "Duplicate Search String Setup" = R,
                  tabledata "Employee Ledger Entry" = rm,
                  tabledata "Filed Contract Line" = rm,
                  tabledata "Finance Charge Text" = R,
                  tabledata "G/L Entry - VAT Entry Link" = rm,
                  tabledata "G/L Entry" = rm,
                  tabledata "Interaction Log Entry" = Rm,
                  tabledata "Item Analysis View Budg. Entry" = r,
                  tabledata "Item Analysis View Entry" = rid,
                  tabledata "Item Budget Entry" = r,
                  tabledata "Item Reference" = IMD,
                  tabledata "Line Fee Note on Report Hist." = R,
                  tabledata Opportunity = Rm,
                  tabledata "Opportunity Entry" = Rm,
                  tabledata "Price Asset" = Rid,
                  tabledata "Price Calculation Buffer" = Rid,
                  tabledata "Price Calculation Setup" = Rid,
                  tabledata "Price Line Filters" = Rid,
                  tabledata "Price List Header" = Rid,
                  tabledata "Price List Line" = Rid,
                  tabledata "Price Source" = Rid,
                  tabledata "Price Worksheet Line" = Rid,
                  tabledata "Profile Questionnaire Line" = R,
                  tabledata "Purch. Cr. Memo Hdr." = rm,
                  tabledata "Purch. Cr. Memo Line" = rm,
                  tabledata "Purch. Inv. Header" = rm,
                  tabledata "Purch. Rcpt. Header" = rm,
                  tabledata "Purchase Header Archive" = r,
                  tabledata "Registered Whse. Activity Line" = rm,
                  tabledata "Reminder Level" = R,
                  tabledata "Reminder Text" = R,
                  tabledata "Res. Journal Line" = r,
                  tabledata "Return Receipt Header" = rm,
                  tabledata "Return Receipt Line" = rm,
                  tabledata "Return Shipment Header" = rm,
                  tabledata "Return Shipment Line" = rm,
                  tabledata "Rlshp. Mgt. Comment Line" = rD,
                  tabledata "Sales Cr.Memo Header" = rm,
                  tabledata "Sales Cr.Memo Line" = rm,
                  tabledata "Sales Discount Access" = Rd,
                  tabledata "Sales Header Archive" = rm,
                  tabledata "Sales Invoice Line" = rm,
#if not CLEAN21
                  tabledata "Sales Line Discount" = Rd,
                  tabledata "Sales Price" = Rid,
#endif
                  tabledata "Sales Price Access" = Rid,
                  tabledata "Sales Shipment Header" = rm,
                  tabledata "Sales Shipment Line" = Rm,
                  tabledata "Service Contract Header" = Rm,
                  tabledata "Service Contract Line" = Rm,
                  tabledata "Service Header" = Rm,
                  tabledata "Service Invoice Line" = Rm,
                  tabledata "Service Item" = Rm,
                  tabledata "Service Item Line" = Rm,
                  tabledata "Service Ledger Entry" = rm,
                  tabledata "Service Line" = r,
                  tabledata "Ship-to Address" = RIMD,
                  tabledata "Standard Customer Sales Code" = RIMD,
                  tabledata "Standard Sales Code" = RIMD,
                  tabledata "Standard Sales Line" = RIMD,
                  tabledata "To-do" = Rm,
                  tabledata "VAT Entry" = Rm,
                  tabledata "VAT Reg. No. Srv Config" = RIMD,
                  tabledata "VAT Reg. No. Srv. Template" = RIMD,
                  tabledata "VAT Registration Log Details" = RIMD,
                  tabledata "VAT Registration No. Format" = IMD,
                  tabledata "Vendor Ledger Entry" = rm,
                  tabledata "Warehouse Activity Header" = rm,
                  tabledata "Warehouse Activity Line" = rm,
                  tabledata "Warehouse Request" = rm,
                  tabledata "Warehouse Shipment Line" = rm,
                  tabledata "Warranty Ledger Entry" = rm,
                  tabledata "Whse. Worksheet Line" = r;
}
