namespace System.Security.AccessControl;

using Microsoft;
using Microsoft.AccountantPortal;
using Microsoft.API;
using Microsoft.API.Upgrade;
using Microsoft.Assembly.Comment;
using Microsoft.Assembly.Document;
using Microsoft.Assembly.History;
using Microsoft.Assembly.Reports;
using Microsoft.Assembly.Setup;
using Microsoft.Bank.BankAccount;
using Microsoft.Bank.Check;
#if not CLEAN24
using Microsoft.Bank.Deposit;
#endif
using Microsoft.Bank.DirectDebit;
using Microsoft.Bank.Ledger;
using Microsoft.Bank.Payment;
using Microsoft.Bank.PositivePay;
using Microsoft.Bank.Reconciliation;
using Microsoft.Bank.Setup;
using Microsoft.Bank.Statement;
using Microsoft.Booking;
using Microsoft.CashFlow.Account;
using Microsoft.CashFlow.Comment;
using Microsoft.CashFlow.Forecast;
using Microsoft.CashFlow.Setup;
using Microsoft.CashFlow.Worksheet;
using Microsoft.CostAccounting.Account;
using Microsoft.CostAccounting.Allocation;
using Microsoft.CostAccounting.Budget;
using Microsoft.CostAccounting.Journal;
using Microsoft.CostAccounting.Ledger;
using Microsoft.CostAccounting.Setup;
using Microsoft.CRM.Analysis;
using Microsoft.CRM.BusinessRelation;
using Microsoft.CRM.Campaign;
using Microsoft.CRM.Comment;
using Microsoft.CRM.Contact;
using Microsoft.CRM.Duplicates;
using Microsoft.CRM.Interaction;
using Microsoft.CRM.Opportunity;
using Microsoft.CRM.Outlook;
using Microsoft.CRM.Profiling;
using Microsoft.CRM.RoleCenters;
using Microsoft.CRM.Segment;
using Microsoft.CRM.Setup;
using Microsoft.CRM.Task;
using Microsoft.CRM.Team;
using Microsoft.EServices.EDocument;
using Microsoft.eServices.OnlineMap;
using Microsoft.Finance.AllocationAccount;
using Microsoft.Finance.Analysis;
using Microsoft.Finance.Consolidation;
using Microsoft.Finance.Currency;
using Microsoft.Finance.Deferral;
using Microsoft.Finance.Dimension.Correction;
using Microsoft.Finance.Dimension;
using Microsoft.Finance.FinancialReports;
using Microsoft.Finance.GeneralLedger.Account;
using Microsoft.Finance.GeneralLedger.Budget;
using Microsoft.Finance.GeneralLedger.Journal;
using Microsoft.Finance.GeneralLedger.Ledger;
using Microsoft.Finance.GeneralLedger.Reports;
using Microsoft.Finance.GeneralLedger.Reversal;
using Microsoft.Finance.GeneralLedger.Setup;
using Microsoft.Finance.Payroll;
using Microsoft.Finance.ReceivablesPayables;
using Microsoft.Finance.RoleCenters;
using Microsoft.Finance.SalesTax;
using Microsoft.Finance.VAT.Calculation;
using Microsoft.Finance.VAT.Setup;
using Microsoft.Finance.VAT.Clause;
using Microsoft.Finance.VAT.Ledger;
using Microsoft.Finance.VAT.RateChange;
using Microsoft.Finance.VAT.Registration;
using Microsoft.Finance.VAT.Reporting;
using Microsoft.FixedAssets.Depreciation;
using Microsoft.FixedAssets.FixedAsset;
using Microsoft.FixedAssets.Insurance;
using Microsoft.FixedAssets.Journal;
using Microsoft.FixedAssets.Ledger;
using Microsoft.FixedAssets.Maintenance;
using Microsoft.FixedAssets.Posting;
using Microsoft.FixedAssets.Setup;
using Microsoft.Foundation.Address;
using Microsoft.Foundation.Attachment;
using Microsoft.Foundation.AuditCodes;
using Microsoft.Foundation.BatchProcessing;
using Microsoft.Foundation.Calendar;
using Microsoft.Foundation.Comment;
using Microsoft.Foundation.Company;
using Microsoft.Foundation.ExtendedText;
using Microsoft.Foundation.Navigate;
using Microsoft.Foundation.NoSeries;
using Microsoft.Foundation.PaymentTerms;
using Microsoft.Foundation.Period;
using Microsoft.Foundation.Reporting;
using Microsoft.Foundation.Shipping;
using Microsoft.Foundation.Task;
using Microsoft.Foundation.UOM;
using Microsoft.HumanResources.Absence;
using Microsoft.HumanResources.Comment;
using Microsoft.HumanResources.Employee;
using Microsoft.HumanResources.Payables;
using Microsoft.HumanResources.Setup;
using Microsoft.Integration.D365Sales;
using Microsoft.Integration.Dataverse;
#if not CLEAN25
using Microsoft.Integration.FieldService;
#endif
using Microsoft.Integration.Entity;
using Microsoft.Integration.Graph;
using Microsoft.Integration.SyncEngine;
using Microsoft.Integration.PowerBI;
using Microsoft.Intercompany.Comment;
using Microsoft.Intercompany.BankAccount;
using Microsoft.Intercompany.Dimension;
using Microsoft.Intercompany.GLAccount;
using Microsoft.Intercompany.Inbox;
using Microsoft.Intercompany.Outbox;
using Microsoft.Intercompany.Partner;
using Microsoft.Intercompany.Setup;
using Microsoft.Inventory.Analysis;
using Microsoft.Inventory.Availability;
using Microsoft.Inventory.BOM.Tree;
using Microsoft.Inventory.BOM;
using Microsoft.Inventory.Comment;
using Microsoft.Inventory.Costing;
using Microsoft.Inventory.Counting.Comment;
using Microsoft.Inventory.Counting.Document;
using Microsoft.Inventory.Counting.History;
using Microsoft.Inventory.Counting.Journal;
using Microsoft.Inventory.Counting.Recording;
using Microsoft.Inventory.Counting.Tracking;
using Microsoft.Inventory.Document;
using Microsoft.Inventory.History;
using Microsoft.Inventory.Intrastat;
using Microsoft.Inventory.Item.Attribute;
using Microsoft.Inventory.Item.Catalog;
using Microsoft.Inventory.Item.Picture;
using Microsoft.Inventory.Item.Substitution;
using Microsoft.Inventory.Item;
using Microsoft.Inventory.Journal;
using Microsoft.Inventory.Ledger;
using Microsoft.Inventory.Location;
using Microsoft.Inventory.Planning;
using Microsoft.Inventory.Reconciliation;
using Microsoft.Inventory.Requisition;
using Microsoft.Inventory.Setup;
using Microsoft.Inventory.Tracking;
using Microsoft.Inventory.Transfer;
using Microsoft.Manufacturing.Capacity;
using Microsoft.Manufacturing.Forecast;
using Microsoft.Manufacturing.Reports;
using Microsoft.Manufacturing.RoleCenters;
using Microsoft.Manufacturing.StandardCost;
using Microsoft.Manufacturing.WorkCenter;
using Microsoft.Pricing.Asset;
using Microsoft.Pricing.Calculation;
using Microsoft.Pricing.PriceList;
using Microsoft.Pricing.Source;
using Microsoft.Pricing.Worksheet;
using Microsoft.Projects.Project.Archive;
using Microsoft.Projects.Project.Job;
using Microsoft.Projects.Project.Journal;
#if not CLEAN25
using Microsoft.Projects.Project.Pricing;
#endif
using Microsoft.Projects.Project.Ledger;
using Microsoft.Projects.Project.Planning;
using Microsoft.Projects.Project.Posting;
using Microsoft.Projects.Project.WIP;
using Microsoft.Projects.Project.Setup;
using Microsoft.Projects.Resources.Analysis;
using Microsoft.Projects.Resources.Journal;
using Microsoft.Projects.Resources.Ledger;
#if not CLEAN25
using Microsoft.Projects.Resources.Pricing;
#endif
using Microsoft.Projects.Resources.Resource;
using Microsoft.Projects.Resources.Setup;
using Microsoft.Projects.RoleCenters;
using Microsoft.Projects.TimeSheet;
using Microsoft.Purchases.Archive;
using Microsoft.Purchases.Comment;
using Microsoft.Purchases.Document;
using Microsoft.Purchases.History;
using Microsoft.Purchases.Payables;
using Microsoft.Purchases.Pricing;
using Microsoft.Purchases.Remittance;
using Microsoft.Purchases.RoleCenters;
using Microsoft.Purchases.Setup;
using Microsoft.Purchases.Vendor;
using Microsoft.RoleCenters;
using Microsoft.Sales.Analysis;
using Microsoft.Sales.Archive;
using Microsoft.Sales.Comment;
using Microsoft.Sales.Customer;
using Microsoft.Sales.Document;
using Microsoft.Sales.FinanceCharge;
using Microsoft.Sales.History;
using Microsoft.Sales.Pricing;
using Microsoft.Sales.Receivables;
using Microsoft.Sales.Reminder;
using Microsoft.Sales.RoleCenters;
using Microsoft.Sales.Setup;
using Microsoft.Utilities;
using Microsoft.Warehouse.Activity;
using Microsoft.Warehouse.Activity.History;
using Microsoft.Warehouse.ADCS;
using Microsoft.Warehouse.Comment;
using Microsoft.Warehouse.CrossDock;
using Microsoft.Warehouse.Document;
using Microsoft.Warehouse.History;
using Microsoft.Warehouse.InternalDocument;
using Microsoft.Warehouse.InventoryDocument;
using Microsoft.Warehouse.Journal;
using Microsoft.Warehouse.Ledger;
using Microsoft.Warehouse.Request;
using Microsoft.Warehouse.RoleCenters;
using Microsoft.Warehouse.Setup;
using Microsoft.Warehouse.Structure;
using Microsoft.Warehouse.Tracking;
using Microsoft.Warehouse.Worksheet;

using System.AI;
using System.Apps;
using System.Automation;
using System.Azure.Identity;
using System.DateTime;
using System.Device;
using System.Diagnostics;
using System.Email;
using System.Environment;
using System.Environment.Configuration;
using System.Globalization;
using System.Integration;
using System.Integration.PowerBI;
using System.IO;
using System.Privacy;
using System.Reflection;
using System.Security.Authentication;
using System.Security.Encryption;
using System.Security.User;
using System.Text;
using System.TestTools;
using System.Threading;
using System.Tooling;
using System.Upgrade;
using System.Utilities;
using System.Visualization;
using System.Xml;

using Microsoft.Service.Contract;
using Microsoft.Service.Document;
using Microsoft.Service.History;
using Microsoft.Service.Item;
using Microsoft.Service.Ledger;
using Microsoft.Service.Loaner;
using Microsoft.Service.Maintenance;
using Microsoft.Service.Resources;
using Microsoft.Service.RoleCenters;
using Microsoft.Service.Setup;

permissionset 7931 "D365 TEAM MEMBER"
{
    Access = Public;
    Assignable = true;
    Caption = 'Dynamics 365 Team Member';

    IncludedPermissionSets = "BaseApp Objects - Exec",
                             "LOGIN",
                             "System App - Basic";

    Permissions = system "Tools, Security, Roles" = X,
                  system "Create a new company" = X,
                  system "Delete a company" = X,
                  system "Rename an existing company" = X,
                  tabledata "Active Session" = m,
                  tabledata "Add-in" = imd,
                  tabledata "Aggregate Permission Set" = Rm,
                  tabledata "All Profile" = m,
                  tabledata "All Profile Extension" = m,
                  tabledata "All Profile Page Metadata" = m,
                  tabledata AllObj = m,
                  tabledata AllObjWithCaption = Rm,
                  tabledata "Alloc. Acc. Manual Override" = RIMD,
                  tabledata "Alloc. Account Distribution" = R,
                  tabledata "Allocation Account" = R,
                  tabledata "Allocation Line" = RIMD,
                  tabledata Chart = m,
                  tabledata Company = M,
                  tabledata "Code Coverage" = Rm,
                  tabledata "CodeUnit Metadata" = m,
                  tabledata "Data Sensitivity" = RM,
                  tabledata Date = m,
#if not CLEAN24
                  tabledata "Deposits Page Setup" = R,
#endif
                  tabledata "Dispute Status" = R,
                  tabledata Device = Rm,
                  tabledata "Document Service" = m,
                  tabledata Drive = Rm,
                  tabledata Entitlement = m,
                  tabledata "Entitlement Set" = m,
                  tabledata "Event Subscription" = Rm,
                  tabledata "Feature Key" = R,
                  tabledata Field = Rm,
                  tabledata File = Rm,
                  tabledata Integer = Rm,
                  tabledata "Intelligent Cloud" = Rimd,
                  tabledata "Intelligent Cloud Status" = Rimd,
                  tabledata Key = Rm,
                  tabledata "License Information" = m,
                  tabledata "License Permission" = m,
                  tabledata Media = m,
                  tabledata "Media Set" = m,
                  tabledata "Membership Entitlement" = m,
                  tabledata "NAV App Installed App" = Rm,
                  tabledata "NAV App Setting" = RIMD,
                  tabledata "Object Access Intent Override" = Rm,
                  tabledata "Object Metadata" = m,
                  tabledata "Object Options" = M,
                  tabledata "Page Metadata" = m,
                  tabledata Permission = m,
                  tabledata "Permission Range" = m,
                  tabledata "Permission Set" = m,
                  tabledata "Profile Configuration Symbols" = m,
                  tabledata "Published Application" = Rm,
                  tabledata "Query Navigation" = RIMD,
                  tabledata "Report Layout" = Rm,
                  tabledata "Report Metadata" = m,
                  tabledata "Scheduled Task" = m,
                  tabledata "Server Instance" = m,
                  tabledata "SID - Account ID" = Rm,
                  tabledata "System Object" = m,
                  tabledata "Table Information" = Rm,
                  tabledata "Table Metadata" = m,
                  tabledata "Table Synch. Setup" = Rm,
                  tabledata "Tenant Profile" = m,
                  tabledata "Tenant Profile Extension" = m,
                  tabledata "Tenant Profile Page Metadata" = m,
                  tabledata "Tenant Profile Setting" = m,
                  tabledata "Time Zone" = m,
                  tabledata "Upgrade Blob Storage" = Rm,
                  tabledata User = RM,
                  tabledata "User Property" = Rimd,
                  tabledata "Windows Language" = m,
                  tabledata "AAD Application" = RM,
                  tabledata "Acc. Sched. Cell Value" = RM,
                  tabledata "Acc. Sched. Chart Setup Line" = RM,
                  tabledata "Acc. Sched. KPI Buffer" = RM,
                  tabledata "Acc. Sched. KPI Web Srv. Line" = RM,
                  tabledata "Acc. Sched. KPI Web Srv. Setup" = RM,
                  tabledata "Acc. Schedule Line" = RM,
                  tabledata "Acc. Schedule Line Entity" = RM,
                  tabledata "Acc. Schedule Name" = RM,
                  tabledata "Financial Report" = RM,
                  tabledata "Financial Report User Filters" = RIMD,
                  tabledata "Account Schedules Chart Setup" = RM,
                  tabledata "Account Use Buffer" = RM,
                  tabledata "Accounting Period" = RM,
                  tabledata "Accounting Services Cue" = RM,
                  tabledata "Action Message Entry" = RM,
                  tabledata "Activities Cue" = RIMD,
                  tabledata Activity = RM,
                  tabledata "Activity Log" = RIMD,
                  tabledata "Activity Step" = RM,
                  tabledata "Additional Fee Setup" = RM,
                  tabledata "Adjust Exchange Rate Buffer" = RM,
                  tabledata "Administration Cue" = RM,
                  tabledata "Aged Report Entity" = RIMD,
                  tabledata "Aging Band Buffer" = RM,
                  tabledata "Alt. Customer Posting Group" = RM,
                  tabledata "Alt. Vendor Posting Group" = RM,
                  tabledata "Alternative Address" = RM,
                  tabledata "Analysis by Dim. Parameters" = RM,
                  tabledata "Analysis by Dim. User Param." = RM,
                  tabledata "Analysis Column" = RM,
                  tabledata "Analysis Column Template" = RM,
                  tabledata "Analysis Dim. Selection Buffer" = RM,
                  tabledata "Analysis Field Value" = RM,
                  tabledata "Analysis Line" = RM,
                  tabledata "Analysis Line Template" = RM,
                  tabledata "Analysis Report Chart Line" = RM,
                  tabledata "Analysis Report Chart Setup" = RM,
                  tabledata "Analysis Report Name" = RM,
                  tabledata "Analysis Selected Dimension" = RM,
                  tabledata "Analysis Type" = RM,
                  tabledata "Analysis View" = RM,
                  tabledata "Analysis View Budget Entry" = RM,
                  tabledata "Analysis View Entry" = RM,
                  tabledata "Analysis View Filter" = RM,
                  tabledata "API Data Upgrade" = RIMD,
                  tabledata "API Entities Setup" = RIMD,
                  tabledata "API Extension Upload" = rimd,
                  tabledata "Application Area Buffer" = RM,
                  tabledata "Application Area Setup" = RM,
                  tabledata "Applied Payment Entry" = RIMD,
                  tabledata "Approval Comment Line" = RIMD,
                  tabledata "Approval Entry" = Rimd,
                  tabledata "Approval Workflow Wizard" = RIMD,
                  tabledata "Approvals Activities Cue" = RIMD,
                  tabledata Area = RM,
                  tabledata "Assemble-to-Order Link" = Rimd,
                  tabledata "Assembly Comment Line" = RM,
                  tabledata "Assembly Header" = Rimd,
                  tabledata "Assembly Line" = RiMd,
                  tabledata "Assembly Setup" = RM,
                  tabledata "Assisted Company Setup Status" = RIMD,
                  tabledata "ATO Sales Buffer" = RM,
                  tabledata Attachment = RM,
                  tabledata "Attachment Entity Buffer" = RIMD,
                  tabledata Attendee = RM,
                  tabledata "Autocomplete Address" = RIMD,
                  tabledata "Availability at Date" = RM,
                  tabledata "Availability Calc. Overview" = RM,
                  tabledata "Average Cost Calc. Overview" = RM,
                  tabledata "Avg. Cost Adjmt. Entry Point" = RIMD,
                  tabledata "Azure AD App Setup" = RM,
                  tabledata "Azure AD Mgt. Setup" = Rim,
                  tabledata "Azure AI Usage" = Rimd,
                  tabledata "Balance Sheet Buffer" = RIMD,
                  tabledata "Bank Acc. Reconciliation" = RM,
                  tabledata "Bank Acc. Reconciliation Line" = RIMD,
                  tabledata "Bank Acc. Rec. Match Buffer" = RIMD,
                  tabledata "Bank Account" = RM,
                  tabledata "Bank Account Balance Buffer" = RIMD,
                  tabledata "Bank Account Ledger Entry" = Rm,
                  tabledata "Bank Account Posting Group" = RM,
                  tabledata "Bank Account Statement" = Rm,
                  tabledata "Bank Account Statement Line" = Rm,
                  tabledata "Bank Clearing Standard" = RM,
                  tabledata "Bank Export/Import Setup" = RM,
                  tabledata "Bank Pmt. Appl. Rule" = RM,
                  tabledata "Bank Pmt. Appl. Settings" = RM,
                  tabledata "Bank Statement Matching Buffer" = RM,
                  tabledata "Bank Stmt Multiple Match Line" = RM,
                  tabledata "Bar Chart Buffer" = RM,
                  tabledata "Base Calendar" = RM,
                  tabledata "Base Calendar Change" = RM,
                  tabledata "Batch Processing Parameter" = Rimd,
                  tabledata "Batch Processing Session Map" = Rimd,
                  tabledata Bin = R,
                  tabledata "Bin Content" = RM,
                  tabledata "Bin Content Buffer" = RM,
                  tabledata "Bin Creation Wksh. Name" = RM,
                  tabledata "Bin Creation Wksh. Template" = RM,
                  tabledata "Bin Creation Worksheet Line" = RM,
                  tabledata "Bin Template" = RM,
                  tabledata "Bin Type" = RM,
                  tabledata "BOM Buffer" = RM,
                  tabledata "BOM Component" = RM,
                  tabledata "BOM Warning Log" = RM,
                  tabledata "Booking Item" = RM,
                  tabledata "Booking Mailbox" = RM,
                  tabledata "Booking Mgr. Setup" = RM,
                  tabledata "Booking Service" = RM,
                  tabledata "Booking Service Mapping" = RM,
                  tabledata "Booking Staff" = RM,
                  tabledata "Booking Sync" = RM,
                  tabledata "Budget Buffer" = RM,
                  tabledata "Bus. Unit In Cons. Process" = RIM,
                  tabledata "Business Chart Buffer" = RM,
                  tabledata "Business Chart Map" = RM,
                  tabledata "Business Chart User Setup" = RIMD,
                  tabledata "Business Relation" = RM,
                  tabledata "Business Unit" = RM,
                  tabledata "Business Unit Information" = RM,
                  tabledata "Business Unit Setup" = RM,
#if not CLEAN24
                  tabledata "Calendar Event" = Rm,
                  tabledata "Calendar Event User Config." = Rm,
#endif
                  tabledata Campaign = RM,
                  tabledata "Campaign Entry" = RM,
                  tabledata "Campaign Status" = RM,
                  tabledata "Campaign Target Group" = RM,
                  tabledata "Cancelled Document" = Rimd,
                  tabledata "Cash Flow Account" = RM,
                  tabledata "Cash Flow Account Comment" = RM,
                  tabledata "Cash Flow Availability Buffer" = RIMD,
                  tabledata "Cash Flow Azure AI Buffer" = Rm,
                  tabledata "Cash Flow Chart Setup" = RM,
                  tabledata "Cash Flow Forecast" = RM,
                  tabledata "Cash Flow Forecast Entry" = RM,
                  tabledata "Cash Flow Manual Expense" = RM,
                  tabledata "Cash Flow Manual Revenue" = RM,
                  tabledata "Cash Flow Report Selection" = RM,
                  tabledata "Cash Flow Setup" = Ri,
                  tabledata "Cash Flow Worksheet Line" = RM,
                  tabledata "Cause of Absence" = RM,
                  tabledata "Cause of Inactivity" = RM,
                  tabledata "CDS Available Virtual Table" = RM,
                  tabledata "CDS BC Table Relation" = R,
                  tabledata "CDS Company" = RM,
                  tabledata "CDS Connection Setup" = RM,
                  tabledata "CDS Coupled Business Unit" = RM,
                  tabledata "CDS Environment" = RM,
                  tabledata "CDS Solution" = RM,
                  tabledata "CDS Teammembership" = RM,
                  tabledata "CDS Teamroles" = RM,
                  tabledata "Certificate of Supply" = RM,
                  tabledata "Change Global Dim. Header" = RM,
                  tabledata "Change Global Dim. Log Entry" = RM,
                  tabledata "Change Log Entry" = Rimd,
                  tabledata "Change Log Setup (Field)" = RM,
                  tabledata "Change Log Setup (Table)" = RM,
                  tabledata "Change Log Setup" = RM,
                  tabledata "Chart Definition" = RM,
                  tabledata "Check Ledger Entry" = RM,
                  tabledata "Close Income Statement Buffer" = RM,
                  tabledata "Close Opportunity Code" = R,
                  tabledata "Column Layout" = RM,
                  tabledata "Column Layout Name" = RM,
                  tabledata "Comment Line" = RM,
                  tabledata "Comment Line Archive" = RIM,
                  tabledata "Communication Method" = RM,
                  tabledata "Company Information" = RM,
                  tabledata "Company Size" = RM,
                  tabledata Confidential = RM,
                  tabledata "Confidential Information" = RM,
                  tabledata "Config. Field Map" = RM,
                  tabledata "Config. Line" = RM,
                  tabledata "Config. Media Buffer" = RM,
                  tabledata "Config. Package Data" = RM,
                  tabledata "Config. Package Error" = RM,
                  tabledata "Config. Package Field" = RM,
                  tabledata "Config. Package Filter" = RM,
                  tabledata "Config. Package Record" = RM,
                  tabledata "Config. Package Table" = RM,
                  tabledata "Config. Question" = RM,
                  tabledata "Config. Question Area" = RM,
                  tabledata "Config. Questionnaire" = RM,
                  tabledata "Config. Record For Processing" = RM,
                  tabledata "Config. Related Field" = RM,
                  tabledata "Config. Related Table" = RM,
                  tabledata "Config. Selection" = RM,
                  tabledata "Config. Setup" = RM,
                  tabledata "Config. Table Processing Rule" = RM,
                  tabledata "Config. Template Header" = RM,
                  tabledata "Config. Template Line" = RIMD,
                  tabledata "Config. Tmpl. Selection Rules" = RIMD,
                  tabledata "Consolidation Account" = RM,
                  tabledata "Consolidation Process" = RIM,
                  tabledata "Consolidation Setup" = RI,
                  tabledata "Cont. Duplicate Search String" = RIMD,
                  tabledata Contact = RM,
                  tabledata "Contact Alt. Addr. Date Range" = RM,
                  tabledata "Contact Alt. Address" = RM,
                  tabledata "Contact Business Relation" = R,
                  tabledata "Contact Dupl. Details Buffer" = RM,
                  tabledata "Contact Duplicate" = RIMD,
                  tabledata "Contact Industry Group" = RM,
                  tabledata "Contact Job Responsibility" = RM,
                  tabledata "Contact Mailing Group" = RM,
                  tabledata "Contact Profile Answer" = RM,
                  tabledata "Contact Value" = RM,
                  tabledata "Contact Web Source" = RM,
                  tabledata "Copy Gen. Journal Parameters" = RIMD,
                  tabledata "Copy Item Buffer" = RM,
                  tabledata "Copy Item Parameters" = RM,
                  tabledata "Cost Accounting Setup" = RM,
                  tabledata "Cost Allocation Source" = RM,
                  tabledata "Cost Allocation Target" = RM,
                  tabledata "Cost Budget Buffer" = Rm,
                  tabledata "Cost Budget Entry" = RM,
                  tabledata "Cost Budget Name" = RM,
                  tabledata "Cost Budget Register" = RM,
                  tabledata "Cost Center" = RM,
                  tabledata "Cost Element Buffer" = RM,
                  tabledata "Cost Entry" = RM,
                  tabledata "Cost Journal Batch" = RM,
                  tabledata "Cost Journal Line" = RM,
                  tabledata "Cost Journal Template" = RM,
                  tabledata "Cost Object" = RM,
                  tabledata "Cost Register" = RM,
                  tabledata "Cost Share Buffer" = RM,
                  tabledata "Cost Type" = RM,
                  tabledata "Country/Region" = RM,
                  tabledata "Country/Region Translation" = RM,
                  tabledata "Coupling Record Buffer" = RM,
                  tabledata "Credit Trans Re-export History" = RM,
                  tabledata "Credit Transfer Entry" = RM,
                  tabledata "Credit Transfer Register" = RM,
                  tabledata "Dataverse Entity Change" = RId,
                  tabledata "CRM Account" = RM,
                  tabledata "CRM Account Statistics" = RM,
                  tabledata "CRM Annotation" = RM,
                  tabledata "CRM Annotation Buffer" = RM,
                  tabledata "CRM Annotation Coupling" = RM,
                  tabledata "CRM Appmodule" = RM,
                  tabledata "CRM BC Virtual Table Config." = RM,
                  tabledata "CRM Businessunit" = RM,
                  tabledata "CRM Company" = RM,
                  tabledata "CRM Connection Setup" = RM,
                  tabledata "CRM Contact" = RM,
                  tabledata "CRM Contract" = RM,
                  tabledata "CRM Customeraddress" = RM,
                  tabledata "CRM Discount" = RM,
                  tabledata "CRM Discounttype" = RM,
                  tabledata "CRM Freight Terms" = R,
                  tabledata "CRM Full Synch. Review Line" = RM,
                  tabledata "CRM Incident" = RM,
                  tabledata "CRM Incidentresolution" = RM,
                  tabledata "CRM Integration Record" = RM,
                  tabledata "CRM Invoice" = RM,
                  tabledata "CRM Invoicedetail" = RM,
                  tabledata "CRM NAV Connection" = RM,
                  tabledata "CRM Opportunity" = RM,
                  tabledata "CRM Option Mapping" = RM,
                  tabledata "CRM Organization" = RM,
                  tabledata "CRM Payment Terms" = R,
                  tabledata "CRM Post" = RM,
                  tabledata "CRM Post Buffer" = RIMD,
                  tabledata "CRM Post Configuration" = RM,
                  tabledata "CRM Pricelevel" = RM,
                  tabledata "CRM Product" = RM,
                  tabledata "CRM Productpricelevel" = RM,
                  tabledata "CRM Quote" = RM,
                  tabledata "CRM Quotedetail" = RM,
                  tabledata "CRM Redirect" = RM,
                  tabledata "CRM Role" = RM,
                  tabledata "CRM Salesorder" = RM,
                  tabledata "CRM Salesorderdetail" = RM,
                  tabledata "CRM Shipping Method" = R,
                  tabledata "CRM Synch Status" = RM,
                  tabledata "CRM Synch. Conflict Buffer" = RM,
                  tabledata "CRM Synch. Job Status Cue" = RM,
                  tabledata "CRM Systemuser" = RM,
                  tabledata "CRM Systemuserroles" = RM,
                  tabledata "CDS Field Security Profile" = RM,
                  tabledata "CDS System User Profiles" = RM,
                  tabledata "CRM Team" = RM,
                  tabledata "CRM Transactioncurrency" = RM,
                  tabledata "CRM Uom" = RM,
                  tabledata "CRM Uomschedule" = RM,
#if not CLEAN25
                  tabledata "FS Connection Setup" = RM,
                  tabledata "FS Bookable Resource" = RM,
                  tabledata "FS Bookable Resource Booking" = RM,
                  tabledata "FS BookableResourceBookingHdr" = RM,
                  tabledata "FS Customer Asset" = RM,
                  tabledata "FS Customer Asset Category" = RM,
                  tabledata "FS Project Task" = RM,
                  tabledata "FS Resource Pay Type" = RM,
                  tabledata "FS Work Order" = RM,
                  tabledata "FS Work Order Incident" = RM,
                  tabledata "FS Work Order Product" = RM,
                  tabledata "FS Work Order Service" = RM,
                  tabledata "FS Work Order Substatus" = RM,
                  tabledata "FS Work Order Type" = RM,
#endif
                  tabledata "CSV Buffer" = RM,
                  tabledata "Curr. Exch. Rate Update Setup" = RM,
                  tabledata Currency = RM,
                  tabledata "Currency Amount" = RM,
                  tabledata "Currency Exchange Rate" = RM,
                  tabledata "Currency for Fin. Charge Terms" = RM,
                  tabledata "Currency for Reminder Level" = RM,
                  tabledata "Currency Total Buffer" = RM,
                  tabledata "Current Salesperson" = RM,
                  tabledata "Cust. Invoice Disc." = RIMD,
                  tabledata "Cust. Ledger Entry" = RiMd,
                  tabledata "Custom Address Format" = RM,
                  tabledata "Custom Address Format Line" = RM,
                  tabledata "Custom Report Layout" = RM,
                  tabledata "Custom Report Selection" = RIMD,
                  tabledata Customer = RM,
                  tabledata "Customer Amount" = RM,
                  tabledata "Customer Bank Account" = RM,
                  tabledata "Customer Discount Group" = RM,
                  tabledata "Customer Posting Group" = RM,
                  tabledata "Customer Price Group" = RM,
                  tabledata "Customer Sales Buffer" = RIMD,
                  tabledata "Customer Templ." = RIMD,
                  tabledata "Customized Calendar Change" = RM,
                  tabledata "Customized Calendar Entry" = RM,
                  tabledata "CV Ledger Entry Buffer" = RM,
                  tabledata "Data Exch." = RM,
                  tabledata "Data Exch. Column Def" = RM,
                  tabledata "Data Exch. Def" = RM,
                  tabledata "Data Exch. Field" = RM,
                  tabledata "Data Exch. Field Mapping" = RM,
                  tabledata "Data Exch. Field Mapping Buf." = RM,
                  tabledata "Data Exch. Line Def" = RM,
                  tabledata "Data Exch. Mapping" = RM,
                  tabledata "Data Exch. Field Grouping" = RM,
                  tabledata "Data Exch. FlowField Gr. Buff." = RM,
                  tabledata "Data Exchange Type" = RM,
                  tabledata "Data Exch. Table Filter" = RM,
                  tabledata "Data Migration Entity" = RM,
                  tabledata "Data Migration Error" = RIMD,
                  tabledata "Data Migration Parameters" = RIMD,
                  tabledata "Data Migration Setup" = RM,
                  tabledata "Data Migration Status" = RIMD,
                  tabledata "Data Migrator Registration" = RM,
                  tabledata "Data Privacy Records" = RM,
                  tabledata "DataExch-RapidStart Buffer" = RM,
                  tabledata "Date Compr. Register" = Rm,
                  tabledata "Date Lookup Buffer" = RIMD,
                  tabledata "Default Dimension" = RM,
                  tabledata "Default Dimension Priority" = RM,
                  tabledata "Deferral Header" = RIMD,
                  tabledata "Deferral Header Archive" = RIMD,
                  tabledata "Deferral Line" = RIMD,
                  tabledata "Deferral Line Archive" = RIMD,
                  tabledata "Deferral Posting Buffer" = RM,
                  tabledata "Deferral Template" = RM,
                  tabledata "Delivery Sorter" = RM,
                  tabledata "Depreciation Book" = RM,
                  tabledata "Depreciation Table Buffer" = RM,
                  tabledata "Depreciation Table Header" = RM,
                  tabledata "Depreciation Table Line" = RM,
                  tabledata "Detailed Cust. Ledg. Entry" = Rimd,
                  tabledata "Detailed CV Ledg. Entry Buffer" = RM,
                  tabledata "Detailed Employee Ledger Entry" = Rimd,
                  tabledata "Detailed Vendor Ledg. Entry" = Rimd,
                  tabledata "Dim Correct Selection Criteria" = R,
                  tabledata "Dim Correction Blocked Setup" = R,
                  tabledata "Dim Correction Change" = R,
                  tabledata "Dim Correction Set Buffer" = R,
                  tabledata "Dim Correction Entry Log" = R,
                  tabledata "Dim. Value per Account" = RM,
                  tabledata Dimension = RM,
                  tabledata "Dimension Buffer" = RM,
                  tabledata "Dimension Code Amount Buffer" = RM,
                  tabledata "Dimension Code Buffer" = RM,
                  tabledata "Dimension Combination" = RM,
                  tabledata "Dimension Correction" = R,
                  tabledata "Dimension Entry Buffer" = RM,
                  tabledata "Dimension ID Buffer" = RM,
                  tabledata "Dimension Selection Buffer" = RM,
                  tabledata "Dimension Set Entry" = Rimd,
                  tabledata "Dimension Set Entry Buffer" = RIMD,
                  tabledata "Dimension Set ID Filter Line" = RM,
                  tabledata "Dimension Set Tree Node" = Rimd,
                  tabledata "Dimension Translation" = RM,
                  tabledata "Dimension Value" = RM,
                  tabledata "Dimension Value Combination" = RM,
                  tabledata "Dimensions Field Map" = RM,
                  tabledata "Dimensions Template" = RM,
                  tabledata "Direct Debit Collection" = RM,
                  tabledata "Direct Debit Collection Entry" = RM,
                  tabledata "Doc. Exch. Service Setup" = RM,
                  tabledata "Document Attachment" = RIMD,
                  tabledata "Document Entry" = RM,
                  tabledata "Document Search Result" = RM,
                  tabledata "Document Sending Profile" = RM,
#if not CLEAN23
                  tabledata "Document Service Cache" = Rm,
#endif
                  tabledata "Drop Shpt. Post. Buffer" = RM,
                  tabledata "Dtld. Price Calculation Setup" = RIMD,
                  tabledata "Duplicate Price Line" = RIMD,
                  tabledata "Duplicate Search String Setup" = RM,
                  tabledata "Dynamic Request Page Entity" = RM,
                  tabledata "Dynamic Request Page Field" = RM,
                  tabledata "ECSL VAT Report Line" = RIMD,
                  tabledata "ECSL VAT Report Line Relation" = RIMD,
                  tabledata "Electronic Document Format" = RM,
                  tabledata "Email Item" = RM,
                  tabledata "Email Parameter" = RM,
                  tabledata Employee = RM,
                  tabledata "Employee Absence" = RIMD,
                  tabledata "Employee Ledger Entry" = Rimd,
                  tabledata "Employee Payment Buffer" = RM,
                  tabledata "Employee Posting Group" = RM,
                  tabledata "Employee Qualification" = RM,
                  tabledata "Employee Relative" = RM,
                  tabledata "Employee Statistics Group" = RM,
                  tabledata "Employee Templ." = RIMD,
                  tabledata "Employee Time Reg Buffer" = RIMD,
                  tabledata "Employment Contract" = RM,
                  tabledata "Entry No. Amount Buffer" = RM,
                  tabledata "Entry Summary" = RM,
                  tabledata "Entry/Exit Point" = RM,
                  tabledata "Error Buffer" = RM,
                  tabledata "Error Handling Parameters" = RM,
                  tabledata "Error Message" = RIMD,
                  tabledata "Error Message Register" = RIMD,
                  tabledata "Excel Buffer" = RM,
                  tabledata "Excel Template Storage" = RM,
                  tabledata "Exch. Rate Adjmt. Reg." = Rm,
                  tabledata "Exch. Rate Adjmt. Ledg. Entry" = Rm,
                  tabledata "Exchange Contact" = RM,
                  tabledata "Exchange Folder" = RM,
                  tabledata "Exchange Object" = RM,
                  tabledata "Exchange Service Setup" = RM,
                  tabledata "Exchange Sync" = RM,
#if not CLEAN24
                  tabledata "Exp. Phys. Invt. Tracking" = RM,
#endif
                  tabledata "Exp. Invt. Order Tracking" = RM,
                  tabledata "Experience Tier Buffer" = RM,
                  tabledata "Experience Tier Setup" = RM,
                  tabledata "Extended Text Header" = RM,
                  tabledata "Extended Text Line" = RM,
                  tabledata "FA Allocation" = RM,
                  tabledata "FA Buffer Projection" = RM,
                  tabledata "FA Class" = RM,
                  tabledata "FA Date Type" = RM,
                  tabledata "FA Depreciation Book" = RM,
                  tabledata "FA G/L Posting Buffer" = RM,
                  tabledata "FA Journal Batch" = RM,
                  tabledata "FA Journal Line" = RM,
                  tabledata "FA Journal Setup" = RM,
                  tabledata "FA Journal Template" = RM,
                  tabledata "FA Ledger Entry" = Rm,
                  tabledata "FA Location" = RM,
                  tabledata "FA Matrix Posting Type" = RM,
                  tabledata "FA Posting Group" = RM,
                  tabledata "FA Posting Group Buffer" = RM,
                  tabledata "FA Posting Type" = RM,
                  tabledata "FA Posting Type Setup" = RM,
                  tabledata "FA Reclass. Journal Batch" = RM,
                  tabledata "FA Reclass. Journal Line" = RM,
                  tabledata "FA Reclass. Journal Template" = RM,
                  tabledata "FA Register" = Rm,
                  tabledata "FA Setup" = RM,
                  tabledata "FA Subclass" = RM,
                  tabledata "Field Monitoring Setup" = Rm,
                  tabledata "Filter Item Attributes Buffer" = RM,
                  tabledata "Fin. Charge Comment Line" = RM,
                  tabledata "Finance Charge Interest Rate" = RM,
                  tabledata "Finance Charge Memo Header" = RM,
                  tabledata "Finance Charge Memo Line" = RM,
                  tabledata "Finance Charge Terms" = RM,
                  tabledata "Finance Charge Text" = RM,
                  tabledata "Finance Cue" = RM,
                  tabledata "Fixed Asset" = RM,
                  tabledata "Flow Service Configuration" = Rimd,
                  tabledata "Flow User Environment Buffer" = RIMD,
                  tabledata "Flow User Environment Config" = RIMD,
                  tabledata "G/L - Item Ledger Relation" = RM,
                  tabledata "G/L Acc. Balance Buffer" = RIMD,
                  tabledata "G/L Acc. Balance/Budget Buffer" = RIMD,
                  tabledata "G/L Acc. Budget Buffer" = RM,
                  tabledata "G/L Account (Analysis View)" = RM,
                  tabledata "G/L Account" = RM,
                  tabledata "G/L Account Category" = RM,
                  tabledata "G/L Account Net Change" = RM,
                  tabledata "G/L Account Where-Used" = RM,
                  tabledata "G/L Account Source Currency" = RMID,
                  tabledata "G/L Budget Entry" = RM,
                  tabledata "G/L Budget Name" = RM,
                  tabledata "G/L Entry - VAT Entry Link" = Rimd,
                  tabledata "G/L Entry" = Rimd,
                  tabledata "G/L Register" = Rimd,
                  tabledata "Gen. Business Posting Group" = RM,
                  tabledata "Gen. Jnl. Allocation" = RM,
                  tabledata "Gen. Jnl. Dim. Filter" = RM,
                  tabledata "Gen. Journal Batch" = RM,
                  tabledata "Gen. Journal Line" = RM,
                  tabledata "Gen. Journal Template" = RM,
                  tabledata "Gen. Product Posting Group" = RM,
                  tabledata "General Ledger Setup" = RIM,
                  tabledata "General Posting Setup" = RM,
                  tabledata "Generic Chart Captions Buffer" = RM,
                  tabledata "Generic Chart Filter" = RM,
                  tabledata "Generic Chart Memo Buffer" = RM,
                  tabledata "Generic Chart Query Column" = RM,
                  tabledata "Generic Chart Setup" = RM,
                  tabledata "Generic Chart Y-Axis" = RM,
                  tabledata Geolocation = RM,
                  tabledata "Grounds for Termination" = RM,
                  tabledata "Handled IC Inbox Jnl. Line" = RM,
                  tabledata "Handled IC Inbox Purch. Header" = RM,
                  tabledata "Handled IC Inbox Purch. Line" = RM,
                  tabledata "Handled IC Inbox Sales Header" = RM,
                  tabledata "Handled IC Inbox Sales Line" = RM,
                  tabledata "Handled IC Inbox Trans." = RM,
                  tabledata "Handled IC Outbox Jnl. Line" = RM,
                  tabledata "Handled IC Outbox Purch. Hdr" = RM,
                  tabledata "Handled IC Outbox Purch. Line" = RM,
                  tabledata "Handled IC Outbox Sales Header" = RM,
                  tabledata "Handled IC Outbox Sales Line" = RM,
                  tabledata "Handled IC Outbox Trans." = RM,
                  tabledata "HR Confidential Comment Line" = RM,
                  tabledata "Human Resource Comment Line" = RM,
                  tabledata "Human Resource Unit of Measure" = RM,
                  tabledata "Human Resources Setup" = RM,
                  tabledata "Hybrid Deployment Setup" = RIMD,
                  tabledata "IC Bank Account" = RM,
                  tabledata "IC Comment Line" = RM,
                  tabledata "IC Dimension" = RM,
                  tabledata "IC Dimension Value" = RM,
                  tabledata "IC Document Dimension" = RM,
                  tabledata "IC G/L Account" = RM,
                  tabledata "IC Inbox Jnl. Line" = RM,
                  tabledata "IC Inbox Purchase Header" = RM,
                  tabledata "IC Inbox Purchase Line" = RM,
                  tabledata "IC Inbox Sales Header" = RM,
                  tabledata "IC Inbox Sales Line" = RM,
                  tabledata "IC Inbox Transaction" = RM,
                  tabledata "IC Inbox/Outbox Jnl. Line Dim." = RM,
                  tabledata "IC Outbox Jnl. Line" = RM,
                  tabledata "IC Outbox Purchase Header" = RM,
                  tabledata "IC Outbox Purchase Line" = RM,
                  tabledata "IC Outbox Sales Header" = RM,
                  tabledata "IC Outbox Sales Line" = RM,
                  tabledata "IC Outbox Transaction" = RM,
                  tabledata "IC Partner" = RM,
                  tabledata "IC Setup" = RM,
                  tabledata "Image Analysis Setup" = RM,
                  tabledata "Image Analysis Scenario" = R,
                  tabledata "Import G/L Transaction" = RM,
                  tabledata "Incoming Document" = RM,
                  tabledata "Incoming Document Approver" = RM,
                  tabledata "Incoming Document Attachment" = RM,
                  tabledata "Incoming Documents Setup" = RM,
                  tabledata "Industry Group" = RM,
                  tabledata "Ins. Coverage Ledger Entry" = Rm,
                  tabledata Insurance = RM,
                  tabledata "Insurance Journal Batch" = RM,
                  tabledata "Insurance Journal Line" = RM,
                  tabledata "Insurance Journal Template" = RM,
                  tabledata "Insurance Register" = Rm,
                  tabledata "Insurance Type" = RM,
                  tabledata "Int. Table Config Template" = RIMD,
                  tabledata "Integration Field Mapping" = RIMD,
                  tabledata "Integration Synch. Job" = RIMD,
                  tabledata "Integration Synch. Job Errors" = RIMD,
                  tabledata "Integration Table Mapping" = RIMD,
                  tabledata "Inter. Log Entry Comment Line" = RIMd,
                  tabledata "Interaction Group" = RM,
                  tabledata "Interaction Log Entry" = RIMD,
                  tabledata "Interaction Merge Data" = RM,
                  tabledata "Interaction Template" = RM,
                  tabledata "Interaction Template Setup" = RM,
                  tabledata "Interaction Tmpl. Language" = RM,
                  tabledata "Intermediate Data Import" = RM,
                  tabledata "Internal Movement Header" = RM,
                  tabledata "Internal Movement Line" = RM,
                  tabledata "Invalidated Dim Correction" = R,
                  tabledata "Inventory Adjmt. Entry (Order)" = Rm,
                  tabledata "Inventory Adjustment Buffer" = Rm,
                  tabledata "Inventory Buffer" = RM,
                  tabledata "Inventory Comment Line" = RM,
                  tabledata "Inventory Event Buffer" = RM,
                  tabledata "Inventory Page Data" = RM,
                  tabledata "Inventory Period" = RM,
                  tabledata "Inventory Period Entry" = RM,
                  tabledata "Inventory Posting Group" = RM,
                  tabledata "Inventory Posting Setup" = RM,
                  tabledata "Inventory Profile Track Buffer" = RM,
                  tabledata "Inventory Report Entry" = RM,
                  tabledata "Inventory Report Header" = RM,
                  tabledata "Inventory Setup" = RM,
#if not CLEAN23
                  tabledata "Invoice Post. Buffer" = RM,
#endif
                  tabledata "Invoice Posting Buffer" = RM,
                  tabledata "Invoiced Booking Item" = RM,
                  tabledata "Invt. Document Header" = RIMD,
                  tabledata "Invt. Document Line" = RIMD,
                  tabledata "Invt. Post to G/L Test Buffer" = RM,
                  tabledata "Invt. Posting Buffer" = RM,
                  tabledata "Invt. Receipt Header" = Rm,
                  tabledata "Invt. Receipt Line" = Rm,
                  tabledata "Invt. Shipment Header" = Rm,
                  tabledata "Invt. Shipment Line" = Rm,
                  tabledata "Isolated Certificate" = RIMD,
                  tabledata "Issued Fin. Charge Memo Header" = Rm,
                  tabledata "Issued Fin. Charge Memo Line" = Rm,
                  tabledata "Issued Reminder Header" = Rm,
                  tabledata "Issued Reminder Line" = Rm,
                  tabledata Item = RM,
                  tabledata "Item Amount" = RM,
                  tabledata "Item Analysis View" = RM,
                  tabledata "Item Analysis View Budg. Entry" = RM,
                  tabledata "Item Analysis View Entry" = RM,
                  tabledata "Item Analysis View Filter" = RM,
                  tabledata "Item Application Entry" = RImd,
                  tabledata "Item Application Entry History" = RIMD,
                  tabledata "Item Attr. Value Translation" = RM,
                  tabledata "Item Attribute" = RM,
                  tabledata "Item Attribute Translation" = RM,
                  tabledata "Item Attribute Value" = RIMD,
                  tabledata "Item Attribute Value Mapping" = RM,
                  tabledata "Item Attribute Value Selection" = RM,
                  tabledata "Item Availability Buffer" = RIMD,
                  tabledata "Item Availability by Date" = RM,
                  tabledata "Item Availability Line" = RM,
                  tabledata "Item Budget Buffer" = RM,
                  tabledata "Item Budget Entry" = RM,
                  tabledata "Item Budget Name" = RM,
                  tabledata "Item Category" = RM,
                  tabledata "Item Charge" = R,
                  tabledata "Item Charge Assignment (Purch)" = RIMD,
                  tabledata "Item Charge Assignment (Sales)" = RIMD,
                  tabledata "Item Discount Group" = RM,
                  tabledata "Item Entry Relation" = R,
                  tabledata "Item Identifier" = RM,
                  tabledata "Item Journal Batch" = RM,
                  tabledata "Item Journal Buffer" = RM,
                  tabledata "Item Journal Line" = RM,
                  tabledata "Item Journal Template" = RM,
                  tabledata "Item Ledger Entry" = Rimd,
                  tabledata "Item Picture Buffer" = RM,
                  tabledata "Item Reference" = RIMD,
                  tabledata "Item Register" = Rimd,
                  tabledata "Item Statistics Buffer" = RM,
                  tabledata "Item Substitution" = RIMD,
                  tabledata "Item Templ." = RIMD,
                  tabledata "Item Tracing Buffer" = Rimd,
                  tabledata "Item Tracing History Buffer" = Rimd,
                  tabledata "Item Tracking Code" = R,
                  tabledata "Item Tracking Comment" = RM,
                  tabledata "Item Translation" = RM,
                  tabledata "Item Turnover Buffer" = RIMD,
                  tabledata "Item Unit of Measure" = RIMD,
                  tabledata "Item Variant" = RM,
                  tabledata "Item Vendor" = RIMD,
                  tabledata Job = RIMD,
                  tabledata "Job Archive" = RIMD,
                  tabledata "Job Buffer" = Rm,
                  tabledata "Job Cue" = RM,
                  tabledata "Job Difference Buffer" = Rm,
                  tabledata "Job Entry No." = RM,
#if not CLEAN25
                  tabledata "Job G/L Account Price" = RM,
                  tabledata "Job Item Price" = RM,
#endif
                  tabledata "Job Journal Batch" = RM,
                  tabledata "Job Journal Line" = RM,
                  tabledata "Job Journal Quantity" = RM,
                  tabledata "Job Journal Template" = RM,
                  tabledata "Job Ledger Entry" = Rm,
                  tabledata "Job Planning Line - Calendar" = RM,
                  tabledata "Job Planning Line" = RIM,
                  tabledata "Job Planning Line Archive" = RIM,
                  tabledata "Job Planning Line Invoice" = RM,
                  tabledata "Job Posting Buffer" = RM,
                  tabledata "Job Posting Group" = RM,
                  tabledata "Job Queue Category" = RIMD,
                  tabledata "Job Queue Entry" = RIMD,
                  tabledata "Job Queue Entry Buffer" = RIMD,
                  tabledata "Job Queue Log Entry" = RIMD,
                  tabledata "Job Queue Role Center Cue" = RIMD,
                  tabledata "Job Queue Notification Setup" = RIMD,
                  tabledata "Job Queue Notified Admin" = RM,
                  tabledata "Job Register" = Rm,
#if not CLEAN25
                  tabledata "Job Resource Price" = RM,
#endif
                  tabledata "Job Responsibility" = RM,
                  tabledata "Job Task" = RIMD,
                  tabledata "Job Task Archive" = RIMD,
                  tabledata "Job Task Dimension" = RIMD,
                  tabledata "Job Usage Link" = RM,
                  tabledata "Job WIP Buffer" = Rm,
                  tabledata "Job WIP Entry" = RM,
                  tabledata "Job WIP G/L Entry" = Rm,
                  tabledata "Job WIP Method" = RM,
                  tabledata "Job WIP Total" = RM,
                  tabledata "Job WIP Warning" = RM,
                  tabledata "Jobs Setup" = RM,
                  tabledata "Journal User Preferences" = RM,
                  tabledata "JSON Buffer" = RM,
                  tabledata "Last Used Chart" = RIMD,
                  tabledata "Ledger Entry Matching Buffer" = RM,
                  tabledata "License Agreement" = RM,
                  tabledata "Line Fee Note on Report Hist." = Rm,
                  tabledata "Line Number Buffer" = RM,
                  tabledata "Load Buffer" = RIMD,
                  tabledata Location = RM,
                  tabledata "Logged Segment" = RM,
                  tabledata "Lot Bin Buffer" = RM,
                  tabledata "Lot No. Information" = RIMD,
                  tabledata "Mailing Group" = RM,
                  tabledata "Main Asset Component" = RM,
                  tabledata Maintenance = RM,
                  tabledata "Maintenance Ledger Entry" = Rm,
                  tabledata "Maintenance Registration" = RM,
                  tabledata "Man. Integration Field Mapping" = RIMD,
                  tabledata "Man. Integration Table Mapping" = RIMD,
                  tabledata "Man. Int. Field Mapping" = RIMD,
                  tabledata Manufacturer = RM,
                  tabledata "Manufacturing Cue" = RM,
                  tabledata "Marketing Setup" = RM,
                  tabledata "Media Repository" = RM,
                  tabledata "Memoized Result" = RM,
                  tabledata "Misc. Article" = RM,
                  tabledata "Misc. Article Information" = RM,
                  tabledata "MS-QBD Setup" = R,
                  tabledata "My Account" = RIMD,
                  tabledata "My Customer" = RIMD,
                  tabledata "My Item" = RIMD,
                  tabledata "My Job" = RIMD,
                  tabledata "My Notifications" = RIMD,
                  tabledata "My Time Sheets" = RIMD,
                  tabledata "My Vendor" = RIMD,
                  tabledata "Name/Value Buffer" = RM,
                  tabledata "Named Forward Link" = RM,
                  tabledata "No. Series" = RM,
                  tabledata "No. Series Line" = RM,
                  tabledata "No. Series Relationship" = RM,
                  tabledata "No. Series Tenant" = RM,
                  tabledata "Nonstock Item" = RM,
                  tabledata "Nonstock Item Setup" = RM,
                  tabledata "Notification Context" = RIMD,
                  tabledata "Notification Entry" = RIMD,
                  tabledata "Notification Schedule" = RM,
                  tabledata "Notification Setup" = RM,
                  tabledata "O365 Brand Color" = RM,
                  tabledata "O365 Device Setup Instructions" = RIMD,
                  tabledata "O365 Getting Started" = RIMD,
                  tabledata "O365 Getting Started Page Data" = RIMD,
                  tabledata "O365 HTML Template" = RM,
                  tabledata "O365 Payment Service Logo" = RM,
                  tabledata "OAuth 2.0 Setup" = RIMD,
                  tabledata "Object Translation" = RM,
                  tabledata "OCR Service Document Template" = RM,
                  tabledata "OCR Service Setup" = RM,
                  tabledata "OData Initialized Status" = RM,
                  tabledata "Office Add-in" = RIMD,
                  tabledata "Office Add-in Context" = RIMD,
                  tabledata "Office Add-in Setup" = RIMD,
                  tabledata "Office Admin. Credentials" = Rimd,
                  tabledata "Office Contact Details" = RIMD,
                  tabledata "Office Document Selection" = RIMD,
                  tabledata "Office Invoice" = RIMD,
                  tabledata "Office Job Journal" = RIMD,
                  tabledata "Office Suggested Line Item" = RIMD,
                  tabledata "Online Bank Acc. Link" = RM,
                  tabledata "Online Map Parameter Setup" = RM,
                  tabledata "Online Map Setup" = RM,
                  tabledata Opportunity = R,
                  tabledata "Opportunity Entry" = RIM,
                  tabledata "Option Lookup Buffer" = rm,
                  tabledata "Order Address" = RIMD,
                  tabledata "Order Promising Line" = RM,
                  tabledata "Order Promising Setup" = RM,
                  tabledata "Order Tracking Entry" = RIMD,
                  tabledata "Organizational Level" = RM,
                  tabledata "Outstanding Bank Transaction" = RM,
                  tabledata "Over-Receipt Code" = RIMD,
                  tabledata "Overdue Approval Entry" = Rm,
                  tabledata "Package No. Information" = RIMD,
                  tabledata "Payable Employee Ledger Entry" = RM,
                  tabledata "Payable Vendor Ledger Entry" = RM,
                  tabledata "Payment Application Proposal" = RM,
                  tabledata "Vendor Payment Buffer" = RM,
                  tabledata "Payment Export Data" = Rm,
                  tabledata "Payment Export Remittance Text" = RM,
                  tabledata "Payment Jnl. Export Error Text" = RM,
                  tabledata "Payment Matching Details" = RIMD,
                  tabledata "Payment Method" = RM,
                  tabledata "Payment Method Translation" = RM,
                  tabledata "Payment Rec. Related Entry" = RIMD,
                  tabledata "Pmt. Rec. Applied-to Entry" = RIMD,
                  tabledata "Payment Registration Buffer" = RM,
                  tabledata "Payment Registration Setup" = RM,
                  tabledata "Payment Reporting Argument" = Rm,
                  tabledata "Payment Service Setup" = RM,
                  tabledata "Payment Term Translation" = RM,
                  tabledata "Payment Terms" = RMD,
                  tabledata "Payroll Import Buffer" = RM,
                  tabledata "Payroll Setup" = RM,
                  tabledata "Permission Buffer" = RIMD,
                  tabledata "Permission Conflicts" = RIMD,
                  tabledata "Permission Conflicts Overview" = RIMD,
                  tabledata "Permission Set Buffer" = RIMD,
                  tabledata "Permission Set Link" = rm,
                  tabledata "Phys. Inventory Ledger Entry" = Rm,
                  tabledata "Phys. Invt. Comment Line" = RM,
                  tabledata "Phys. Invt. Count Buffer" = RM,
                  tabledata "Phys. Invt. Counting Period" = RM,
                  tabledata "Phys. Invt. Item Selection" = RM,
                  tabledata "Phys. Invt. Order Header" = RM,
                  tabledata "Phys. Invt. Order Line" = RM,
                  tabledata "Phys. Invt. Record Header" = RM,
                  tabledata "Phys. Invt. Record Line" = RM,
#if not CLEAN24
                  tabledata "Phys. Invt. Tracking" = RM,
#endif
                  tabledata "Invt. Order Tracking" = RM,
                  tabledata "Picture Entity" = RIMD,
                  tabledata "Planning Assignment" = Rim,
                  tabledata "Planning Buffer" = RM,
                  tabledata "Planning Component" = Rm,
                  tabledata "Planning Error Log" = RM,
                  tabledata "Positive Pay Detail" = RM,
                  tabledata "Positive Pay Entry" = RM,
                  tabledata "Positive Pay Entry Detail" = RM,
                  tabledata "Positive Pay Footer" = RM,
                  tabledata "Positive Pay Header" = RM,
                  tabledata "Post Code" = RM,
                  tabledata "Post Value Entry to G/L" = RImd,
                  tabledata "Postcode Service Config" = RIMD,
                  tabledata "Posted Approval Comment Line" = Rm,
                  tabledata "Posted Approval Entry" = Rm,
                  tabledata "Posted Assemble-to-Order Link" = RM,
                  tabledata "Posted Assembly Header" = RM,
                  tabledata "Posted Assembly Line" = RM,
                  tabledata "Posted Deferral Header" = RM,
                  tabledata "Posted Deferral Line" = RM,
                  tabledata "Posted Docs. With No Inc. Buf." = RM,
                  tabledata "Posted Gen. Journal Batch" = RIMD,
                  tabledata "Posted Gen. Journal Line" = RIMD,
                  tabledata "Posted Invt. Pick Header" = RM,
                  tabledata "Posted Invt. Pick Line" = RM,
                  tabledata "Posted Invt. Put-away Header" = RM,
                  tabledata "Posted Invt. Put-away Line" = RM,
                  tabledata "Posted Payment Recon. Hdr" = RM,
                  tabledata "Posted Payment Recon. Line" = RM,
                  tabledata "Posted Whse. Receipt Header" = RM,
                  tabledata "Posted Whse. Receipt Line" = RM,
                  tabledata "Posted Whse. Shipment Header" = RM,
                  tabledata "Posted Whse. Shipment Line" = RM,
#if not CLEAN23
                  tabledata "Power BI User Configuration" = RIMD,
                  tabledata "Power BI Report Configuration" = RIMD,
                  tabledata "Power BI User Status" = RIMD,
#endif
                  tabledata "Power BI Chart Buffer" = RIMD,
                  tabledata "Power BI Context Settings" = RIMD,
                  tabledata "Power BI Customer Reports" = RIMD,
                  tabledata "Power BI Displayed Element" = RIMD,
                  tabledata "Power BI Report Labels" = R,
                  tabledata "Power BI Report Uploads" = RIMD,
                  tabledata "Prepayment Inv. Line Buffer" = RM,
                  tabledata "Price Asset" = RIMD,
                  tabledata "Price Calculation Buffer" = RIMD,
                  tabledata "Price Calculation Setup" = RIMD,
                  tabledata "Price Line Filters" = RIMD,
                  tabledata "Price List Header" = RIMD,
                  tabledata "Price List Line" = RIMD,
                  tabledata "Price Source" = RIMD,
                  tabledata "Price Worksheet Line" = RIMD,
                  tabledata "Printer Selection" = RM,
                  tabledata "Production Forecast Entry" = RM,
                  tabledata "Production Forecast Name" = RM,
                  tabledata "Profile Questionnaire Header" = RM,
                  tabledata "Profile Questionnaire Line" = RM,
#if not CLEAN24
                  tabledata "Pstd. Exp. Phys. Invt. Track" = RM,
#endif
                  tabledata "Pstd.Exp.Invt.Order.Tracking" = RM,
                  tabledata "Pstd. Phys. Invt. Order Hdr" = RM,
                  tabledata "Pstd. Phys. Invt. Order Line" = RM,
                  tabledata "Pstd. Phys. Invt. Record Hdr" = RM,
                  tabledata "Pstd. Phys. Invt. Record Line" = RM,
                  tabledata "Pstd. Phys. Invt. Tracking" = RM,
                  tabledata "Purch. Comment Line" = RM,
                  tabledata "Purch. Comment Line Archive" = RM,
                  tabledata "Purch. Cr. Memo Entity Buffer" = RIMD,
                  tabledata "Purch. Cr. Memo Hdr." = RIMD,
                  tabledata "Purch. Cr. Memo Line" = Rimd,
                  tabledata "Purch. Inv. Entity Aggregate" = RIMD,
                  tabledata "Purch. Inv. Header" = RimD,
                  tabledata "Purch. Inv. Line" = Rimd,
                  tabledata "Purch. Inv. Line Aggregate" = RIMD,
#if not CLEAN25
                  tabledata "Purch. Price Line Disc. Buff." = RM,
#endif
                  tabledata "Purch. Rcpt. Header" = RIMD,
                  tabledata "Purch. Rcpt. Line" = Rimd,
                  tabledata "Purchase Cue" = RM,
                  tabledata "Purchase Discount Access" = RM,
                  tabledata "Purchase Header" = RIMD,
                  tabledata "Purchase Header Archive" = RIMD,
                  tabledata "Purchase Line" = RIMD,
                  tabledata "Purchase Line Archive" = RIMD,
#if not CLEAN25
                  tabledata "Purchase Line Discount" = RM,
#endif
                  tabledata "Purchase Order Entity Buffer" = RMID,
                  tabledata "Purchase Prepayment %" = RM,
#if not CLEAN25
                  tabledata "Purchase Price" = RM,
#endif
                  tabledata "Purchase Price Access" = RM,
                  tabledata "Purchases & Payables Setup" = RM,
                  tabledata Purchasing = RM,
                  tabledata "Put-away Template Header" = RM,
                  tabledata "Put-away Template Line" = RM,
                  tabledata Qualification = RM,
                  tabledata "Query Metadata" = m,
                  tabledata "RapidStart Services Cue" = RM,
                  tabledata Rating = RM,
                  tabledata "RC Headlines User Data" = RIMD,
                  tabledata "Reason Code" = RM,
                  tabledata "Receivables-Payables Buffer" = RIMD,
                  tabledata "Reclas. Dimension Set Buffer" = RM,
                  tabledata "Reconcile CV Acc Buffer" = RM,
                  tabledata "Record Buffer" = Rimd,
                  tabledata "Record Export Buffer" = RM,
                  tabledata "Record Set Buffer" = Rimd,
                  tabledata "Record Set Definition" = Rimd,
                  tabledata "Record Set Tree" = Rimd,
                  tabledata "Recorded Event Buffer" = RM,
                  tabledata "Referenced XML Schema" = RM,
                  tabledata "Registered Invt. Movement Hdr." = Rm,
                  tabledata "Registered Invt. Movement Line" = Rm,
                  tabledata "Registered Whse. Activity Hdr." = Rm,
                  tabledata "Registered Whse. Activity Line" = Rm,
                  tabledata "Relationship Mgmt. Cue" = RM,
                  tabledata Relative = RM,
                  tabledata "Reminder Attachment Text" = RM,
                  tabledata "Reminder Attachment Text Line" = RM,
                  tabledata "Reminder Comment Line" = RM,
                  tabledata "Reminder Email Text" = RM,
                  tabledata "Reminder Header" = RM,
                  tabledata "Reminder Level" = RM,
                  tabledata "Reminder Line" = RM,
                  tabledata "Reminder Terms" = RM,
                  tabledata "Reminder Terms Translation" = RM,
                  tabledata "Reminder Text" = RM,
                  tabledata "Reminder Action Group" = R,
                  tabledata "Reminder Action" = R,
                  tabledata "Create Reminders Setup" = R,
                  tabledata "Issue Reminders Setup" = R,
                  tabledata "Send Reminders Setup" = R,
                  tabledata "Reminder Automation Error" = R,
                  tabledata "Reminder Action Group Log" = R,
                  tabledata "Reminder Action Log" = R,
                  tabledata "Reminder/Fin. Charge Entry" = Rm,
                  tabledata "Remit Address" = RIMD,
                  tabledata "Report Inbox" = RM,
                  tabledata "Report Layout Selection" = RM,
                  tabledata "Report Layout Update Log" = RM,
                  tabledata "Report List Translation" = RM,
                  tabledata "Report Selection Warehouse" = RM,
                  tabledata "Report Selections" = RM,
                  tabledata "Report Totals Buffer" = RM,
                  tabledata "Req. Wksh. Template" = RM,
                  tabledata "Requisition Line" = RM,
                  tabledata "Requisition Wksh. Name" = RM,
                  tabledata "Res. Availability Buffer" = RIMD,
                  tabledata "Res. Capacity Entry" = RM,
                  tabledata "Res. Gr. Availability Buffer" = RIMD,
                  tabledata "Res. Journal Batch" = RM,
                  tabledata "Res. Journal Line" = RM,
                  tabledata "Res. Journal Template" = RM,
                  tabledata "Res. Ledger Entry" = Rm,
                  tabledata "Reservation Entry" = RIMD,
                  tabledata "Reservation Entry Buffer" = RIMD,
                  tabledata Resource = RM,
#if not CLEAN25
                  tabledata "Resource Cost" = R,
#endif
                  tabledata "Resource Group" = RM,
#if not CLEAN25
                  tabledata "Resource Price" = R,
                  tabledata "Resource Price Change" = RM,
#endif
                  tabledata "Resource Register" = RM,
                  tabledata "Resource Unit of Measure" = R,
                  tabledata "Resources Setup" = RM,
                  tabledata "Responsibility Center" = RM,
                  tabledata "Restricted Record" = RIMD,
                  tabledata "Return Reason" = R,
                  tabledata "Return Receipt Header" = Rim,
                  tabledata "Return Receipt Line" = Rim,
                  tabledata "Return Shipment Header" = Rimd,
                  tabledata "Return Shipment Line" = Rimd,
                  tabledata "Returns-Related Document" = RM,
                  tabledata "Reversal Entry" = RM,
                  tabledata "Rlshp. Mgt. Comment Line" = RM,
                  tabledata "RM Matrix Management" = R,
                  tabledata "Role Center Notifications" = RIMD,
                  tabledata "Rounding Method" = RM,
                  tabledata "Rounding Residual Buffer" = Rm,
                  tabledata "Sales & Receivables Setup" = RM,
                  tabledata "Sales by Cust. Grp.Chart Setup" = RM,
                  tabledata "Sales Comment Line" = RM,
                  tabledata "Sales Comment Line Archive" = RM,
                  tabledata "Sales Cr. Memo Entity Buffer" = RIMD,
                  tabledata "Sales Cr.Memo Header" = RimD,
                  tabledata "Sales Cr.Memo Line" = Rimd,
                  tabledata "Sales Cue" = RM,
                  tabledata "Sales Cycle" = RM,
                  tabledata "Sales Cycle Stage" = RM,
                  tabledata "Sales Discount Access" = RIMD,
                  tabledata "Sales Document Icon" = Rm,
                  tabledata "Sales Header" = RIMD,
                  tabledata "Sales Header Archive" = RIMD,
                  tabledata "Sales Invoice Entity Aggregate" = RIMD,
                  tabledata "Sales Invoice Header" = RimD,
                  tabledata "Sales Invoice Line" = Rimd,
                  tabledata "Sales Invoice Line Aggregate" = RIMD,
                  tabledata "Sales Line" = RIMD,
                  tabledata "Sales Line Archive" = RIMD,
#if not CLEAN25
                  tabledata "Sales Line Discount" = RIMD,
#endif
                  tabledata "Sales Order Entity Buffer" = RIMD,
                  tabledata "Sales Planning Line" = Rimd,
                  tabledata "Sales Prepayment %" = RM,
#if not CLEAN25
                  tabledata "Sales Price" = RIMD,
#endif
                  tabledata "Sales Price Access" = RIMD,
#if not CLEAN25
                  tabledata "Sales Price and Line Disc Buff" = RM,
                  tabledata "Sales Price Worksheet" = RIMD,
#endif
                  tabledata "Sales Quote Entity Buffer" = RIMD,
                  tabledata "Sales Shipment Buffer" = RM,
                  tabledata "Sales Shipment Header" = RimD,
                  tabledata "Sales Shipment Line" = Rimd,
                  tabledata "Salesperson/Purchaser" = RM,
                  tabledata Salutation = RM,
                  tabledata "Salutation Formula" = RM,
                  tabledata "Saved Segment Criteria" = RM,
                  tabledata "Saved Segment Criteria Line" = RM,
                  tabledata "SB Owner Cue" = RM,
                  tabledata "Segment Criteria Line" = RM,
                  tabledata "Segment Header" = RM,
                  tabledata "Segment History" = RM,
                  tabledata "Segment Interaction Language" = RM,
                  tabledata "Segment Line" = RM,
                  tabledata "Segment Wizard Filter" = RM,
                  tabledata "Selected Dimension" = RM,
                  tabledata "Semi-Manual Execution Log" = RM,
                  tabledata "Semi-Manual Test Wizard" = RM,
                  tabledata "Sent Notification Entry" = RIMD,
                  tabledata "SEPA Direct Debit Mandate" = RM,
                  tabledata "Serial No. Information" = RIMD,
                  tabledata "Service Connection" = RM,
                  tabledata Session = imd,
                  tabledata "Session Event" = m,
                  tabledata "Ship-to Address" = RIMD,
                  tabledata "Shipment Method" = RM,
                  tabledata "Shipment Method Translation" = RM,
                  tabledata "Shipping Agent" = RM,
                  tabledata "Shipping Agent Services" = R,
                  tabledata "Sorting Table" = RM,
                  tabledata "Source Code" = RM,
                  tabledata "Source Code Setup" = RM,
                  tabledata "Special Equipment" = RM,
                  tabledata "Standard Address" = Rm,
                  tabledata "Standard Cost Worksheet" = RM,
                  tabledata "Standard Cost Worksheet Name" = RM,
                  tabledata "Standard Customer Sales Code" = RIMD,
                  tabledata "Standard General Journal" = RM,
                  tabledata "Standard General Journal Line" = RIMD,
                  tabledata "Standard Item Journal" = RM,
                  tabledata "Standard Item Journal Line" = RM,
                  tabledata "Standard Purchase Code" = RM,
                  tabledata "Standard Purchase Line" = RM,
                  tabledata "Standard Sales Code" = RIMD,
                  tabledata "Standard Sales Line" = RIMD,
                  tabledata "Standard Text" = RM,
                  tabledata "Standard Vendor Purchase Code" = RM,
                  tabledata "Stockkeeping Unit" = RM,
                  tabledata "Stockkeeping Unit Comment Line" = RM,
                  tabledata "Substitution Condition" = R,
                  tabledata "Support Contact Information" = R,
                  tabledata "SWIFT Code" = RM,
                  tabledata "Table Config Template" = RIMD,
                  tabledata "Table Filter" = RM,
                  tabledata "Tariff Number" = RM,
                  tabledata "Tax Area" = RM,
                  tabledata "Tax Area Buffer" = RIMD,
                  tabledata "Tax Area Line" = RM,
                  tabledata "Tax Area Translation" = RM,
                  tabledata "Tax Detail" = RIMD,
                  tabledata "Tax Group" = RM,
                  tabledata "Tax Group Buffer" = RIMD,
                  tabledata "Tax Jurisdiction" = RM,
                  tabledata "Tax Jurisdiction Translation" = RM,
                  tabledata "Tax Rate Buffer" = RIMD,
                  tabledata "Tax Setup" = RM,
                  tabledata Team = RM,
                  tabledata "Team Member Cue" = RIMD,
                  tabledata "Team Salesperson" = RM,
                  tabledata "Temp Integration Field Mapping" = RM,
                  tabledata TempStack = RM,
                  tabledata "Tenant Config. Package File" = RM,
                  tabledata "Terms And Conditions" = RIM,
                  tabledata "Terms And Conditions State" = RIM,
                  tabledata Territory = RM,
                  tabledata "Text-to-Account Mapping" = RIMD,
                  tabledata "Time Series Buffer" = R,
                  tabledata "Time Series Forecast" = R,
                  tabledata "Time Sheet Chart Setup" = RIMD,
                  tabledata "Time Sheet Cmt. Line Archive" = RIMD,
                  tabledata "Time Sheet Comment Line" = RIMD,
                  tabledata "Time Sheet Detail" = RIMD,
                  tabledata "Time Sheet Detail Archive" = RIMD,
                  tabledata "Time Sheet Header" = RIMD,
                  tabledata "Time Sheet Header Archive" = RIMD,
                  tabledata "Time Sheet Line" = RIMD,
                  tabledata "Time Sheet Line Archive" = RIMD,
                  tabledata "Time Sheet Posting Entry" = RIMD,
                  tabledata "Timeline Event" = RM,
                  tabledata "Timeline Event Change" = RM,
                  tabledata "To-do" = RM,
                  tabledata "To-do Interaction Language" = RM,
                  tabledata "Top Customers By Sales Buffer" = RIMD,
                  tabledata "Total Value Insured" = RM,
                  tabledata "Tracking Specification" = Rimd,
                  tabledata "Trailing Sales Orders Setup" = RM,
                  tabledata "Transaction Specification" = RM,
                  tabledata "Transaction Type" = R,
                  tabledata "Transfer Header" = RM,
                  tabledata "Transfer Line" = RM,
                  tabledata "Transfer Receipt Header" = RM,
                  tabledata "Transfer Receipt Line" = RM,
                  tabledata "Transfer Route" = RM,
                  tabledata "Transfer Shipment Header" = RM,
                  tabledata "Transfer Shipment Line" = RM,
                  tabledata "Transformation Rule" = RM,
                  tabledata "Transport Method" = R,
                  tabledata "Trial Balance Cache" = RM,
                  tabledata "Trial Balance Cache Info" = RM,
                  tabledata "Trial Balance Entity Buffer" = RM,
                  tabledata "Trial Balance Setup" = RM,
                  tabledata Union = RM,
                  tabledata "Unit of Measure" = RM,
                  tabledata "Unit of Measure Translation" = RM,
                  tabledata "Unlinked Attachment" = RIMD,
                  tabledata "Unplanned Demand" = RM,
                  tabledata "Untracked Planning Element" = RM,
                  tabledata "User Preference" = RIMD,
                  tabledata "User Security Status" = RM,
                  tabledata "User Setup" = RM,
                  tabledata "User Task" = RM,
                  tabledata "User Task Group" = RIMD,
                  tabledata "User Task Group Member" = RIMD,
                  tabledata "User Time Register" = RM,
                  tabledata "User Tours" = RM,
                  tabledata "Value Entry" = Rimd,
                  tabledata "Value Entry Relation" = R,
                  tabledata "VAT Amount Line" = RIMD,
                  tabledata "VAT Assisted Setup Bus. Grp." = RM,
                  tabledata "VAT Assisted Setup Templates" = RM,
                  tabledata "VAT Business Posting Group" = RM,
                  tabledata "VAT Clause" = RM,
                  tabledata "VAT Clause by Doc. Type" = RM,
                  tabledata "VAT Clause by Doc. Type Trans." = RM,
                  tabledata "VAT Clause Translation" = RM,
                  tabledata "VAT Entry" = Rimd,
                  tabledata "VAT Posting Setup" = RM,
                  tabledata "VAT Product Posting Group" = RM,
                  tabledata "VAT Rate Change Conversion" = R,
                  tabledata "VAT Rate Change Log Entry" = Ri,
                  tabledata "VAT Rate Change Setup" = R,
                  tabledata "VAT Reg. No. Srv Config" = RM,
                  tabledata "VAT Reg. No. Srv. Template" = RM,
                  tabledata "VAT Registration Log" = RM,
                  tabledata "VAT Registration Log Details" = RM,
                  tabledata "VAT Registration No. Format" = RM,
                  tabledata "VAT Report Archive" = Rm,
                  tabledata "VAT Report Error Log" = RM,
                  tabledata "VAT Report Header" = RM,
                  tabledata "VAT Report Line" = RM,
                  tabledata "VAT Report Line Relation" = RM,
                  tabledata "VAT Report Setup" = RM,
                  tabledata "VAT Reports Configuration" = RIMD,
                  tabledata "VAT Return Period" = RM,
                  tabledata "VAT Setup Posting Groups" = RM,
                  tabledata "VAT Statement Line" = RM,
                  tabledata "VAT Statement Name" = RM,
                  tabledata "VAT Statement Report Line" = RIMD,
                  tabledata "VAT Statement Template" = RM,
                  tabledata "VAT Setup" = RM,
                  tabledata "Alt. Cust. VAT Reg." = RM,
                  tabledata Vendor = RM,
                  tabledata "Vendor Amount" = RM,
                  tabledata "Vendor Bank Account" = RM,
                  tabledata "Vendor Invoice Disc." = RM,
                  tabledata "Vendor Ledger Entry" = RiMd,
                  tabledata "Vendor Posting Group" = RM,
                  tabledata "Vendor Purchase Buffer" = RIMD,
                  tabledata "Vendor Templ." = RIMD,
                  tabledata "Warehouse Activity Header" = RM,
                  tabledata "Warehouse Activity Line" = RM,
                  tabledata "Warehouse Basic Cue" = RM,
                  tabledata "Warehouse Class" = RM,
                  tabledata "Warehouse Comment Line" = RM,
                  tabledata "Warehouse Employee" = RM,
                  tabledata "Warehouse Entry" = Rm,
                  tabledata "Warehouse Journal Batch" = RM,
                  tabledata "Warehouse Journal Line" = RM,
                  tabledata "Warehouse Journal Template" = RM,
                  tabledata "Warehouse Reason Code" = RM,
                  tabledata "Warehouse Receipt Header" = RM,
                  tabledata "Warehouse Receipt Line" = RM,
                  tabledata "Warehouse Register" = RM,
                  tabledata "Warehouse Request" = RiMd,
                  tabledata "Warehouse Setup" = RM,
                  tabledata "Warehouse Shipment Header" = RM,
                  tabledata "Warehouse Shipment Line" = RM,
                  tabledata "Warehouse Source Filter" = RM,
                  tabledata "Warehouse WMS Cue" = RM,
                  tabledata "Warehouse Worker WMS Cue" = RM,
                  tabledata "Web Source" = RM,
                  tabledata "WF Event/Response Combination" = RM,
                  tabledata "Where Used Base Calendar" = RM,
                  tabledata "Whse. Cross-Dock Opportunity" = RM,
                  tabledata "Whse. Internal Pick Header" = RM,
                  tabledata "Whse. Internal Pick Line" = RM,
                  tabledata "Whse. Internal Put-away Header" = RM,
                  tabledata "Whse. Internal Put-away Line" = RM,
                  tabledata "Whse. Item Entry Relation" = R,
                  tabledata "Whse. Item Tracking Line" = Rm,
                  tabledata "Whse. Pick Request" = RM,
                  tabledata "Whse. Put-away Request" = RM,
                  tabledata "Whse. Worksheet Line" = RM,
                  tabledata "Whse. Worksheet Name" = RM,
                  tabledata "Whse. Worksheet Template" = RM,
                  tabledata "Work Center" = RM,
                  tabledata "Work Type" = R,
                  tabledata "Workflow - Record Change" = Rimd,
                  tabledata "Workflow - Table Relation" = RIMD,
                  tabledata Workflow = RIMD,
                  tabledata "Workflow Buffer" = RIMD,
                  tabledata "Workflow Category" = RIMD,
                  tabledata "Workflow Event" = RIMD,
                  tabledata "Workflow Event Queue" = RIMD,
                  tabledata "Workflow Record Change Archive" = Rimd,
                  tabledata "Workflow Response" = RIMD,
                  tabledata "Workflow Rule" = RIMD,
                  tabledata "Workflow Step" = RIMD,
                  tabledata "Workflow Step Argument" = RIMD,
                  tabledata "Workflow Step Argument Archive" = Rimd,
                  tabledata "Workflow Step Buffer" = RIMD,
                  tabledata "Workflow Step Instance" = RIMD,
                  tabledata "Workflow Step Instance Archive" = Rimd,
                  tabledata "Workflow Table Relation Value" = RIMD,
                  tabledata "Workflow User Group" = RIMD,
                  tabledata "Workflow User Group Member" = RIMD,
                  tabledata "Workflow Webhook Entry" = Rimd,
                  tabledata "Workflow Webhook Notification" = Rimd,
                  tabledata "Workflow Webhook Sub Buffer" = RIMD,
                  tabledata "Workflow Webhook Subscription" = RIMD,
                  tabledata "Workflows Entries Buffer" = Rimd,
                  tabledata "XML Buffer" = RM,
                  tabledata "XML Schema" = RM,
                  tabledata "XML Schema Element" = RM,
                  tabledata "XML Schema Restriction" = RM,
                  tabledata Zone = RM,

                  // Service
                  tabledata "Contract Change Log" = RM,
                  tabledata "Contract Gain/Loss Entry" = RM,
                  tabledata "Contract Group" = RM,
                  tabledata "Contract Trend Buffer" = RIMD,
                  tabledata "Fault Area" = RM,
                  tabledata "Fault Area/Symptom Code" = RM,
                  tabledata "Fault Code" = RM,
                  tabledata "Fault Reason Code" = RM,
                  tabledata "Fault/Resol. Cod. Relationship" = RM,
                  tabledata "Filed Contract Line" = RM,
                  tabledata Loaner = RM,
                  tabledata "Loaner Entry" = RM,
                  tabledata "Repair Status" = RM,
                  tabledata "Resolution Code" = RM,
                  tabledata "Resource Location" = RM,
                  tabledata "Resource Service Zone" = RM,
                  tabledata "Resource Skill" = RM,
                  tabledata "Service Cue" = RM,
                  tabledata "Service Item Trend Buffer" = RIMD,
                  tabledata "Service Shipment Buffer" = Rm,
                  tabledata "Skill Code" = RM,
                  tabledata "Standard Service Code" = RM,
                  tabledata "Standard Service Item Gr. Code" = RM,
                  tabledata "Standard Service Line" = RM,
                  tabledata "Symptom Code" = RM,
                  tabledata "Troubleshooting Header" = RM,
                  tabledata "Troubleshooting Line" = RM,
                  tabledata "Troubleshooting Setup" = RM,
                  tabledata "Warranty Ledger Entry" = RM,
                  tabledata "Work-Hour Template" = RM;
}
