namespace System.Security.AccessControl;

using Microsoft.AccountantPortal;
using Microsoft.Booking;
using Microsoft.Intercompany.Comment;
using Microsoft.Projects.Project.Archive;
using Microsoft.Projects.Project.Job;
using Microsoft.Inventory.Location;
using Microsoft.Projects.TimeSheet;
using Microsoft.CostAccounting.Setup;
using Microsoft.Manufacturing.Reports;
using Microsoft.Bank.Payment;
using Microsoft.Foundation.Reporting;
using Microsoft.EServices.EDocument;
using Microsoft.Foundation.Attachment;
using Microsoft.Foundation.Navigate;
using Microsoft.Finance.VAT.Reporting;
using Microsoft.Finance.VAT.Ledger;
using Microsoft.eServices.OnlineMap;
using Microsoft.Finance.Payroll;
using Microsoft.Inventory.Reconciliation;
using Microsoft.Projects.Project.Journal;
#if not CLEAN23
using Microsoft.Projects.Project.Pricing;
#endif
using Microsoft.Projects.Project.Ledger;
using Microsoft.Projects.Project.Planning;
using Microsoft.Projects.Project.Posting;
using Microsoft.Projects.Project.WIP;
using Microsoft.Projects.Project.Setup;
using System.Security.Authentication;
using System.Globalization;
using Microsoft.Foundation.AuditCodes;
using Microsoft.Foundation.Shipping;
using Microsoft.Foundation.UOM;
using Microsoft.Foundation.Task;
using Microsoft.Finance.VAT.Calculation;
using Microsoft.Finance.VAT.Setup;
using Microsoft.Finance.VAT.Clause;
using Microsoft.Finance.VAT.RateChange;
using Microsoft.Finance.VAT.Registration;
using Microsoft.Assembly.Comment;
using Microsoft.Assembly.Document;
using Microsoft.Assembly.History;
using Microsoft.Assembly.Reports;
using Microsoft.Assembly.Setup;
using Microsoft.Bank.BankAccount;
using Microsoft.Bank.Check;
using Microsoft.Bank.DirectDebit;
using Microsoft.Bank.Ledger;
using Microsoft.Bank.PositivePay;
using Microsoft.Bank.Reconciliation;
using Microsoft.Bank.Setup;
using Microsoft.Bank.Statement;
using Microsoft.CashFlow.Account;
using Microsoft.CashFlow.Comment;
using Microsoft.CashFlow.Forecast;
using Microsoft.CashFlow.Setup;
using Microsoft.CashFlow.Worksheet;
using Microsoft.Foundation.Period;
using Microsoft.RoleCenters;
using Microsoft.CostAccounting.Account;
using Microsoft.CostAccounting.Allocation;
using Microsoft.CostAccounting.Budget;
using Microsoft.CostAccounting.Journal;
using Microsoft.CostAccounting.Ledger;
using Microsoft.CRM.Analysis;
using Microsoft.CRM.BusinessRelation;
using Microsoft.CRM.Campaign;
using Microsoft.CRM.Comment;
using Microsoft.CRM.Contact;
using Microsoft.CRM.Duplicates;
using Microsoft.CRM.Interaction;
using Microsoft.CRM.Opportunity;
using Microsoft.CRM.Outlook;
using Microsoft.CRM.Profiling;
using Microsoft.CRM.RoleCenters;
using Microsoft.CRM.Segment;
using Microsoft.CRM.Setup;
using Microsoft.CRM.Task;
using Microsoft.CRM.Team;
using Microsoft.Finance.AllocationAccount;
using Microsoft.Finance.Analysis;
using Microsoft.Finance.Consolidation;
using Microsoft.Finance.Currency;
using Microsoft.Finance.Deferral;
using Microsoft.Finance.Dimension.Correction;
using Microsoft.Finance.Dimension;
using Microsoft.Finance.FinancialReports;
using Microsoft.Finance.GeneralLedger.Account;
using Microsoft.Finance.GeneralLedger.Budget;
using Microsoft.Finance.GeneralLedger.Journal;
using Microsoft.Finance.GeneralLedger.Ledger;
using Microsoft.Finance.GeneralLedger.Reports;
using Microsoft.Finance.GeneralLedger.Reversal;
using Microsoft.Finance.GeneralLedger.Setup;
using Microsoft.Finance.ReceivablesPayables;
using Microsoft.Finance.RoleCenters;
using Microsoft.Finance.SalesTax;
using Microsoft.FixedAssets.Depreciation;
using Microsoft.FixedAssets.FixedAsset;
using Microsoft.FixedAssets.Insurance;
using Microsoft.FixedAssets.Journal;
using Microsoft.FixedAssets.Ledger;
using Microsoft.FixedAssets.Maintenance;
using Microsoft.FixedAssets.Posting;
using Microsoft.FixedAssets.Setup;
using Microsoft.Foundation.Address;
using Microsoft.Foundation.Comment;
using Microsoft.Foundation.Company;
using Microsoft.Foundation.ExtendedText;
using Microsoft.Foundation.NoSeries;
using Microsoft.Foundation.PaymentTerms;
using Microsoft.HumanResources.Comment;
using Microsoft.HumanResources.Employee;
using Microsoft.HumanResources.Payables;
using Microsoft.HumanResources.Setup;
using Microsoft.Integration.D365Sales;
using Microsoft.Integration.Dataverse;
using Microsoft.Integration.Entity;
#if not CLEAN25
using Microsoft.Integration.FieldService;
#endif
using Microsoft.Integration.Graph;
using Microsoft.Integration.SyncEngine;
using Microsoft.Integration.PowerBI;
using Microsoft.Intercompany.BankAccount;
using Microsoft.Intercompany.Dimension;
using Microsoft.Intercompany.GLAccount;
using Microsoft.Intercompany.Inbox;
using Microsoft.Intercompany.Outbox;
using Microsoft.Intercompany.Partner;
using Microsoft.Intercompany.Setup;
using Microsoft.Inventory.Analysis;
using Microsoft.Inventory.Availability;
using Microsoft.Inventory.BOM.Tree;
using Microsoft.Inventory.BOM;
using Microsoft.Inventory.Comment;
using Microsoft.Inventory.Costing;
using Microsoft.Inventory.Counting.Comment;
using Microsoft.Inventory.Counting.Document;
using Microsoft.Inventory.Counting.History;
using Microsoft.Inventory.Counting.Journal;
using Microsoft.Inventory.Counting.Recording;
using Microsoft.Inventory.Counting.Tracking;
using Microsoft.Inventory.Document;
using Microsoft.Inventory.History;
using Microsoft.Inventory.Item.Attribute;
using Microsoft.Inventory.Item.Catalog;
using Microsoft.Inventory.Item.Picture;
using Microsoft.Inventory.Item.Substitution;
using Microsoft.Inventory.Item;
using Microsoft.Inventory.Journal;
using Microsoft.Inventory.Ledger;
using Microsoft.Inventory.Planning;
using Microsoft.Inventory.Requisition;
using Microsoft.Inventory.Setup;
using Microsoft.Inventory.Tracking;
using Microsoft.Inventory.Transfer;
using Microsoft.Manufacturing.Capacity;
using Microsoft.Manufacturing.Comment;
using Microsoft.Manufacturing.Document;
using Microsoft.Manufacturing.Family;
using Microsoft.Manufacturing.Forecast;
using Microsoft.Manufacturing.MachineCenter;
using Microsoft.Manufacturing.ProductionBOM;
using Microsoft.Manufacturing.RoleCenters;
using Microsoft.Manufacturing.Routing;
using Microsoft.Manufacturing.Setup;
using Microsoft.Manufacturing.StandardCost;
using Microsoft.Manufacturing.WorkCenter;
using Microsoft.Pricing.Asset;
using Microsoft.Pricing.Calculation;
using Microsoft.Pricing.PriceList;
using Microsoft.Pricing.Source;
using Microsoft.Pricing.Worksheet;
using Microsoft.Projects.Resources.Analysis;
using Microsoft.Projects.Resources.Journal;
using Microsoft.Projects.Resources.Ledger;
#if not CLEAN23
using Microsoft.Projects.Resources.Pricing;
#endif
using Microsoft.Projects.Resources.Resource;
using Microsoft.Projects.Resources.Setup;
using Microsoft.Projects.RoleCenters;
using Microsoft.Purchases.Archive;
using Microsoft.Purchases.Comment;
using Microsoft.Purchases.Document;
using Microsoft.Purchases.History;
using Microsoft.Purchases.Payables;
using Microsoft.Purchases.Pricing;
using Microsoft.Purchases.Remittance;
using Microsoft.Purchases.RoleCenters;
using Microsoft.Purchases.Setup;
using Microsoft.Purchases.Vendor;
using Microsoft.Sales.Analysis;
using Microsoft.Sales.Archive;
using Microsoft.Sales.Comment;
using Microsoft.Sales.Customer;
using Microsoft.Sales.Document;
using Microsoft.Sales.FinanceCharge;
using Microsoft.Sales.History;
using Microsoft.Sales.Pricing;
using Microsoft.Sales.Receivables;
using Microsoft.Sales.Reminder;
using Microsoft.Sales.RoleCenters;
using Microsoft.Sales.Setup;
using Microsoft.Service.Comment;
using Microsoft.Service.Contract;
using Microsoft.Service.Document;
using Microsoft.Service.Email;
using Microsoft.Service.History;
using Microsoft.Service.Item;
using Microsoft.Service.Ledger;
using Microsoft.Service.Loaner;
using Microsoft.Service.Maintenance;
using Microsoft.Service.Posting;
using Microsoft.Service.Pricing;
using Microsoft.Service.Resources;
using Microsoft.Service.RoleCenters;
using Microsoft.Service.Setup;
using Microsoft.Warehouse.Activity.History;
using Microsoft.Warehouse.Activity;
using Microsoft.Warehouse.ADCS;
using Microsoft.Warehouse.Comment;
using Microsoft.Warehouse.CrossDock;
using Microsoft.Warehouse.Document;
using Microsoft.Warehouse.History;
using Microsoft.Warehouse.InternalDocument;
using Microsoft.Warehouse.InventoryDocument;
using Microsoft.Warehouse.Journal;
using Microsoft.Warehouse.Ledger;
using Microsoft.Warehouse.Request;
using Microsoft.Warehouse.RoleCenters;
using Microsoft.Warehouse.Setup;
using Microsoft.Warehouse.Structure;
using Microsoft.Warehouse.Tracking;
using Microsoft.Warehouse.Worksheet;
using System.AI;
using System.Apps;
using System.Automation;
using System.Azure.Identity;
using System.DateTime;
using System.Device;
using System.Diagnostics;
using System.Email;
using System.Environment.Configuration;
using System.Environment;
using System.Integration.PowerBI;
using System.Integration;
using System.IO;
using System.Privacy;
using System.Reflection;
using System.Security.Encryption;
using System.Security.User;
using System.TestTools;
using System.TestTools.TestRunner;
using System.Text;
using System.Threading;
using System.Tooling;
using System.Utilities;
using System.Visualization;
using System.Xml;
using System.Upgrade;
using Microsoft.Utilities;
using Microsoft.Inventory.Intrastat;
using Microsoft.Foundation.Calendar;
using Microsoft.Foundation.BatchProcessing;
using Microsoft.HumanResources.Absence;
using Microsoft.API;
using Microsoft;

permissionset 5117 "D365 AUTOMATION"
{
    Access = Public;
    Assignable = true;
    Caption = 'Dynamics 365 Automation';

    IncludedPermissionSets = "System App - Basic",
                             "Company - Edit",
                             "Permissions & Licenses - Edit",
                             "Session - Edit",
                             LOGIN;

    Permissions = system "Tools, Security, Roles" = X,
                  codeunit * = X,
                  query * = X,
                  report * = X,
                  table * = X,
                  xmlport * = X,
                  tabledata "Add-in" = imd,
                  tabledata "Aggregate Permission Set" = Rimd,
                  tabledata "All Profile" = imd,
                  tabledata AllObj = imd,
                  tabledata AllObjWithCaption = Rimd,
                  tabledata Chart = imd,
                  tabledata "Code Coverage" = Rimd,
                  tabledata "CodeUnit Metadata" = imd,
                  tabledata "Data Sensitivity" = RIMD,
                  tabledata Date = imd,
                  tabledata "Designed Query" = R,
                  tabledata "Designed Query Caption" = R,
                  tabledata "Designed Query Category" = R,
                  tabledata "Designed Query Column" = R,
                  tabledata "Designed Query Column Filter" = R,
                  tabledata "Designed Query Data Item" = R,
                  tabledata "Designed Query Filter" = R,
                  tabledata "Designed Query Group" = RIMD,
                  tabledata "Designed Query Join" = R,
                  tabledata "Designed Query Management" = RIMD,
                  tabledata "Designed Query Obj" = Rimd,
                  tabledata "Designed Query Order By" = R,
                  tabledata "Designed Query Permission" = RIMD,
                  tabledata Device = Rimd,
                  tabledata "Document Service" = imd,
                  tabledata Drive = Rimd,
                  tabledata Entitlement = imd,
                  tabledata "Entitlement Set" = imd,
                  tabledata "Event Subscription" = Rimd,
                  tabledata "Feature Key" = R,
                  tabledata Field = Rimd,
                  tabledata File = Rimd,
                  tabledata Integer = Rimd,
                  tabledata "Intelligent Cloud" = Rimd,
                  tabledata "Intelligent Cloud Status" = Rimd,
                  tabledata Key = Rimd,
                  tabledata "License Information" = imd,
                  tabledata "License Permission" = imd,
                  tabledata Media = imd,
                  tabledata "Media Resources" = Rimd,
                  tabledata "Media Set" = imd,
                  tabledata "Membership Entitlement" = imd,
                  tabledata "NAV App Installed App" = Rimd,
                  tabledata "NAV App Setting" = RIMD,
                  tabledata "Object Access Intent Override" = Rimd,
                  tabledata "Object Metadata" = imd,
                  tabledata "Object Options" = IMD,
                  tabledata "Page Metadata" = imd,
                  tabledata Permission = imd,
                  tabledata "Permission Range" = imd,
                  tabledata "Permission Set" = imd,
                  tabledata "Profile Configuration Symbols" = imd,
                  tabledata "Published Application" = Rimd,
                  tabledata "Query Navigation" = RIMD,
                  tabledata "Report Layout" = Rimd,
                  tabledata "Report Metadata" = imd,
                  tabledata "Scheduled Task" = imd,
                  tabledata "Server Instance" = imd,
                  tabledata "SID - Account ID" = Rimd,
                  tabledata "System Object" = imd,
                  tabledata "Table Information" = Rimd,
                  tabledata "Table Metadata" = imd,
                  tabledata "Table Synch. Setup" = Rimd,
#pragma warning disable AL0432
                  tabledata "Tenant Profile" = imd,
#pragma warning restore AL0432
                  tabledata "Tenant Profile Extension" = imd,
                  tabledata "Tenant Profile Page Metadata" = imd,
                  tabledata "Tenant Profile Setting" = imd,
                  tabledata "Tenant Web Service" = RIMD,
                  tabledata "Time Zone" = imd,
                  tabledata "Upgrade Blob Storage" = Rimd,
                  tabledata User = RMD,
                  tabledata "User Property" = Rimd,
                  tabledata "Web Service" = RIMD,
                  tabledata "Windows Language" = imd,
                  tabledata "AAD Application" = RIMD,
                  tabledata "Acc. Sched. Cell Value" = RIMD,
                  tabledata "Acc. Sched. Chart Setup Line" = RIMD,
                  tabledata "Acc. Sched. KPI Buffer" = RIMD,
                  tabledata "Acc. Sched. KPI Web Srv. Line" = RIMD,
                  tabledata "Acc. Sched. KPI Web Srv. Setup" = RIMD,
                  tabledata "Acc. Schedule Line" = RIMD,
                  tabledata "Acc. Schedule Line Entity" = RIMD,
                  tabledata "Acc. Schedule Name" = RIMD,
                  tabledata "Financial Report" = RIMD,
                  tabledata "Financial Report User Filters" = RIMD,
                  tabledata "Account Schedules Chart Setup" = RIMD,
                  tabledata "Account Use Buffer" = RIMD,
                  tabledata "Accounting Period" = RIMD,
                  tabledata "Accounting Services Cue" = RIMD,
                  tabledata "Action Message Entry" = RIMD,
                  tabledata "Activities Cue" = RIMD,
                  tabledata Activity = RIMD,
                  tabledata "Activity Log" = RIMD,
                  tabledata "Activity Step" = RIMD,
                  tabledata "ADCS User" = RIMD,
                  tabledata "Additional Fee Setup" = RIMD,
                  tabledata "Adjust Exchange Rate Buffer" = RIMD,
                  tabledata "Administration Cue" = RIMD,
                  tabledata "Aged Report Entity" = RIMD,
                  tabledata "Aging Band Buffer" = RIMD,
                  tabledata "Alloc. Acc. Manual Override" = RIMD,
                  tabledata "Alloc. Account Distribution" = RIMD,
                  tabledata "Allocation Account" = RIMD,
                  tabledata "Allocation Line" = RIMD,
                  tabledata "Alt. Customer Posting Group" = RIMD,
                  tabledata "Alt. Vendor Posting Group" = RIMD,
                  tabledata "Alternative Address" = RIMD,
                  tabledata "Analysis by Dim. Parameters" = RIMD,
                  tabledata "Analysis by Dim. User Param." = RIMD,
                  tabledata "Analysis Column" = RIMD,
                  tabledata "Analysis Column Template" = RIMD,
                  tabledata "Analysis Dim. Selection Buffer" = RIMD,
                  tabledata "Analysis Field Value" = RIMD,
                  tabledata "Analysis Line" = RIMD,
                  tabledata "Analysis Line Template" = RIMD,
                  tabledata "Analysis Report Chart Line" = RIMD,
                  tabledata "Analysis Report Chart Setup" = RIMD,
                  tabledata "Analysis Report Name" = RIMD,
                  tabledata "Analysis Selected Dimension" = RIMD,
                  tabledata "Analysis Type" = RIMD,
                  tabledata "Analysis View" = RIMD,
                  tabledata "Analysis View Budget Entry" = RIMD,
                  tabledata "Analysis View Entry" = RIMD,
                  tabledata "Analysis View Filter" = RIMD,
                  tabledata "API Entities Setup" = RIMD,
                  tabledata "API Extension Upload" = rimd,
                  tabledata "Application Area Buffer" = RIMD,
                  tabledata "Application Area Setup" = RIMD,
                  tabledata "Applied Payment Entry" = RIMD,
                  tabledata "Approval Comment Line" = RIMD,
                  tabledata "Approval Entry" = Rimd,
                  tabledata "Approval Workflow Wizard" = RIMD,
                  tabledata "Approvals Activities Cue" = RIMD,
                  tabledata Area = RIMD,
                  tabledata "Assemble-to-Order Link" = RIMD,
                  tabledata "Assembly Comment Line" = RIMD,
                  tabledata "Assembly Header" = RIMD,
                  tabledata "Assembly Line" = RIMD,
                  tabledata "Assembly Setup" = RIMD,
                  tabledata "Assisted Company Setup Status" = RIMD,
                  tabledata "ATO Sales Buffer" = RIMD,
                  tabledata Attachment = RIMD,
                  tabledata "Attachment Entity Buffer" = RIMD,
                  tabledata Attendee = RIMD,
                  tabledata "Autocomplete Address" = RIMD,
                  tabledata "Availability at Date" = RIMD,
                  tabledata "Availability Calc. Overview" = RIMD,
                  tabledata "Average Cost Calc. Overview" = RIMD,
                  tabledata "Avg. Cost Adjmt. Entry Point" = RIMD,
                  tabledata "Azure AD App Setup" = RIMD,
                  tabledata "Azure AD Mgt. Setup" = RIMD,
                  tabledata "Azure AI Usage" = Rimd,
                  tabledata "Balance Sheet Buffer" = RIMD,
                  tabledata "Bank Acc. Reconciliation" = RIMD,
                  tabledata "Bank Acc. Reconciliation Line" = RIMD,
                  tabledata "Bank Acc. Rec. Match Buffer" = RIMD,
                  tabledata "Bank Account" = RIMD,
                  tabledata "Bank Account Balance Buffer" = RIMD,
                  tabledata "Bank Account Ledger Entry" = Rimd,
                  tabledata "Bank Account Posting Group" = RIMD,
                  tabledata "Bank Account Statement" = RimD,
                  tabledata "Bank Account Statement Line" = Rimd,
                  tabledata "Bank Clearing Standard" = RIMD,
                  tabledata "Bank Export/Import Setup" = RIMD,
                  tabledata "Bank Pmt. Appl. Rule" = RIMD,
                  tabledata "Bank Pmt. Appl. Settings" = RIMD,
                  tabledata "Bank Statement Matching Buffer" = RIMD,
                  tabledata "Bank Stmt Multiple Match Line" = RIMD,
                  tabledata "Bar Chart Buffer" = RIMD,
                  tabledata "Base Calendar" = RIMD,
                  tabledata "Base Calendar Change" = RIMD,
                  tabledata "Batch Processing Parameter" = Rimd,
                  tabledata "Batch Processing Session Map" = Rimd,
                  tabledata Bin = RIMD,
                  tabledata "Bin Content" = RIMD,
                  tabledata "Bin Content Buffer" = RIMD,
                  tabledata "Bin Creation Wksh. Name" = RIMD,
                  tabledata "Bin Creation Wksh. Template" = RIMD,
                  tabledata "Bin Creation Worksheet Line" = RIMD,
                  tabledata "Bin Template" = RIMD,
                  tabledata "Bin Type" = RIMD,
                  tabledata "BOM Buffer" = RIMD,
                  tabledata "BOM Component" = RIMD,
                  tabledata "BOM Warning Log" = RIMD,
                  tabledata "Booking Item" = RIMD,
                  tabledata "Booking Mailbox" = RIMD,
                  tabledata "Booking Mgr. Setup" = RIMD,
                  tabledata "Booking Service" = RIMD,
                  tabledata "Booking Service Mapping" = RIMD,
                  tabledata "Booking Staff" = RIMD,
                  tabledata "Booking Sync" = RIMD,
                  tabledata "Budget Buffer" = RIMD,
                  tabledata "Bus. Unit In Cons. Process" = RIM,
                  tabledata "Business Chart Buffer" = RIMD,
                  tabledata "Business Chart Map" = RIMD,
                  tabledata "Business Chart User Setup" = RIMD,
                  tabledata "Business Relation" = RIMD,
                  tabledata "Business Unit" = RIMD,
                  tabledata "Business Unit Information" = RIMD,
                  tabledata "Business Unit Setup" = RIMD,
                  tabledata "CAL Test Codeunit" = RIMD,
                  tabledata "CAL Test Coverage Map" = RIMD,
                  tabledata "CAL Test Enabled Codeunit" = RIMD,
                  tabledata "CAL Test Line" = RIMD,
                  tabledata "CAL Test Method" = RIMD,
                  tabledata "CAL Test Result" = RIMD,
                  tabledata "CAL Test Suite" = RIMD,
                  tabledata "Calendar Absence Entry" = RIMD,
                  tabledata "Calendar Entry" = RIMD,
#if not CLEAN24
                  tabledata "Calendar Event" = Rimd,
                  tabledata "Calendar Event User Config." = Rimd,
#endif
                  tabledata Campaign = RIMD,
                  tabledata "Campaign Entry" = RIMD,
                  tabledata "Campaign Status" = RIMD,
                  tabledata "Campaign Target Group" = RIMD,
                  tabledata "Cancelled Document" = Rimd,
                  tabledata "Capacity Constrained Resource" = RIMD,
                  tabledata "Capacity Ledger Entry" = Rimd,
                  tabledata "Capacity Unit of Measure" = RIMD,
                  tabledata "Cash Flow Account" = RIMD,
                  tabledata "Cash Flow Account Comment" = RIMD,
                  tabledata "Cash Flow Availability Buffer" = RIMD,
                  tabledata "Cash Flow Azure AI Buffer" = Rimd,
                  tabledata "Cash Flow Chart Setup" = RIMD,
                  tabledata "Cash Flow Forecast" = RIMD,
                  tabledata "Cash Flow Forecast Entry" = RIMD,
                  tabledata "Cash Flow Manual Expense" = RIMD,
                  tabledata "Cash Flow Manual Revenue" = RIMD,
                  tabledata "Cash Flow Report Selection" = RIMD,
                  tabledata "Cash Flow Setup" = RIMD,
                  tabledata "Cash Flow Worksheet Line" = RIMD,
                  tabledata "Cause of Absence" = RIMD,
                  tabledata "Cause of Inactivity" = RIMD,
                  tabledata "CDS Available Virtual Table" = RIMD,
                  tabledata "CDS BC Table Relation" = RIMD,
                  tabledata "CDS Company" = RIMD,
                  tabledata "CDS Connection Setup" = RIMD,
                  tabledata "CDS Coupled Business Unit" = RIMD,
                  tabledata "CDS Environment" = RIMD,
#if not CLEAN22
                  tabledata "CDS Failed Option Mapping" = RIMD,
#endif
                  tabledata "CDS Solution" = RIMD,
                  tabledata "CDS Teammembership" = RIMD,
                  tabledata "CDS Teamroles" = RIMD,
                  tabledata "Certificate of Supply" = RIMD,
                  tabledata "Change Global Dim. Header" = RIMD,
                  tabledata "Change Global Dim. Log Entry" = RIMD,
                  tabledata "Change Log Entry" = Rimd,
                  tabledata "Change Log Setup (Field)" = RIMD,
                  tabledata "Change Log Setup (Table)" = RIMD,
                  tabledata "Change Log Setup" = RIMD,
                  tabledata "Chart Definition" = RIMD,
                  tabledata "Check Ledger Entry" = RIMD,
                  tabledata "Close Income Statement Buffer" = RIMD,
                  tabledata "Close Opportunity Code" = RIMD,
                  tabledata "Column Layout" = RIMD,
                  tabledata "Column Layout Name" = RIMD,
                  tabledata "Comment Line" = RIMD,
                  tabledata "Comment Line Archive" = RIMD,
                  tabledata "Communication Method" = RIMD,
                  tabledata "Company Information" = RIMD,
                  tabledata "Company Size" = RIMD,
                  tabledata Confidential = RIMD,
                  tabledata "Confidential Information" = RIMD,
                  tabledata "Config. Field Map" = RIMD,
                  tabledata "Config. Line" = RIMD,
                  tabledata "Config. Media Buffer" = RIMD,
                  tabledata "Config. Package" = RIMD,
                  tabledata "Config. Package Data" = RIMD,
                  tabledata "Config. Package Error" = RIMD,
                  tabledata "Config. Package Field" = RIMD,
                  tabledata "Config. Package Filter" = RIMD,
                  tabledata "Config. Package Record" = RIMD,
                  tabledata "Config. Package Table" = RIMD,
                  tabledata "Config. Question" = RIMD,
                  tabledata "Config. Question Area" = RIMD,
                  tabledata "Config. Questionnaire" = RIMD,
                  tabledata "Config. Record For Processing" = RIMD,
                  tabledata "Config. Related Field" = RIMD,
                  tabledata "Config. Related Table" = RIMD,
                  tabledata "Config. Selection" = RIMD,
                  tabledata "Config. Setup" = RIMD,
                  tabledata "Config. Table Processing Rule" = RIMD,
                  tabledata "Config. Template Header" = RIMD,
                  tabledata "Config. Template Line" = RIMD,
                  tabledata "Config. Tmpl. Selection Rules" = RIMD,
                  tabledata "Consolidation Account" = RIMD,
                  tabledata "Consolidation Process" = RIM,
                  tabledata "Consolidation Setup" = RIM,
                  tabledata "Cont. Duplicate Search String" = RIMD,
                  tabledata Contact = RIMD,
                  tabledata "Contact Alt. Addr. Date Range" = RIMD,
                  tabledata "Contact Alt. Address" = RIMD,
                  tabledata "Contact Business Relation" = RIMD,
                  tabledata "Contact Dupl. Details Buffer" = RIMD,
                  tabledata "Contact Duplicate" = RIMD,
                  tabledata "Contact Industry Group" = RIMD,
                  tabledata "Contact Job Responsibility" = RIMD,
                  tabledata "Contact Mailing Group" = RIMD,
                  tabledata "Contact Profile Answer" = RIMD,
                  tabledata "Contact Value" = RIMD,
                  tabledata "Contact Web Source" = RIMD,
                  tabledata "Contract Change Log" = RIMD,
                  tabledata "Contract Gain/Loss Entry" = RIMD,
                  tabledata "Contract Group" = RIMD,
                  tabledata "Contract Trend Buffer" = RIMD,
                  tabledata "Contract/Service Discount" = RIMD,
                  tabledata "Copy Gen. Journal Parameters" = RIMD,
                  tabledata "Copy Item Buffer" = RIMD,
                  tabledata "Copy Item Parameters" = RIMD,
                  tabledata "Cost Accounting Setup" = RIMD,
                  tabledata "Cost Allocation Source" = RIMD,
                  tabledata "Cost Allocation Target" = RIMD,
                  tabledata "Cost Budget Buffer" = Rimd,
                  tabledata "Cost Budget Entry" = RIMD,
                  tabledata "Cost Budget Name" = RIMD,
                  tabledata "Cost Budget Register" = RIMD,
                  tabledata "Cost Center" = RIMD,
                  tabledata "Cost Element Buffer" = RIMD,
                  tabledata "Cost Entry" = RIMD,
                  tabledata "Cost Journal Batch" = RIMD,
                  tabledata "Cost Journal Line" = RIMD,
                  tabledata "Cost Journal Template" = RIMD,
                  tabledata "Cost Object" = RIMD,
                  tabledata "Cost Register" = RIMD,
                  tabledata "Cost Share Buffer" = RIMD,
                  tabledata "Cost Type" = RIMD,
                  tabledata "Country/Region" = RIMD,
                  tabledata "Country/Region Translation" = RIMD,
#if not CLEAN22                  
                  tabledata "Coupling Field Buffer" = RIMD,
#endif
                  tabledata "Coupling Record Buffer" = RIMD,
                  tabledata "Credit Trans Re-export History" = RIMD,
                  tabledata "Credit Transfer Entry" = RIMD,
                  tabledata "Credit Transfer Register" = RIMD,
                  tabledata "Dataverse Entity Change" = RID,
                  tabledata "CRM Account" = RIMD,
                  tabledata "CRM Account Statistics" = RIMD,
                  tabledata "CRM Annotation" = RIMD,
                  tabledata "CRM Annotation Buffer" = RIMD,
                  tabledata "CRM Annotation Coupling" = RIMD,
                  tabledata "CRM Appmodule" = RIMD,
                  tabledata "CRM BC Virtual Table Config." = RIMD,
                  tabledata "CRM Businessunit" = RIMD,
                  tabledata "CRM Company" = RIMD,
                  tabledata "CRM Connection Setup" = RIMD,
                  tabledata "CRM Contact" = RIMD,
                  tabledata "CRM Contract" = RIMD,
                  tabledata "CRM Customeraddress" = RIMD,
                  tabledata "CRM Discount" = RIMD,
                  tabledata "CRM Discounttype" = RIMD,
                  tabledata "CRM Freight Terms" = R,
                  tabledata "CRM Full Synch. Review Line" = RIMD,
                  tabledata "CRM Incident" = RIMD,
                  tabledata "CRM Incidentresolution" = RIMD,
                  tabledata "CRM Integration Record" = RIMD,
                  tabledata "CRM Invoice" = RIMD,
                  tabledata "CRM Invoicedetail" = RIMD,
                  tabledata "CRM NAV Connection" = RIMD,
                  tabledata "CRM Opportunity" = RIMD,
                  tabledata "CRM Option Mapping" = RIMD,
                  tabledata "CRM Organization" = RIMD,
                  tabledata "CRM Payment Terms" = R,
                  tabledata "CRM Post" = RIMD,
                  tabledata "CRM Post Buffer" = RIMD,
                  tabledata "CRM Post Configuration" = RIMD,
                  tabledata "CRM Pricelevel" = RIMD,
                  tabledata "CRM Product" = RIMD,
                  tabledata "CRM Productpricelevel" = RIMD,
                  tabledata "CRM Quote" = RIMD,
                  tabledata "CRM Quotedetail" = RIMD,
                  tabledata "CRM Redirect" = RIMD,
                  tabledata "CRM Role" = RIMD,
                  tabledata "CRM Salesorder" = RIMD,
                  tabledata "CRM Salesorderdetail" = RIMD,
                  tabledata "CRM Shipping Method" = R,
                  tabledata "CRM Synch Status" = RIMD,
                  tabledata "CRM Synch. Conflict Buffer" = RIMD,
                  tabledata "CRM Synch. Job Status Cue" = RIMD,
                  tabledata "CRM Systemuser" = RIMD,
                  tabledata "CRM Systemuserroles" = RIMD,
                  tabledata "CDS Field Security Profile" = RIMD,
                  tabledata "CDS System User Profiles" = RIMD,
                  tabledata "CRM Team" = RIMD,
                  tabledata "CRM Transactioncurrency" = RIMD,
                  tabledata "CRM Uom" = RIMD,
                  tabledata "CRM Uomschedule" = RIMD,
#if not CLEAN25
                  tabledata "FS Connection Setup" = RIMD,
                  tabledata "FS Bookable Resource" = RIMD,
                  tabledata "FS Bookable Resource Booking" = RIMD,
                  tabledata "FS BookableResourceBookingHdr" = RIMD,
                  tabledata "FS Customer Asset" = RIMD,
                  tabledata "FS Customer Asset Category" = RIMD,
                  tabledata "FS Project Task" = RIMD,
                  tabledata "FS Resource Pay Type" = RIMD,
                  tabledata "FS Work Order" = RIMD,
                  tabledata "FS Work Order Incident" = RIMD,
                  tabledata "FS Work Order Product" = RIMD,
                  tabledata "FS Work Order Service" = RIMD,
                  tabledata "FS Work Order Substatus" = RIMD,
                  tabledata "FS Work Order Type" = RIMD,
#endif
                  tabledata "CSV Buffer" = RIMD,
                  tabledata "Curr. Exch. Rate Update Setup" = RIMD,
                  tabledata Currency = RIMD,
                  tabledata "Currency Amount" = RIMD,
                  tabledata "Currency Exchange Rate" = RIMD,
                  tabledata "Currency for Fin. Charge Terms" = RIMD,
                  tabledata "Currency for Reminder Level" = RIMD,
                  tabledata "Currency Total Buffer" = RIMD,
                  tabledata "Current Salesperson" = RIMD,
                  tabledata "Cust. Invoice Disc." = RIMD,
                  tabledata "Cust. Ledger Entry" = RiMd,
                  tabledata "Custom Address Format" = RIMD,
                  tabledata "Custom Address Format Line" = RIMD,
                  tabledata "Custom Report Layout" = RIMD,
                  tabledata "Custom Report Selection" = RIMD,
                  tabledata Customer = RIMD,
                  tabledata "Customer Amount" = RIMD,
                  tabledata "Customer Bank Account" = RIMD,
                  tabledata "Customer Discount Group" = RIMD,
                  tabledata "Customer Posting Group" = RIMD,
                  tabledata "Customer Price Group" = RIMD,
                  tabledata "Customer Sales Buffer" = RIMD,
                  tabledata "Customer Templ." = RIMD,
                  tabledata "Customized Calendar Change" = RIMD,
                  tabledata "Customized Calendar Entry" = RIMD,
                  tabledata "CV Ledger Entry Buffer" = RIMD,
                  tabledata "Data Exch." = RIMD,
                  tabledata "Data Exch. Column Def" = RIMD,
                  tabledata "Data Exch. Def" = RIMD,
                  tabledata "Data Exch. Field" = RIMD,
                  tabledata "Data Exch. Field Mapping" = RIMD,
                  tabledata "Data Exch. Field Mapping Buf." = RIMD,
                  tabledata "Data Exch. Line Def" = RIMD,
                  tabledata "Data Exch. Mapping" = RIMD,
                  tabledata "Data Exch. Field Grouping" = RIMD,
                  tabledata "Data Exch. FlowField Gr. Buff." = RIMD,
                  tabledata "Data Exchange Type" = RIMD,
                  tabledata "Data Exch. Table Filter" = RIMD,
                  tabledata "Data Migration Entity" = RIMD,
                  tabledata "Data Migration Error" = RIMD,
                  tabledata "Data Migration Parameters" = RIMD,
                  tabledata "Data Migration Setup" = RIMD,
                  tabledata "Data Migration Status" = RIMD,
                  tabledata "Data Migrator Registration" = RIMD,
                  tabledata "Data Privacy Records" = RIMD,
                  tabledata "DataExch-RapidStart Buffer" = RIMD,
                  tabledata "Date Compr. Register" = Rimd,
                  tabledata "Date Lookup Buffer" = RIMD,
                  tabledata "Default Dimension" = RIMD,
                  tabledata "Default Dimension Priority" = RIMD,
                  tabledata "Deferral Header" = RIMD,
                  tabledata "Deferral Header Archive" = RIMD,
                  tabledata "Deferral Line" = RIMD,
                  tabledata "Deferral Line Archive" = RIMD,
                  tabledata "Deferral Posting Buffer" = RIMD,
                  tabledata "Deferral Template" = RIMD,
                  tabledata "Delivery Sorter" = RIMD,
                  tabledata "Depreciation Book" = RIMD,
                  tabledata "Depreciation Table Buffer" = RIMD,
                  tabledata "Depreciation Table Header" = RIMD,
                  tabledata "Depreciation Table Line" = RIMD,
                  tabledata "Detailed Cust. Ledg. Entry" = Rimd,
                  tabledata "Detailed CV Ledg. Entry Buffer" = RIMD,
                  tabledata "Detailed Employee Ledger Entry" = Rimd,
                  tabledata "Detailed Vendor Ledg. Entry" = Rimd,
                  tabledata "Dim Correct Selection Criteria" = R,
                  tabledata "Dim Correction Blocked Setup" = R,
                  tabledata "Dim Correction Change" = R,
                  tabledata "Dim Correction Set Buffer" = R,
                  tabledata "Dim Correction Entry Log" = R,
                  tabledata "Dim. Value per Account" = RIMD,
                  tabledata Dimension = RIMD,
                  tabledata "Dimension Buffer" = RIMD,
                  tabledata "Dimension Code Amount Buffer" = RIMD,
                  tabledata "Dimension Code Buffer" = RIMD,
                  tabledata "Dimension Combination" = RIMD,
                  tabledata "Dimension Correction" = R,
                  tabledata "Dimension Entry Buffer" = RIMD,
                  tabledata "Dimension ID Buffer" = RIMD,
                  tabledata "Dimension Selection Buffer" = RIMD,
                  tabledata "Dimension Set Entry" = Rimd,
                  tabledata "Dimension Set Entry Buffer" = RIMD,
                  tabledata "Dimension Set ID Filter Line" = RIMD,
                  tabledata "Dimension Set Tree Node" = Rimd,
                  tabledata "Dimension Translation" = RIMD,
                  tabledata "Dimension Value" = RIMD,
                  tabledata "Dimension Value Combination" = RIMD,
                  tabledata "Dimensions Field Map" = RIMD,
                  tabledata "Dimensions Template" = RIMD,
                  tabledata "Direct Debit Collection" = RIMD,
                  tabledata "Direct Debit Collection Entry" = RIMD,
                  tabledata "Doc. Exch. Service Setup" = RIMD,
                  tabledata "Document Attachment" = RIMD,
                  tabledata "Document Entry" = RIMD,
                  tabledata "Document Search Result" = RIMD,
                  tabledata "Document Sending Profile" = RIMD,
#if not CLEAN23
                  tabledata "Document Service Cache" = Rimd,
#endif
                  tabledata "Drop Shpt. Post. Buffer" = RIMD,
                  tabledata "Dtld. Price Calculation Setup" = RIMD,
                  tabledata "Duplicate Price Line" = RIMD,
                  tabledata "Duplicate Search String Setup" = RIMD,
                  tabledata "Dynamic Request Page Entity" = RIMD,
                  tabledata "Dynamic Request Page Field" = RIMD,
                  tabledata "ECSL VAT Report Line" = RIMD,
                  tabledata "ECSL VAT Report Line Relation" = RIMD,
                  tabledata "Electronic Document Format" = RIMD,
                  tabledata "Email Item" = RIMD,
                  tabledata "Email Parameter" = RIMD,
                  tabledata Employee = RIMD,
                  tabledata "Employee Absence" = RIMD,
                  tabledata "Employee Ledger Entry" = Rimd,
                  tabledata "Employee Payment Buffer" = RIMD,
                  tabledata "Employee Posting Group" = RIMD,
                  tabledata "Employee Qualification" = RIMD,
                  tabledata "Employee Relative" = RIMD,
                  tabledata "Employee Statistics Group" = RIMD,
                  tabledata "Employee Templ." = RIMD,
                  tabledata "Employee Time Reg Buffer" = RIMD,
                  tabledata "Employment Contract" = RIMD,
                  tabledata "Entry No. Amount Buffer" = RIMD,
                  tabledata "Entry Summary" = RIMD,
                  tabledata "Entry/Exit Point" = RIMD,
                  tabledata "Error Buffer" = RIMD,
                  tabledata "Error Handling Parameters" = RIMD,
                  tabledata "Error Message" = RIMD,
                  tabledata "Error Message Register" = RIMD,
                  tabledata "Excel Buffer" = RIMD,
                  tabledata "Excel Template Storage" = RIMD,
                  tabledata "Exch. Rate Adjmt. Reg." = Rimd,
                  tabledata "Exch. Rate Adjmt. Ledg. Entry" = Rimd,
                  tabledata "Exchange Contact" = RIMD,
                  tabledata "Exchange Folder" = RIMD,
                  tabledata "Exchange Object" = RIMD,
                  tabledata "Exchange Service Setup" = RIMD,
                  tabledata "Exchange Sync" = RIMD,
#if not CLEAN24
                  tabledata "Exp. Phys. Invt. Tracking" = RIMD,
#endif
                  tabledata "Exp. Invt. Order Tracking" = RIMD,
                  tabledata "Experience Tier Buffer" = RIMD,
                  tabledata "Experience Tier Setup" = RIMD,
                  tabledata "Extended Text Header" = RIMD,
                  tabledata "Extended Text Line" = RIMD,
                  tabledata "FA Allocation" = RIMD,
                  tabledata "FA Buffer Projection" = RIMD,
                  tabledata "FA Class" = RIMD,
                  tabledata "FA Date Type" = RIMD,
                  tabledata "FA Depreciation Book" = RIMD,
                  tabledata "FA G/L Posting Buffer" = RIMD,
                  tabledata "FA Journal Batch" = RIMD,
                  tabledata "FA Journal Line" = RIMD,
                  tabledata "FA Journal Setup" = RIMD,
                  tabledata "FA Journal Template" = RIMD,
                  tabledata "FA Ledger Entry" = Rimd,
                  tabledata "FA Location" = RIMD,
                  tabledata "FA Matrix Posting Type" = RIMD,
                  tabledata "FA Posting Group" = RIMD,
                  tabledata "FA Posting Group Buffer" = RIMD,
                  tabledata "FA Posting Type" = RIMD,
                  tabledata "FA Posting Type Setup" = RIMD,
                  tabledata "FA Reclass. Journal Batch" = RIMD,
                  tabledata "FA Reclass. Journal Line" = RIMD,
                  tabledata "FA Reclass. Journal Template" = RIMD,
                  tabledata "FA Register" = Rimd,
                  tabledata "FA Setup" = RIMD,
                  tabledata "FA Subclass" = RIMD,
                  tabledata Family = RIMD,
                  tabledata "Family Line" = RIMD,
                  tabledata "Fault Area" = RIMD,
                  tabledata "Fault Area/Symptom Code" = RIMD,
                  tabledata "Fault Code" = RIMD,
                  tabledata "Fault Reason Code" = RIMD,
                  tabledata "Fault/Resol. Cod. Relationship" = RIMD,
                  tabledata "Field Buffer" = RIMD,
                  tabledata "Field Monitoring Setup" = Rm,
                  tabledata "Filed Contract Line" = RIMD,
                  tabledata "Filed Service Contract Header" = RIMD,
                  tabledata "Filter Item Attributes Buffer" = RIMD,
                  tabledata "Fin. Charge Comment Line" = RIMD,
                  tabledata "Finance Charge Interest Rate" = RIMD,
                  tabledata "Finance Charge Memo Header" = RIMD,
                  tabledata "Finance Charge Memo Line" = RIMD,
                  tabledata "Finance Charge Terms" = RIMD,
                  tabledata "Finance Charge Text" = RIMD,
                  tabledata "Finance Cue" = RIMD,
                  tabledata "Fixed Asset" = RIMD,
                  tabledata "Flow Service Configuration" = Rimd,
                  tabledata "Flow User Environment Buffer" = RIMD,
                  tabledata "Flow User Environment Config" = RIMD,
                  tabledata "G/L - Item Ledger Relation" = RIMD,
                  tabledata "G/L Acc. Balance Buffer" = RIMD,
                  tabledata "G/L Acc. Balance/Budget Buffer" = RIMD,
                  tabledata "G/L Acc. Budget Buffer" = RIMD,
                  tabledata "G/L Account (Analysis View)" = RIMD,
                  tabledata "G/L Account" = RIMD,
                  tabledata "G/L Account Category" = RIMD,
                  tabledata "G/L Account Net Change" = RIMD,
                  tabledata "G/L Account Where-Used" = RIMD,
                  tabledata "G/L Budget Entry" = RIMD,
                  tabledata "G/L Budget Name" = RIMD,
                  tabledata "G/L Entry - VAT Entry Link" = Rimd,
                  tabledata "G/L Entry" = Rimd,
                  tabledata "G/L Register" = Rimd,
                  tabledata "Gen. Business Posting Group" = RIMD,
                  tabledata "Gen. Jnl. Allocation" = RIMD,
                  tabledata "Gen. Jnl. Dim. Filter" = RIMD,
                  tabledata "Gen. Journal Batch" = RIMD,
                  tabledata "Gen. Journal Line" = RIMD,
                  tabledata "Gen. Journal Template" = RIMD,
                  tabledata "Gen. Product Posting Group" = RIMD,
                  tabledata "General Ledger Setup" = RIMD,
                  tabledata "General Posting Setup" = RIMD,
                  tabledata "Generic Chart Captions Buffer" = RIMD,
                  tabledata "Generic Chart Filter" = RIMD,
                  tabledata "Generic Chart Memo Buffer" = RIMD,
                  tabledata "Generic Chart Query Column" = RIMD,
                  tabledata "Generic Chart Setup" = RIMD,
                  tabledata "Generic Chart Y-Axis" = RIMD,
                  tabledata Geolocation = RIMD,
                  tabledata "Grounds for Termination" = RIMD,
                  tabledata "Handled IC Inbox Jnl. Line" = RIMD,
                  tabledata "Handled IC Inbox Purch. Header" = RIMD,
                  tabledata "Handled IC Inbox Purch. Line" = RIMD,
                  tabledata "Handled IC Inbox Sales Header" = RIMD,
                  tabledata "Handled IC Inbox Sales Line" = RIMD,
                  tabledata "Handled IC Inbox Trans." = RIMD,
                  tabledata "Handled IC Outbox Jnl. Line" = RIMD,
                  tabledata "Handled IC Outbox Purch. Hdr" = RIMD,
                  tabledata "Handled IC Outbox Purch. Line" = RIMD,
                  tabledata "Handled IC Outbox Sales Header" = RIMD,
                  tabledata "Handled IC Outbox Sales Line" = RIMD,
                  tabledata "Handled IC Outbox Trans." = RIMD,
                  tabledata "HR Confidential Comment Line" = RIMD,
                  tabledata "Human Resource Comment Line" = RIMD,
                  tabledata "Human Resource Unit of Measure" = RIMD,
                  tabledata "Human Resources Setup" = RIMD,
                  tabledata "Hybrid Deployment Setup" = RIMD,
                  tabledata "IC Bank Account" = RIMD,
                  tabledata "IC Comment Line" = RIMD,
                  tabledata "IC Dimension" = RIMD,
                  tabledata "IC Dimension Value" = RIMD,
                  tabledata "IC Document Dimension" = RIMD,
                  tabledata "IC G/L Account" = RIMD,
                  tabledata "IC Inbox Jnl. Line" = RIMD,
                  tabledata "IC Inbox Purchase Header" = RIMD,
                  tabledata "IC Inbox Purchase Line" = RIMD,
                  tabledata "IC Inbox Sales Header" = RIMD,
                  tabledata "IC Inbox Sales Line" = RIMD,
                  tabledata "IC Inbox Transaction" = RIMD,
                  tabledata "IC Inbox/Outbox Jnl. Line Dim." = RIMD,
                  tabledata "IC Outbox Jnl. Line" = RIMD,
                  tabledata "IC Outbox Purchase Header" = RIMD,
                  tabledata "IC Outbox Purchase Line" = RIMD,
                  tabledata "IC Outbox Sales Header" = RIMD,
                  tabledata "IC Outbox Sales Line" = RIMD,
                  tabledata "IC Outbox Transaction" = RIMD,
                  tabledata "IC Partner" = RIMD,
                  tabledata "IC Setup" = RIMD,
                  tabledata "Image Analysis Setup" = RIMD,
                  tabledata "Image Analysis Scenario" = R,
                  tabledata "Import G/L Transaction" = RIMD,
                  tabledata "Incoming Document" = RIMD,
                  tabledata "Incoming Document Approver" = RIMD,
                  tabledata "Incoming Document Attachment" = RIMD,
                  tabledata "Incoming Documents Setup" = RIMD,
                  tabledata "Industry Group" = RIMD,
                  tabledata "Ins. Coverage Ledger Entry" = Rimd,
                  tabledata Insurance = RIMD,
                  tabledata "Insurance Journal Batch" = RIMD,
                  tabledata "Insurance Journal Line" = RIMD,
                  tabledata "Insurance Journal Template" = RIMD,
                  tabledata "Insurance Register" = Rimd,
                  tabledata "Insurance Type" = RIMD,
                  tabledata "Integration Field Mapping" = RIMD,
                  tabledata "Integration Synch. Job" = RIMD,
                  tabledata "Integration Synch. Job Errors" = RIMD,
                  tabledata "Integration Table Mapping" = RIMD,
                  tabledata "Inter. Log Entry Comment Line" = RIMD,
                  tabledata "Interaction Merge Data" = R,
                  tabledata "Interaction Group" = RIMD,
                  tabledata "Interaction Log Entry" = RIMD,
                  tabledata "Interaction Template" = RIMD,
                  tabledata "Interaction Template Setup" = RIMD,
                  tabledata "Interaction Tmpl. Language" = RIMD,
                  tabledata "Intermediate Data Import" = RIMD,
                  tabledata "Internal Movement Header" = RIMD,
                  tabledata "Internal Movement Line" = RIMD,
#if not CLEAN22
                  tabledata "Advanced Intrastat Checklist" = RIMD,
                  tabledata "Intrastat Jnl. Batch" = RIMD,
                  tabledata "Intrastat Jnl. Line" = RIMD,
                  tabledata "Intrastat Jnl. Template" = RIMD,
                  tabledata "Intrastat Setup" = RIMD,
#endif
                  tabledata "Invalidated Dim Correction" = R,
                  tabledata "Inventory Adjmt. Entry (Order)" = Rimd,
                  tabledata "Inventory Adjustment Buffer" = Rimd,
                  tabledata "Inventory Buffer" = RIMD,
                  tabledata "Inventory Comment Line" = RIMD,
                  tabledata "Inventory Event Buffer" = RIMD,
                  tabledata "Inventory Page Data" = RIMD,
                  tabledata "Inventory Period" = RIMD,
                  tabledata "Inventory Period Entry" = RIMD,
                  tabledata "Inventory Posting Group" = RIMD,
                  tabledata "Inventory Posting Setup" = RIMD,
                  tabledata "Inventory Profile" = Rimd,
                  tabledata "Inventory Profile Track Buffer" = RIMD,
                  tabledata "Inventory Report Entry" = RIMD,
                  tabledata "Inventory Report Header" = RIMD,
                  tabledata "Inventory Setup" = RIMD,
#if not CLEAN23
                  tabledata "Invoice Post. Buffer" = RIMD,
#endif
                  tabledata "Invoice Posting Buffer" = RIMD,
                  tabledata "Invoiced Booking Item" = RIMD,
                  tabledata "Invt. Document Header" = RIMD,
                  tabledata "Invt. Document Line" = RIMD,
                  tabledata "Invt. Post to G/L Test Buffer" = RIMD,
                  tabledata "Invt. Posting Buffer" = RIMD,
                  tabledata "Invt. Receipt Header" = Rimd,
                  tabledata "Invt. Receipt Line" = Rimd,
                  tabledata "Invt. Shipment Header" = Rimd,
                  tabledata "Invt. Shipment Line" = Rimd,
                  tabledata "Isolated Certificate" = RIMD,
                  tabledata "Issued Fin. Charge Memo Header" = RimD,
                  tabledata "Issued Fin. Charge Memo Line" = Rimd,
                  tabledata "Issued Reminder Header" = RimD,
                  tabledata "Issued Reminder Line" = Rimd,
                  tabledata Item = RIMD,
                  tabledata "Item Amount" = RIMD,
                  tabledata "Item Analysis View" = RIMD,
                  tabledata "Item Analysis View Budg. Entry" = RIMD,
                  tabledata "Item Analysis View Entry" = RIMD,
                  tabledata "Item Analysis View Filter" = RIMD,
                  tabledata "Item Application Entry" = RImd,
                  tabledata "Item Application Entry History" = RIMD,
                  tabledata "Item Attr. Value Translation" = RIMD,
                  tabledata "Item Attribute" = RIMD,
                  tabledata "Item Attribute Translation" = RIMD,
                  tabledata "Item Attribute Value" = RIMD,
                  tabledata "Item Attribute Value Mapping" = RIMD,
                  tabledata "Item Attribute Value Selection" = RIMD,
                  tabledata "Item Availability Buffer" = RIMD,
                  tabledata "Item Availability by Date" = RIMD,
                  tabledata "Item Availability Line" = RIMD,
                  tabledata "Item Budget Buffer" = RIMD,
                  tabledata "Item Budget Entry" = RIMD,
                  tabledata "Item Budget Name" = RIMD,
                  tabledata "Item Category" = RIMD,
                  tabledata "Item Charge" = RIMD,
                  tabledata "Item Charge Assignment (Purch)" = RIMD,
                  tabledata "Item Charge Assignment (Sales)" = RIMD,
                  tabledata "Item Discount Group" = RIMD,
                  tabledata "Item Entry Relation" = RIMD,
                  tabledata "Item Identifier" = RIMD,
                  tabledata "Item Journal Batch" = RIMD,
                  tabledata "Item Journal Buffer" = RIMD,
                  tabledata "Item Journal Line" = RIMD,
                  tabledata "Item Journal Template" = RIMD,
                  tabledata "Item Ledger Entry" = Rimd,
                  tabledata "Item Picture Buffer" = RIMD,
                  tabledata "Item Reference" = RIMD,
                  tabledata "Item Register" = Rimd,
                  tabledata "Item Statistics Buffer" = RIMD,
                  tabledata "Item Substitution" = RIMD,
                  tabledata "Item Templ." = RIMD,
                  tabledata "Item Tracing Buffer" = Rimd,
                  tabledata "Item Tracing History Buffer" = Rimd,
                  tabledata "Item Tracking Code" = RIMD,
                  tabledata "Item Tracking Comment" = RIMD,
                  tabledata "Item Tracking Setup" = RIMD,
                  tabledata "Item Translation" = RIMD,
                  tabledata "Item Turnover Buffer" = RIMD,
                  tabledata "Item Unit of Measure" = RIMD,
                  tabledata "Item Variant" = RIMD,
                  tabledata "Item Vendor" = RIMD,
                  tabledata Job = RIMD,
                  tabledata "Job Archive" = RIMD,
                  tabledata "Job Buffer" = Rimd,
                  tabledata "Job Cue" = RIMD,
                  tabledata "Job Difference Buffer" = Rimd,
                  tabledata "Job Entry No." = RIMD,
#if not CLEAN23
                  tabledata "Job G/L Account Price" = RIMD,
                  tabledata "Job Item Price" = RIMD,
#endif
                  tabledata "Job Journal Batch" = RIMD,
                  tabledata "Job Journal Line" = RIMD,
                  tabledata "Job Journal Quantity" = RIMD,
                  tabledata "Job Journal Template" = RIMD,
                  tabledata "Job Ledger Entry" = Rimd,
                  tabledata "Job Planning Line - Calendar" = RIMD,
                  tabledata "Job Planning Line" = RIMD,
                  tabledata "Job Planning Line Archive" = RIMD,
                  tabledata "Job Planning Line Invoice" = RIMD,
                  tabledata "Job Posting Buffer" = RIMD,
                  tabledata "Job Posting Group" = RIMD,
                  tabledata "Job Queue Category" = RIMD,
                  tabledata "Job Queue Entry" = RIMD,
                  tabledata "Job Queue Entry Buffer" = RIMD,
                  tabledata "Job Queue Log Entry" = RIMD,
                  tabledata "Job Register" = Rimd,
#if not CLEAN23
                  tabledata "Job Resource Price" = RIMD,
#endif
                  tabledata "Job Responsibility" = RIMD,
                  tabledata "Job Task" = RIMD,
                  tabledata "Job Task Archive" = RIMD,
                  tabledata "Job Task Dimension" = RIMD,
                  tabledata "Job Usage Link" = RIMD,
                  tabledata "Job WIP Buffer" = Rimd,
                  tabledata "Job WIP Entry" = RIMD,
                  tabledata "Job WIP G/L Entry" = Rimd,
                  tabledata "Job WIP Method" = RIMD,
                  tabledata "Job WIP Total" = RIMD,
                  tabledata "Job WIP Warning" = RIMD,
                  tabledata "Jobs Setup" = RIMD,
                  tabledata "Journal User Preferences" = RIMD,
                  tabledata "JSON Buffer" = RIMD,
                  tabledata "Last Used Chart" = RIMD,
                  tabledata "Ledger Entry Matching Buffer" = RIMD,
                  tabledata "License Agreement" = RIMD,
                  tabledata "Line Fee Note on Report Hist." = Rimd,
                  tabledata "Line Number Buffer" = RIMD,
                  tabledata "Load Buffer" = RIMD,
                  tabledata Loaner = RIMD,
                  tabledata "Loaner Entry" = RIMD,
                  tabledata Location = RIMD,
                  tabledata "Logged Segment" = RIMd,
                  tabledata "Lot Bin Buffer" = RIMD,
                  tabledata "Lot No. Information" = RIMD,
                  tabledata "Man. Integration Field Mapping" = RIMD,
                  tabledata "Man. Integration Table Mapping" = RIMD,
                  tabledata "Man. Int. Field Mapping" = RIMD,
                  tabledata "Machine Center" = RIMD,
                  tabledata "Mailing Group" = RIMD,
                  tabledata "Main Asset Component" = RIMD,
                  tabledata Maintenance = RIMD,
                  tabledata "Maintenance Ledger Entry" = Rimd,
                  tabledata "Maintenance Registration" = RIMD,
                  tabledata Manufacturer = RIMD,
                  tabledata "Manufacturing Comment Line" = RIMD,
                  tabledata "Manufacturing Cue" = RIMD,
                  tabledata "Manufacturing Setup" = RIMD,
                  tabledata "Manufacturing User Template" = RIMD,
                  tabledata "Marketing Setup" = RIMD,
                  tabledata "Media Repository" = RIMD,
                  tabledata "Memoized Result" = RIMD,
                  tabledata "Merge Duplicates Buffer" = RIMD,
                  tabledata "Merge Duplicates Conflict" = RIMD,
                  tabledata "Merge Duplicates Line Buffer" = RIMD,
                  tabledata "Miniform Function" = RIMD,
                  tabledata "Miniform Function Group" = RIMD,
                  tabledata "Miniform Header" = RIMD,
                  tabledata "Miniform Line" = RIMD,
                  tabledata "Misc. Article" = RIMD,
                  tabledata "Misc. Article Information" = RIMD,
                  tabledata "MS-QBD Setup" = R,
                  tabledata "My Account" = RIMD,
                  tabledata "My Customer" = RIMD,
                  tabledata "My Item" = RIMD,
                  tabledata "My Job" = RIMD,
                  tabledata "My Notifications" = RIMD,
                  tabledata "My Time Sheets" = RIMD,
                  tabledata "My Vendor" = RIMD,
                  tabledata "Name/Value Buffer" = RIMD,
                  tabledata "Named Forward Link" = RIMD,
                  tabledata "No. Series" = RIMD,
                  tabledata "No. Series Line" = RIMD,
                  tabledata "No. Series Relationship" = RIMD,
                  tabledata "No. Series Tenant" = RIMD,
                  tabledata "Nonstock Item" = RIMD,
                  tabledata "Nonstock Item Setup" = RIMD,
                  tabledata "Notification Context" = RIMD,
                  tabledata "Notification Entry" = RIMD,
                  tabledata "Notification Schedule" = RIMD,
                  tabledata "Notification Setup" = RIMD,
                  tabledata "O365 Brand Color" = RIMD,
                  tabledata "O365 Device Setup Instructions" = RIMD,
                  tabledata "O365 Getting Started" = RIMD,
                  tabledata "O365 Getting Started Page Data" = RIMD,
                  tabledata "O365 HTML Template" = RIMD,
                  tabledata "O365 Payment Service Logo" = RIMD,
                  tabledata "OAuth 2.0 Setup" = RIMD,
                  tabledata "Object Translation" = RIMD,
                  tabledata "OCR Service Document Template" = RIMD,
                  tabledata "OCR Service Setup" = RIMD,
                  tabledata "OData Initialized Status" = RIMD,
                  tabledata "Office Add-in" = RIMD,
                  tabledata "Office Add-in Context" = RIMD,
                  tabledata "Office Add-in Setup" = RIMD,
                  tabledata "Office Admin. Credentials" = Rimd,
                  tabledata "Office Contact Details" = RIMD,
                  tabledata "Office Document Selection" = RIMD,
                  tabledata "Office Invoice" = RIMD,
                  tabledata "Office Job Journal" = RIMD,
                  tabledata "Office Suggested Line Item" = RIMD,
                  tabledata "Online Bank Acc. Link" = RIMD,
                  tabledata "Online Map Parameter Setup" = RIMD,
                  tabledata "Online Map Setup" = RIMD,
                  tabledata Opportunity = RIMD,
                  tabledata "Opportunity Entry" = RIMD,
                  tabledata "Option Lookup Buffer" = rimd,
                  tabledata "Order Address" = RIMD,
                  tabledata "Order Promising Line" = RIMD,
                  tabledata "Order Promising Setup" = RIMD,
                  tabledata "Order Tracking Entry" = RIMD,
                  tabledata "Organizational Level" = RIMD,
                  tabledata "Outstanding Bank Transaction" = RIMD,
                  tabledata "Over-Receipt Code" = RIMD,
                  tabledata "Overdue Approval Entry" = Rimd,
                  tabledata "Package No. Information" = RIMD,
                  tabledata "Payable Employee Ledger Entry" = RIMD,
                  tabledata "Payable Vendor Ledger Entry" = RIMD,
                  tabledata "Payment Application Proposal" = RIMD,
#if not CLEAN22
                  tabledata "Payment Buffer" = RIMD,
#endif
                  tabledata "Vendor Payment Buffer" = RIMD,
                  tabledata "Payment Export Data" = Rimd,
                  tabledata "Payment Export Remittance Text" = RIMD,
                  tabledata "Payment Jnl. Export Error Text" = RIMD,
                  tabledata "Payment Matching Details" = RIMD,
                  tabledata "Payment Method" = RIMD,
                  tabledata "Payment Method Translation" = RIMD,
                  tabledata "Payment Rec. Related Entry" = RIMD,
                  tabledata "Pmt. Rec. Applied-to Entry" = RIMD,
                  tabledata "Payment Registration Buffer" = RIMD,
                  tabledata "Payment Registration Setup" = RIMD,
                  tabledata "Payment Reporting Argument" = Rimd,
                  tabledata "Payment Service Setup" = RIMD,
                  tabledata "Payment Term Translation" = RIMD,
                  tabledata "Payment Terms" = RIMD,
                  tabledata "Payroll Import Buffer" = RIMD,
                  tabledata "Payroll Setup" = RIMD,
                  tabledata "Permission Buffer" = RIMD,
                  tabledata "Permission Conflicts" = RIMD,
                  tabledata "Permission Conflicts Overview" = RIMD,
                  tabledata "Permission Set Buffer" = RIMD,
                  tabledata "Permission Set Link" = rimd,
                  tabledata "Phys. Inventory Ledger Entry" = Rimd,
                  tabledata "Phys. Invt. Comment Line" = RIMD,
                  tabledata "Phys. Invt. Count Buffer" = RIMD,
                  tabledata "Phys. Invt. Counting Period" = RIMD,
                  tabledata "Phys. Invt. Item Selection" = RIMD,
                  tabledata "Phys. Invt. Order Header" = RIMD,
                  tabledata "Phys. Invt. Order Line" = RIMD,
                  tabledata "Phys. Invt. Record Header" = RIMD,
                  tabledata "Phys. Invt. Record Line" = RIMD,
#if not CLEAN24
                  tabledata "Phys. Invt. Tracking" = RIMD,
#endif
                  tabledata "Invt. Order Tracking" = RIMD,
                  tabledata "Picture Entity" = RIMD,
                  tabledata "Planning Assignment" = RIMD,
                  tabledata "Planning Buffer" = RIMD,
                  tabledata "Planning Component" = RIMD,
                  tabledata "Planning Error Log" = RIMD,
                  tabledata "Planning Routing Line" = RIMD,
                  tabledata "Positive Pay Detail" = RIMD,
                  tabledata "Positive Pay Entry" = RIMD,
                  tabledata "Positive Pay Entry Detail" = RIMD,
                  tabledata "Positive Pay Footer" = RIMD,
                  tabledata "Positive Pay Header" = RIMD,
                  tabledata "Post Code" = RIMD,
                  tabledata "Post Value Entry to G/L" = RImd,
                  tabledata "Postcode Service Config" = RIMD,
                  tabledata "Posted Approval Comment Line" = Rimd,
                  tabledata "Posted Approval Entry" = Rimd,
                  tabledata "Posted Assemble-to-Order Link" = RIMD,
                  tabledata "Posted Assembly Header" = RIMD,
                  tabledata "Posted Assembly Line" = RIMD,
                  tabledata "Posted Deferral Header" = RIMD,
                  tabledata "Posted Deferral Line" = RIMD,
                  tabledata "Posted Docs. With No Inc. Buf." = RIMD,
                  tabledata "Posted Gen. Journal Batch" = RIMD,
                  tabledata "Posted Gen. Journal Line" = RIMD,
                  tabledata "Posted Invt. Pick Header" = RIMD,
                  tabledata "Posted Invt. Pick Line" = RIMD,
                  tabledata "Posted Invt. Put-away Header" = RIMD,
                  tabledata "Posted Invt. Put-away Line" = RIMD,
                  tabledata "Posted Payment Recon. Hdr" = RIMD,
                  tabledata "Posted Payment Recon. Line" = RIMD,
                  tabledata "Posted Whse. Receipt Header" = RIMD,
                  tabledata "Posted Whse. Receipt Line" = RIMD,
                  tabledata "Posted Whse. Shipment Header" = RIMD,
                  tabledata "Posted Whse. Shipment Line" = RIMD,
#if not CLEAN22
                  tabledata "Power BI Service Status Setup" = RIMD,
#endif
#if not CLEAN23
                  tabledata "Power BI User Configuration" = RIMD,
                  tabledata "Power BI Report Configuration" = RIMD,
                  tabledata "Power BI User Status" = RIMD,
#endif
                  tabledata "Power BI Chart Buffer" = RIMD,
                  tabledata "Power BI Context Settings" = RIMD,
                  tabledata "Power BI Customer Reports" = RIMD,
                  tabledata "Power BI Displayed Element" = RIMD,
                  tabledata "Power BI Report Labels" = R,
                  tabledata "Power BI Report Uploads" = RIMD,
                  tabledata "Prepayment Inv. Line Buffer" = RIMD,
                  tabledata "Price Asset" = RIMD,
                  tabledata "Price Calculation Buffer" = RIMD,
                  tabledata "Price Calculation Setup" = RIMD,
                  tabledata "Price Line Filters" = RIMD,
                  tabledata "Price List Header" = RIMD,
                  tabledata "Price List Line" = RIMD,
                  tabledata "Price Worksheet Line" = RIMD,
                  tabledata "Price Source" = RIMD,
                  tabledata "Printer Selection" = RIMD,
                  tabledata "Prod. Order Capacity Need" = RIMD,
                  tabledata "Prod. Order Comment Line" = RIMD,
                  tabledata "Prod. Order Comp. Cmt Line" = RIMD,
                  tabledata "Prod. Order Component" = RIMD,
                  tabledata "Prod. Order Line" = RIMD,
                  tabledata "Prod. Order Routing Line" = RIMD,
                  tabledata "Prod. Order Routing Personnel" = RIMD,
                  tabledata "Prod. Order Routing Tool" = RIMD,
                  tabledata "Prod. Order Rtng Comment Line" = RIMD,
                  tabledata "Prod. Order Rtng Qlty Meas." = RIMD,
                  tabledata "Production BOM Comment Line" = RIMD,
                  tabledata "Production BOM Header" = RIMD,
                  tabledata "Production BOM Line" = RIMD,
                  tabledata "Production BOM Version" = RIMD,
                  tabledata "Production Forecast Entry" = RIMD,
                  tabledata "Production Forecast Name" = RIMD,
                  tabledata "Production Matrix  BOM Entry" = Rimd,
                  tabledata "Production Matrix BOM Line" = Rimd,
                  tabledata "Production Order" = RIMD,
                  tabledata "Profile Questionnaire Header" = RIMD,
                  tabledata "Profile Questionnaire Line" = RIMD,
#if not CLEAN24
                  tabledata "Pstd. Exp. Phys. Invt. Track" = RIMD,
#endif
                  tabledata "Pstd.Exp.Invt.Order.Tracking" = RIMD,
                  tabledata "Pstd. Phys. Invt. Order Hdr" = RIMD,
                  tabledata "Pstd. Phys. Invt. Order Line" = RIMD,
                  tabledata "Pstd. Phys. Invt. Record Hdr" = RIMD,
                  tabledata "Pstd. Phys. Invt. Record Line" = RIMD,
                  tabledata "Pstd. Phys. Invt. Tracking" = RIMD,
                  tabledata "Purch. Comment Line" = RIMD,
                  tabledata "Purch. Comment Line Archive" = RIMD,
                  tabledata "Purch. Cr. Memo Entity Buffer" = RIMD,
                  tabledata "Purch. Cr. Memo Hdr." = RIMD,
                  tabledata "Purch. Cr. Memo Line" = Rimd,
                  tabledata "Purch. Inv. Entity Aggregate" = RIMD,
                  tabledata "Purch. Inv. Header" = RimD,
                  tabledata "Purch. Inv. Line" = Rimd,
                  tabledata "Purch. Inv. Line Aggregate" = RIMD,
#if not CLEAN23
                  tabledata "Purch. Price Line Disc. Buff." = RIMD,
#endif
                  tabledata "Purch. Rcpt. Header" = RIMD,
                  tabledata "Purch. Rcpt. Line" = Rimd,
                  tabledata "Purchase Cue" = RIMD,
                  tabledata "Purchase Discount Access" = RIMD,
                  tabledata "Purchase Header" = RIMD,
                  tabledata "Purchase Header Archive" = RIMD,
                  tabledata "Purchase Line" = RIMD,
                  tabledata "Purchase Line Archive" = RIMD,
#if not CLEAN23
                  tabledata "Purchase Line Discount" = RIMD,
#endif
                  tabledata "Purchase Order Entity Buffer" = RIMD,
                  tabledata "Purchase Prepayment %" = RIMD,
#if not CLEAN23
                  tabledata "Purchase Price" = RIMD,
#endif
                  tabledata "Purchase Price Access" = RIMD,
                  tabledata "Purchases & Payables Setup" = RIMD,
                  tabledata Purchasing = RIMD,
                  tabledata "Put-away Template Header" = RIMD,
                  tabledata "Put-away Template Line" = RIMD,
                  tabledata Qualification = RIMD,
                  tabledata "Quality Measure" = RIMD,
                  tabledata "Query Metadata" = imd,
                  tabledata "RapidStart Services Cue" = RIMD,
                  tabledata Rating = RIMD,
                  tabledata "RC Headlines User Data" = RIMD,
                  tabledata "Reason Code" = RIMD,
                  tabledata "Receivables-Payables Buffer" = RIMD,
                  tabledata "Reclas. Dimension Set Buffer" = RIMD,
                  tabledata "Reconcile CV Acc Buffer" = RIMD,
                  tabledata "Record Buffer" = Rimd,
                  tabledata "Record Export Buffer" = RIMD,
                  tabledata "Record Set Buffer" = Rimd,
                  tabledata "Record Set Definition" = Rimd,
                  tabledata "Record Set Tree" = Rimd,
                  tabledata "Recorded Event Buffer" = RIMD,
                  tabledata "Referenced XML Schema" = RIMD,
                  tabledata "Registered Absence" = RIMD,
                  tabledata "Registered Invt. Movement Hdr." = RimD,
                  tabledata "Registered Invt. Movement Line" = Rimd,
                  tabledata "Registered Whse. Activity Hdr." = Rimd,
                  tabledata "Registered Whse. Activity Line" = Rimd,
                  tabledata "Relationship Mgmt. Cue" = RIMD,
                  tabledata Relative = RIMD,
                  tabledata "Reminder Attachment Text" = RIMD,
                  tabledata "Reminder Comment Line" = RIMD,
                  tabledata "Reminder Email Text" = RIMD,
                  tabledata "Reminder Header" = RIMD,
                  tabledata "Reminder Level" = RIMD,
                  tabledata "Reminder Line" = RIMD,
                  tabledata "Reminder Terms" = RIMD,
                  tabledata "Reminder Action Group" = RIMD,
                  tabledata "Reminder Action" = RIMD,
                  tabledata "Create Reminders Setup" = RIMD,
                  tabledata "Issue Reminders Setup" = RIMD,
                  tabledata "Send Reminders Setup" = RIMD,
                  tabledata "Reminder Automation Error" = RIMD,
                  tabledata "Reminder Action Group Log" = RIMD,
                  tabledata "Reminder Action Log" = RIMD,
                  tabledata "Reminder Terms Translation" = RIMD,
                  tabledata "Reminder Text" = RIMD,
                  tabledata "Reminder/Fin. Charge Entry" = Rimd,
                  tabledata "Remit Address" = RIMD,
                  tabledata "Repair Status" = RIMD,
                  tabledata "Report Inbox" = RIMD,
                  tabledata "Report Layout Selection" = RIMD,
                  tabledata "Report Layout Update Log" = RIMD,
                  tabledata "Report List Translation" = RIMD,
                  tabledata "Report Selection Warehouse" = RIMD,
                  tabledata "Report Selections" = RIMD,
                  tabledata "Report Totals Buffer" = RIMD,
                  tabledata "Req. Wksh. Template" = RIMD,
                  tabledata "Requisition Line" = RIMD,
                  tabledata "Requisition Wksh. Name" = RIMD,
                  tabledata "Res. Availability Buffer" = RIMD,
                  tabledata "Res. Capacity Entry" = RIMD,
                  tabledata "Res. Gr. Availability Buffer" = RIMD,
                  tabledata "Res. Journal Batch" = RIMD,
                  tabledata "Res. Journal Line" = RIMD,
                  tabledata "Res. Journal Template" = RIMD,
                  tabledata "Res. Ledger Entry" = Rimd,
                  tabledata "Reservation Entry" = RIMD,
                  tabledata "Reservation Entry Buffer" = RIMD,
                  tabledata "Resolution Code" = RIMD,
                  tabledata Resource = RIMD,
#if not CLEAN23
                  tabledata "Resource Cost" = RIMD,
#endif
                  tabledata "Resource Group" = RIMD,
                  tabledata "Resource Location" = RIMD,
#if not CLEAN23
                  tabledata "Resource Price" = RIMD,
                  tabledata "Resource Price Change" = RIMD,
#endif
                  tabledata "Resource Register" = RIMD,
                  tabledata "Resource Service Zone" = RIMD,
                  tabledata "Resource Skill" = RIMD,
                  tabledata "Resource Unit of Measure" = RIMD,
                  tabledata "Resources Setup" = RIMD,
                  tabledata "Responsibility Center" = RIMD,
                  tabledata "Restricted Record" = RIMD,
                  tabledata "Return Reason" = RIMD,
                  tabledata "Return Receipt Header" = RimD,
                  tabledata "Return Receipt Line" = Rimd,
                  tabledata "Return Shipment Header" = Rimd,
                  tabledata "Return Shipment Line" = Rimd,
                  tabledata "Returns-Related Document" = RIMD,
                  tabledata "Reversal Entry" = RIMD,
                  tabledata "Rlshp. Mgt. Comment Line" = RIMD,
                  tabledata "RM Matrix Management" = Rd,
                  tabledata "Role Center Notifications" = RIMD,
                  tabledata "Rounding Method" = RIMD,
                  tabledata "Rounding Residual Buffer" = Rimd,
                  tabledata "Routing Comment Line" = RIMD,
                  tabledata "Routing Header" = RIMD,
                  tabledata "Routing Line" = RIMD,
                  tabledata "Routing Link" = RIMD,
                  tabledata "Routing Personnel" = RIMD,
                  tabledata "Routing Quality Measure" = RIMD,
                  tabledata "Routing Tool" = RIMD,
                  tabledata "Routing Version" = RIMD,
                  tabledata "Sales & Receivables Setup" = RIMD,
                  tabledata "Sales by Cust. Grp.Chart Setup" = RIMD,
                  tabledata "Sales Comment Line" = RIMD,
                  tabledata "Sales Comment Line Archive" = RIMD,
                  tabledata "Sales Cr. Memo Entity Buffer" = RIMD,
                  tabledata "Sales Cr.Memo Header" = RimD,
                  tabledata "Sales Cr.Memo Line" = Rimd,
                  tabledata "Sales Cue" = RIMD,
                  tabledata "Sales Cycle" = RIMD,
                  tabledata "Sales Cycle Stage" = RIMD,
                  tabledata "Sales Discount Access" = RIMD,
                  tabledata "Sales Document Icon" = Rimd,
                  tabledata "Sales Header" = RIMD,
                  tabledata "Sales Header Archive" = RIMD,
                  tabledata "Sales Invoice Entity Aggregate" = RIMD,
                  tabledata "Sales Invoice Header" = RimD,
                  tabledata "Sales Invoice Line" = Rimd,
                  tabledata "Sales Invoice Line Aggregate" = RIMD,
                  tabledata "Sales Line" = RIMD,
                  tabledata "Sales Line Archive" = RIMD,
#if not CLEAN23
                  tabledata "Sales Line Discount" = RIMD,
#endif
                  tabledata "Sales Order Entity Buffer" = RIMD,
                  tabledata "Sales Planning Line" = Rimd,
                  tabledata "Sales Prepayment %" = RIMD,
#if not CLEAN23
                  tabledata "Sales Price" = RIMD,
#endif
                  tabledata "Sales Price Access" = RIMD,
#if not CLEAN23
                  tabledata "Sales Price and Line Disc Buff" = RIMD,
                  tabledata "Sales Price Worksheet" = RIMD,
#endif
                  tabledata "Sales Quote Entity Buffer" = RIMD,
                  tabledata "Sales Shipment Buffer" = RIMD,
                  tabledata "Sales Shipment Header" = RimD,
                  tabledata "Sales Shipment Line" = Rimd,
                  tabledata "Salesperson/Purchaser" = RIMD,
                  tabledata Salutation = RIMD,
                  tabledata "Salutation Formula" = RIMD,
                  tabledata "Saved Segment Criteria" = RIMD,
                  tabledata "Saved Segment Criteria Line" = RIMD,
                  tabledata "SB Owner Cue" = RIMD,
                  tabledata Scrap = RIMD,
                  tabledata "Segment Criteria Line" = RIMD,
                  tabledata "Segment Header" = RIMD,
                  tabledata "Segment History" = RIMD,
                  tabledata "Segment Interaction Language" = RIMD,
                  tabledata "Segment Line" = RIMD,
                  tabledata "Segment Wizard Filter" = RIMD,
                  tabledata "Selected Dimension" = RIMD,
                  tabledata "Semi-Manual Execution Log" = RIMD,
                  tabledata "Semi-Manual Test Wizard" = RIMD,
                  tabledata "Sent Notification Entry" = RIMD,
                  tabledata "SEPA Direct Debit Mandate" = RIMD,
                  tabledata "Serial No. Information" = RIMD,
                  tabledata "Serv. Price Adjustment Detail" = RIMD,
                  tabledata "Serv. Price Group Setup" = RIMD,
                  tabledata "Service Comment Line" = RIMD,
                  tabledata "Service Connection" = RIMD,
                  tabledata "Service Contract Account Group" = RIMD,
                  tabledata "Service Contract Header" = RIMD,
                  tabledata "Service Contract Line" = RIMD,
                  tabledata "Service Contract Template" = RIMD,
                  tabledata "Service Cost" = RIMD,
                  tabledata "Service Cr.Memo Header" = RIMD,
                  tabledata "Service Cr.Memo Line" = RIMD,
                  tabledata "Service Cue" = RIMD,
                  tabledata "Service Document Log" = RIMD,
                  tabledata "Service Document Register" = RIMD,
                  tabledata "Service Email Queue" = RIMD,
                  tabledata "Service Header" = RIMD,
                  tabledata "Service Hour" = RIMD,
                  tabledata "Service Invoice Header" = RIMD,
                  tabledata "Service Invoice Line" = RIMD,
                  tabledata "Service Item" = RIMD,
                  tabledata "Service Item Component" = RIMD,
                  tabledata "Service Item Group" = RIMD,
                  tabledata "Service Item Line" = RIMD,
                  tabledata "Service Item Log" = RIMD,
                  tabledata "Service Item Trend Buffer" = RIMD,
                  tabledata "Service Ledger Entry" = Rimd,
                  tabledata "Service Line" = RIMD,
                  tabledata "Service Line Price Adjmt." = RIMD,
                  tabledata "Service Mgt. Setup" = RIMD,
                  tabledata "Service Order Allocation" = RIMD,
                  tabledata "Service Order Posting Buffer" = RIMD,
                  tabledata "Service Order Type" = RIMD,
                  tabledata "Service Price Adjustment Group" = RIMD,
                  tabledata "Service Price Group" = RIMD,
                  tabledata "Service Register" = RIMD,
                  tabledata "Service Shelf" = RIMD,
                  tabledata "Service Shipment Buffer" = RimD,
                  tabledata "Service Shipment Header" = RIMD,
                  tabledata "Service Shipment Item Line" = RIMD,
                  tabledata "Service Shipment Line" = RIMD,
                  tabledata "Service Status Priority Setup" = RIMD,
                  tabledata "Service Zone" = RIMD,
                  tabledata "Ship-to Address" = RIMD,
                  tabledata "Shipment Method" = RIMD,
                  tabledata "Shipment Method Translation" = RIMD,
                  tabledata "Shipping Agent" = RIMD,
                  tabledata "Shipping Agent Services" = RIMD,
                  tabledata "Shop Calendar" = RIMD,
                  tabledata "Shop Calendar Holiday" = RIMD,
                  tabledata "Shop Calendar Working Days" = RIMD,
                  tabledata "Skill Code" = RIMD,
                  tabledata "Sorting Table" = RIMD,
                  tabledata "Source Code" = RIMD,
                  tabledata "Source Code Setup" = RIMD,
                  tabledata "Special Equipment" = RIMD,
                  tabledata "Standard Address" = Rimd,
                  tabledata "Standard Cost Worksheet" = RIMD,
                  tabledata "Standard Cost Worksheet Name" = RIMD,
                  tabledata "Standard Customer Sales Code" = RIMD,
                  tabledata "Standard General Journal" = RIMD,
                  tabledata "Standard General Journal Line" = RIMD,
                  tabledata "Standard Item Journal" = RIMD,
                  tabledata "Standard Item Journal Line" = RIMD,
                  tabledata "Standard Purchase Code" = RIMD,
                  tabledata "Standard Purchase Line" = RIMD,
                  tabledata "Standard Sales Code" = RIMD,
                  tabledata "Standard Sales Line" = RIMD,
                  tabledata "Standard Service Code" = RIMD,
                  tabledata "Standard Service Item Gr. Code" = RIMD,
                  tabledata "Standard Service Line" = RIMD,
                  tabledata "Standard Task" = RIMD,
                  tabledata "Standard Task Description" = RIMD,
                  tabledata "Standard Task Personnel" = RIMD,
                  tabledata "Standard Task Quality Measure" = RIMD,
                  tabledata "Standard Task Tool" = RIMD,
                  tabledata "Standard Text" = RIMD,
                  tabledata "Standard Vendor Purchase Code" = RIMD,
                  tabledata "Stockkeeping Unit" = RIMD,
                  tabledata "Stockkeeping Unit Comment Line" = RIMD,
                  tabledata Stop = RIMD,
                  tabledata "Substitution Condition" = RIMD,
                  tabledata "Support Contact Information" = R,
                  tabledata "SWIFT Code" = RIMD,
                  tabledata "Symptom Code" = RIMD,
                  tabledata "Table Filter" = RIMD,
                  tabledata "Tariff Number" = RIMD,
                  tabledata "Tax Area" = RIMD,
                  tabledata "Tax Area Buffer" = RIMD,
                  tabledata "Tax Area Line" = RIMD,
                  tabledata "Tax Area Translation" = RIMD,
                  tabledata "Tax Detail" = RIMD,
                  tabledata "Tax Group" = RIMD,
                  tabledata "Tax Group Buffer" = RIMD,
                  tabledata "Tax Jurisdiction" = RIMD,
                  tabledata "Tax Jurisdiction Translation" = RIMD,
                  tabledata "Tax Rate Buffer" = RIMD,
                  tabledata "Tax Setup" = RIMD,
                  tabledata Team = RIMD,
                  tabledata "Team Member Cue" = RIMD,
                  tabledata "Team Salesperson" = RIMD,
                  tabledata "Temp Integration Field Mapping" = RIMD,
                  tabledata TempStack = RIMD,
                  tabledata "Tenant Config. Package File" = RIMD,
                  tabledata "Terms And Conditions" = RIM,
                  tabledata "Terms And Conditions State" = RIM,
                  tabledata Territory = RIMD,
                  tabledata "Text-to-Account Mapping" = RIMD,
                  tabledata "Time Series Buffer" = R,
                  tabledata "Time Series Forecast" = R,
                  tabledata "Time Sheet Chart Setup" = RIMD,
                  tabledata "Time Sheet Cmt. Line Archive" = RIMD,
                  tabledata "Time Sheet Comment Line" = RIMD,
                  tabledata "Time Sheet Detail" = RIMD,
                  tabledata "Time Sheet Detail Archive" = RIMD,
                  tabledata "Time Sheet Header" = RIMD,
                  tabledata "Time Sheet Header Archive" = RIMD,
                  tabledata "Time Sheet Line" = RIMD,
                  tabledata "Time Sheet Line Archive" = RIMD,
                  tabledata "Time Sheet Posting Entry" = RIMD,
                  tabledata "Timeline Event" = RIMD,
                  tabledata "Timeline Event Change" = RIMD,
                  tabledata "To-do" = RIMD,
                  tabledata "To-do Interaction Language" = RIMD,
                  tabledata "Top Customers By Sales Buffer" = RIMD,
                  tabledata "Total Value Insured" = RIMD,
                  tabledata "Tracking Specification" = RIMD,
                  tabledata "Trailing Sales Orders Setup" = RIMD,
                  tabledata "Transaction Specification" = RIMD,
                  tabledata "Transaction Type" = RIMD,
                  tabledata "Transfer Header" = RIMD,
                  tabledata "Transfer Line" = RIMD,
                  tabledata "Transfer Receipt Header" = RIMD,
                  tabledata "Transfer Receipt Line" = RIMD,
                  tabledata "Transfer Route" = RIMD,
                  tabledata "Transfer Shipment Header" = RIMD,
                  tabledata "Transfer Shipment Line" = RIMD,
                  tabledata "Transformation Rule" = RIMD,
                  tabledata "Transport Method" = RIMD,
                  tabledata "Trial Balance Cache" = RIMD,
                  tabledata "Trial Balance Cache Info" = RIMD,
                  tabledata "Trial Balance Entity Buffer" = RIMD,
                  tabledata "Trial Balance Setup" = RIMD,
                  tabledata "Troubleshooting Header" = RIMD,
                  tabledata "Troubleshooting Line" = RIMD,
                  tabledata "Troubleshooting Setup" = RIMD,
                  tabledata Union = RIMD,
                  tabledata "Unit Group" = RIMD,
                  tabledata "Unit of Measure" = RIMD,
                  tabledata "Unit of Measure Translation" = RIMD,
                  tabledata "Unlinked Attachment" = RIMD,
                  tabledata "Unplanned Demand" = RIMD,
                  tabledata "Untracked Planning Element" = RIMD,
#if not CLEAN22
                  tabledata "User Group" = R,
                  tabledata "User Group Access Control" = R,
                  tabledata "User Group Member" = Rimd,
                  tabledata "User Group Permission Set" = R,
                  tabledata "User Group Plan" = Rimd,
#endif
                  tabledata "User Preference" = RIMD,
                  tabledata "User Security Status" = RIMD,
                  tabledata "User Setup" = RIMD,
                  tabledata "User Task" = RIMD,
                  tabledata "User Task Group" = RIMD,
                  tabledata "User Task Group Member" = RIMD,
                  tabledata "User Time Register" = RIMD,
                  tabledata "User Tours" = RIMD,
                  tabledata "Value Entry" = Rimd,
                  tabledata "Value Entry Relation" = RIMD,
                  tabledata "VAT Amount Line" = RIMD,
                  tabledata "VAT Assisted Setup Bus. Grp." = RIMD,
                  tabledata "VAT Assisted Setup Templates" = RIMD,
                  tabledata "VAT Business Posting Group" = RIMD,
                  tabledata "VAT Clause" = RIMD,
                  tabledata "VAT Clause by Doc. Type" = RIMD,
                  tabledata "VAT Clause by Doc. Type Trans." = RIMD,
                  tabledata "VAT Clause Translation" = RIMD,
                  tabledata "VAT Entry" = Rimd,
                  tabledata "VAT Posting Setup" = RIMD,
                  tabledata "VAT Product Posting Group" = RIMD,
                  tabledata "VAT Rate Change Conversion" = RIMD,
                  tabledata "VAT Rate Change Log Entry" = Rimd,
                  tabledata "VAT Rate Change Setup" = RIMD,
                  tabledata "VAT Reg. No. Srv Config" = RIMD,
                  tabledata "VAT Reg. No. Srv. Template" = RIMD,
                  tabledata "VAT Registration Log" = RIMD,
                  tabledata "VAT Registration Log Details" = RIMD,
                  tabledata "VAT Registration No. Format" = RIMD,
                  tabledata "VAT Report Archive" = Rimd,
                  tabledata "VAT Report Error Log" = RIMD,
                  tabledata "VAT Report Header" = RIMD,
                  tabledata "VAT Report Line" = RIMD,
                  tabledata "VAT Report Line Relation" = RIMD,
                  tabledata "VAT Report Setup" = RIMD,
                  tabledata "VAT Reporting Code" = RIMD,
                  tabledata "VAT Reports Configuration" = RIMD,
                  tabledata "VAT Return Period" = RIMD,
                  tabledata "VAT Setup Posting Groups" = RIMD,
                  tabledata "VAT Statement Line" = RIMD,
                  tabledata "VAT Statement Name" = RIMD,
                  tabledata "VAT Statement Report Line" = RIMD,
                  tabledata "VAT Statement Template" = RIMD,
                  tabledata "VAT Setup" = RIMD,
                  tabledata "VAT Posting Parameters" = RIMD,
                  tabledata Vendor = RIMD,
                  tabledata "Vendor Amount" = RIMD,
                  tabledata "Vendor Bank Account" = RIMD,
                  tabledata "Vendor Invoice Disc." = RIMD,
                  tabledata "Vendor Ledger Entry" = RiMd,
                  tabledata "Vendor Posting Group" = RIMD,
                  tabledata "Vendor Purchase Buffer" = RIMD,
                  tabledata "Vendor Templ." = RIMD,
                  tabledata "Warehouse Activity Header" = RIMD,
                  tabledata "Warehouse Activity Line" = RIMD,
                  tabledata "Warehouse Basic Cue" = RIMD,
                  tabledata "Warehouse Class" = RIMD,
                  tabledata "Warehouse Comment Line" = RIMD,
                  tabledata "Warehouse Employee" = RIMD,
                  tabledata "Warehouse Entry" = Rimd,
                  tabledata "Warehouse Journal Batch" = RIMD,
                  tabledata "Warehouse Journal Line" = RIMD,
                  tabledata "Warehouse Journal Template" = RIMD,
                  tabledata "Warehouse Reason Code" = RIMD,
                  tabledata "Warehouse Receipt Header" = RIMD,
                  tabledata "Warehouse Receipt Line" = RIMD,
                  tabledata "Warehouse Register" = RIMD,
                  tabledata "Warehouse Request" = RIMD,
                  tabledata "Warehouse Setup" = RIMD,
                  tabledata "Warehouse Shipment Header" = RIMD,
                  tabledata "Warehouse Shipment Line" = RIMD,
                  tabledata "Warehouse Source Filter" = RIMD,
                  tabledata "Warehouse WMS Cue" = RIMD,
                  tabledata "Warehouse Worker WMS Cue" = RIMD,
                  tabledata "Warranty Ledger Entry" = RIMD,
                  tabledata "Web Source" = RIMD,
                  tabledata "WF Event/Response Combination" = RIMD,
                  tabledata "Where Used Base Calendar" = RIMD,
                  tabledata "Where-Used Line" = Rimd,
                  tabledata "Whse. Cross-Dock Opportunity" = RIMD,
                  tabledata "Whse. Internal Pick Header" = RIMD,
                  tabledata "Whse. Internal Pick Line" = RIMD,
                  tabledata "Whse. Internal Put-away Header" = RIMD,
                  tabledata "Whse. Internal Put-away Line" = RIMD,
                  tabledata "Whse. Item Entry Relation" = RIMD,
                  tabledata "Whse. Item Tracking Line" = Rimd,
                  tabledata "Whse. Pick Request" = RIMD,
                  tabledata "Whse. Put-away Request" = RIMD,
                  tabledata "Whse. Worksheet Line" = RIMD,
                  tabledata "Whse. Worksheet Name" = RIMD,
                  tabledata "Whse. Worksheet Template" = RIMD,
                  tabledata "Work Center" = RIMD,
                  tabledata "Work Center Group" = RIMD,
                  tabledata "Work Shift" = RIMD,
                  tabledata "Work Type" = RIMD,
                  tabledata "Work-Hour Template" = RIMD,
                  tabledata "Workflow - Record Change" = Rimd,
                  tabledata "Workflow - Table Relation" = RIMD,
                  tabledata Workflow = RIMD,
                  tabledata "Workflow Buffer" = RIMD,
                  tabledata "Workflow Category" = RIMD,
                  tabledata "Workflow Event" = RIMD,
                  tabledata "Workflow Event Queue" = RIMD,
                  tabledata "Workflow Record Change Archive" = Rimd,
                  tabledata "Workflow Response" = RIMD,
                  tabledata "Workflow Rule" = RIMD,
                  tabledata "Workflow Step" = RIMD,
                  tabledata "Workflow Step Argument" = RIMD,
                  tabledata "Workflow Step Argument Archive" = Rimd,
                  tabledata "Workflow Step Buffer" = RIMD,
                  tabledata "Workflow Step Instance" = RIMD,
                  tabledata "Workflow Step Instance Archive" = Rimd,
                  tabledata "Workflow Table Relation Value" = RIMD,
                  tabledata "Workflow User Group" = RIMD,
                  tabledata "Workflow User Group Member" = RIMD,
                  tabledata "Workflow Webhook Entry" = Rimd,
                  tabledata "Workflow Webhook Notification" = Rimd,
                  tabledata "Workflow Webhook Sub Buffer" = RIMD,
                  tabledata "Workflow Webhook Subscription" = RIMD,
                  tabledata "Workflows Entries Buffer" = Rimd,
                  tabledata "XML Buffer" = RIMD,
                  tabledata "XML Schema" = RIMD,
                  tabledata "XML Schema Element" = RIMD,
                  tabledata "XML Schema Restriction" = RIMD,
                  tabledata Zone = RIMD;
}
