permissionset 6850 "D365PREM SMG, EDIT"
{
    Assignable = true;

    Caption = 'D365 Service Management Edit';
    Permissions = tabledata "Contract/Service Discount" = RIMD,
                  tabledata "Dtld. Price Calculation Setup" = RIMD,
                  tabledata "Duplicate Price Line" = RIMD,
                  tabledata "Filed Service Contract Header" = RIMD,
                  tabledata "Price Asset" = RIMD,
                  tabledata "Price Calculation Buffer" = RIMD,
                  tabledata "Price Calculation Setup" = RIMD,
                  tabledata "Price Line Filters" = RIMD,
                  tabledata "Price List Header" = RIMD,
                  tabledata "Price List Line" = RIMD,
                  tabledata "Price Source" = RIMD,
                  tabledata "Serv. Price Adjustment Detail" = RIMD,
                  tabledata "Serv. Price Group Setup" = RIMD,
                  tabledata "Service Comment Line" = RIMD,
                  tabledata "Service Contract Account Group" = RIMD,
                  tabledata "Service Contract Header" = RIMD,
                  tabledata "Service Contract Line" = RIMD,
                  tabledata "Service Contract Template" = RIMD,
                  tabledata "Service Cost" = RIMD,
                  tabledata "Service Cr.Memo Header" = RIMD,
                  tabledata "Service Cr.Memo Line" = RIMD,
                  tabledata "Service Document Log" = RIMD,
                  tabledata "Service Document Register" = RIMD,
                  tabledata "Service Email Queue" = RIMD,
                  tabledata "Service Header" = RIMD,
                  tabledata "Service Hour" = RIMD,
                  tabledata "Service Invoice Header" = RIMD,
                  tabledata "Service Invoice Line" = RIMD,
                  tabledata "Service Item" = RIMD,
                  tabledata "Service Item Component" = RIMD,
                  tabledata "Service Item Group" = RIMD,
                  tabledata "Service Item Line" = RIMD,
                  tabledata "Service Item Log" = RIMD,
                  tabledata "Service Ledger Entry" = Rimd,
                  tabledata "Service Line" = RIMD,
                  tabledata "Service Line Price Adjmt." = RIMD,
                  tabledata "Service Mgt. Setup" = RIMD,
                  tabledata "Service Order Allocation" = RIMD,
                  tabledata "Service Order Posting Buffer" = RIMD,
                  tabledata "Service Order Type" = RIMD,
                  tabledata "Service Price Adjustment Group" = RIMD,
                  tabledata "Service Price Group" = RIMD,
                  tabledata "Service Register" = RIMD,
                  tabledata "Service Shelf" = RIMD,
                  tabledata "Service Shipment Header" = RIMD,
                  tabledata "Service Shipment Item Line" = RIMD,
                  tabledata "Service Shipment Line" = RIMD,
                  tabledata "Service Status Priority Setup" = RIMD,
                  tabledata "Service Zone" = RIMD;
}
