namespace System.Security.AccessControl;

using Microsoft.AccountantPortal;
using Microsoft.Booking;
using Microsoft.Intercompany.Comment;
using Microsoft.CostAccounting.Setup;
using Microsoft.Manufacturing.Reports;
using Microsoft.Bank.Payment;
using Microsoft.Foundation.Reporting;
using Microsoft.EServices.EDocument;
using Microsoft.Foundation.Attachment;
using Microsoft.Foundation.Navigate;
using Microsoft.Finance.VAT.Reporting;
using Microsoft.Finance.VAT.Ledger;
using Microsoft.eServices.OnlineMap;
using Microsoft.Finance.Payroll;
using Microsoft.Inventory.Reconciliation;
using Microsoft.Projects.Project.Journal;
#if not CLEAN25
using Microsoft.Projects.Project.Pricing;
#endif
using Microsoft.Projects.Project.Ledger;
using Microsoft.Projects.Project.Planning;
using Microsoft.Projects.Project.Posting;
using Microsoft.Projects.Project.WIP;
using Microsoft.Projects.Project.Setup;
using System.Security.Authentication;
using System.Globalization;
using Microsoft.Foundation.AuditCodes;
using Microsoft.Foundation.Shipping;
using Microsoft.Foundation.UOM;
using Microsoft.Foundation.Task;
using Microsoft.Finance.VAT.Calculation;
using Microsoft.Finance.VAT.Setup;
using Microsoft.Finance.VAT.Clause;
using Microsoft.Finance.VAT.RateChange;
using Microsoft.Finance.VAT.Registration;
using Microsoft.Assembly.Comment;
using Microsoft.Assembly.Document;
using Microsoft.Assembly.History;
using Microsoft.Assembly.Reports;
using Microsoft.Assembly.Setup;
using Microsoft.Bank.BankAccount;
using Microsoft.Bank.Check;
using Microsoft.Bank.DirectDebit;
using Microsoft.Bank.Ledger;
using Microsoft.Bank.PositivePay;
using Microsoft.Bank.Reconciliation;
using Microsoft.Bank.Setup;
using Microsoft.Bank.Statement;
using Microsoft.CashFlow.Account;
using Microsoft.CashFlow.Comment;
using Microsoft.CashFlow.Forecast;
using Microsoft.CashFlow.Setup;
using Microsoft.CashFlow.Worksheet;
using Microsoft.CostAccounting.Account;
using Microsoft.CostAccounting.Allocation;
using Microsoft.CostAccounting.Budget;
using Microsoft.CostAccounting.Journal;
using Microsoft.CostAccounting.Ledger;
using Microsoft.CRM.Analysis;
using Microsoft.CRM.BusinessRelation;
using Microsoft.CRM.Campaign;
using Microsoft.CRM.Comment;
using Microsoft.CRM.Contact;
using Microsoft.CRM.Duplicates;
using Microsoft.CRM.Interaction;
using Microsoft.CRM.Opportunity;
using Microsoft.CRM.Outlook;
using Microsoft.CRM.Profiling;
using Microsoft.CRM.RoleCenters;
using Microsoft.CRM.Segment;
using Microsoft.CRM.Setup;
using Microsoft.CRM.Task;
using Microsoft.CRM.Team;
using Microsoft.Finance.AllocationAccount;
using Microsoft.Finance.Analysis;
using Microsoft.Finance.Consolidation;
using Microsoft.Finance.Currency;
using Microsoft.Finance.Deferral;
using Microsoft.Finance.Dimension.Correction;
using Microsoft.Finance.Dimension;
using Microsoft.Finance.FinancialReports;
using Microsoft.Finance.GeneralLedger.Account;
using Microsoft.Finance.GeneralLedger.Budget;
using Microsoft.Finance.GeneralLedger.Journal;
using Microsoft.Finance.GeneralLedger.Ledger;
using Microsoft.Finance.GeneralLedger.Reports;
using Microsoft.Finance.GeneralLedger.Reversal;
using Microsoft.Finance.GeneralLedger.Setup;
using Microsoft.Finance.ReceivablesPayables;
using Microsoft.Finance.RoleCenters;
using Microsoft.Finance.SalesTax;
using Microsoft.FixedAssets.Depreciation;
using Microsoft.FixedAssets.FixedAsset;
using Microsoft.FixedAssets.Insurance;
using Microsoft.FixedAssets.Journal;
using Microsoft.FixedAssets.Ledger;
using Microsoft.FixedAssets.Maintenance;
using Microsoft.FixedAssets.Posting;
using Microsoft.FixedAssets.Setup;
using Microsoft.Foundation.Address;
using Microsoft.Foundation.Comment;
using Microsoft.Foundation.Company;
using Microsoft.Foundation.ExtendedText;
using Microsoft.Foundation.NoSeries;
using Microsoft.Foundation.PaymentTerms;
using Microsoft.HumanResources.Comment;
using Microsoft.HumanResources.Employee;
using Microsoft.HumanResources.Payables;
using Microsoft.HumanResources.Setup;
using Microsoft.Integration.D365Sales;
using Microsoft.Integration.Dataverse;
#if not CLEAN25
using Microsoft.Integration.FieldService;
#endif
using Microsoft.Integration.Entity;
using Microsoft.Integration.Graph;
using Microsoft.Integration.SyncEngine;
using Microsoft.Integration.PowerBI;
using Microsoft.Intercompany.BankAccount;
using Microsoft.Intercompany.Dimension;
using Microsoft.Intercompany.GLAccount;
using Microsoft.Intercompany.Inbox;
using Microsoft.Intercompany.Outbox;
using Microsoft.Intercompany.Partner;
using Microsoft.Intercompany.Setup;
using Microsoft.Inventory.Analysis;
using Microsoft.Inventory.Availability;
using Microsoft.Inventory.BOM.Tree;
using Microsoft.Inventory.BOM;
using Microsoft.Inventory.Comment;
using Microsoft.Inventory.Costing;
using Microsoft.Inventory.Counting.Comment;
using Microsoft.Inventory.Counting.Document;
using Microsoft.Inventory.Counting.History;
using Microsoft.Inventory.Counting.Journal;
using Microsoft.Inventory.Counting.Recording;
using Microsoft.Inventory.Counting.Tracking;
using Microsoft.Inventory.Document;
using Microsoft.Inventory.History;
using Microsoft.Inventory.Item.Attribute;
using Microsoft.Inventory.Item.Catalog;
using Microsoft.Inventory.Item.Picture;
using Microsoft.Inventory.Item.Substitution;
using Microsoft.Inventory.Item;
using Microsoft.Inventory.Journal;
using Microsoft.Inventory.Ledger;
using Microsoft.Inventory.Location;
using Microsoft.Inventory.Planning;
using Microsoft.Inventory.Requisition;
using Microsoft.Inventory.Setup;
using Microsoft.Inventory.Tracking;
using Microsoft.Inventory.Transfer;
using Microsoft.Manufacturing.Capacity;
using Microsoft.Manufacturing.Comment;
using Microsoft.Manufacturing.Document;
using Microsoft.Manufacturing.Family;
using Microsoft.Manufacturing.Forecast;
using Microsoft.Manufacturing.MachineCenter;
using Microsoft.Manufacturing.ProductionBOM;
using Microsoft.Manufacturing.RoleCenters;
using Microsoft.Manufacturing.Routing;
using Microsoft.Manufacturing.Setup;
using Microsoft.Manufacturing.StandardCost;
using Microsoft.Manufacturing.WorkCenter;
using Microsoft.Pricing.Asset;
using Microsoft.Pricing.Calculation;
using Microsoft.Pricing.PriceList;
using Microsoft.Pricing.Source;
using Microsoft.Pricing.Worksheet;
using Microsoft.Projects.Resources.Analysis;
using Microsoft.Projects.Resources.Journal;
using Microsoft.Projects.Resources.Ledger;
#if not CLEAN25
using Microsoft.Projects.Resources.Pricing;
#endif
using Microsoft.Projects.Resources.Resource;
using Microsoft.Projects.Resources.Setup;
using Microsoft.Projects.RoleCenters;
using Microsoft.Purchases.Archive;
using Microsoft.Purchases.Comment;
using Microsoft.Purchases.Document;
using Microsoft.Purchases.History;
using Microsoft.Purchases.Payables;
using Microsoft.Purchases.Pricing;
using Microsoft.Purchases.Remittance;
using Microsoft.Purchases.RoleCenters;
using Microsoft.Purchases.Setup;
using Microsoft.Purchases.Vendor;
using Microsoft.Sales.Analysis;
using Microsoft.Sales.Archive;
using Microsoft.Sales.Comment;
using Microsoft.Sales.Customer;
using Microsoft.Sales.Document;
using Microsoft.Sales.FinanceCharge;
using Microsoft.Sales.History;
using Microsoft.Sales.Pricing;
using Microsoft.Sales.Receivables;
using Microsoft.Sales.Reminder;
using Microsoft.Sales.RoleCenters;
using Microsoft.Sales.Setup;
using Microsoft.Warehouse.Activity.History;
using Microsoft.Warehouse.Activity;
using Microsoft.Warehouse.ADCS;
using Microsoft.Warehouse.Comment;
using Microsoft.Warehouse.CrossDock;
using Microsoft.Warehouse.Document;
using Microsoft.Warehouse.History;
using Microsoft.Warehouse.InternalDocument;
using Microsoft.Warehouse.InventoryDocument;
using Microsoft.Warehouse.Journal;
using Microsoft.Warehouse.Ledger;
using Microsoft.Warehouse.Request;
using Microsoft.Warehouse.RoleCenters;
using Microsoft.Warehouse.Setup;
using Microsoft.Warehouse.Structure;
using Microsoft.Warehouse.Tracking;
using Microsoft.Warehouse.Worksheet;
using System.AI;
using System.Automation;
using System.Azure.Identity;
using System.DateTime;
using System.Device;
using System.Diagnostics;
using System.Email;
using System.Environment.Configuration;
using System.Environment;
using System.Integration.PowerBI;
using System.Integration;
using System.IO;
using System.Privacy;
using System.Reflection;
using System.Security.Encryption;
using System.Security.User;
using System.TestTools;
using System.Text;
using System.Threading;
using System.Tooling;
using System.Utilities;
using System.Visualization;
using System.Xml;
using System.Apps;
using System.Upgrade;
using Microsoft.RoleCenters;
using Microsoft.Projects.Project.Job;
using Microsoft.Projects.TimeSheet;
using Microsoft.Foundation.Period;
using Microsoft.Utilities;
using Microsoft.Inventory.Intrastat;
using Microsoft.Foundation.Calendar;
using Microsoft.Foundation.BatchProcessing;
using Microsoft.HumanResources.Absence;
using Microsoft.API;
using Microsoft;

using Microsoft.Service.Archive;
using Microsoft.Service.Comment;
using Microsoft.Service.Contract;
using Microsoft.Service.Document;
using Microsoft.Service.Email;
using Microsoft.Service.History;
using Microsoft.Service.Item;
using Microsoft.Service.Ledger;
using Microsoft.Service.Loaner;
using Microsoft.Service.Maintenance;
using Microsoft.Service.Posting;
using Microsoft.Service.Pricing;
using Microsoft.Service.Resources;
using Microsoft.Service.RoleCenters;
using Microsoft.Service.Setup;

permissionset 6121 "INTELLIGENT CLOUD"
{
    Access = Public;
    Assignable = true;
    Caption = 'D365 Intelligent Cloud';

    IncludedPermissionSets = "BaseApp Objects - Exec",
                             "System App - Basic",
                             "Session - Edit";

    Permissions = system "Tools, Security, Roles" = X,
                  tabledata "Add-in" = imd,
                  tabledata "Aggregate Permission Set" = R,
                  tabledata "All Profile" = IMD,
                  tabledata "All Profile Extension" = IMD,
                  tabledata "All Profile Page Metadata" = IMD,
                  tabledata AllObjWithCaption = R,
                  tabledata Chart = m,
                  tabledata "Code Coverage" = R,
                  tabledata "Data Sensitivity" = RM,
                  tabledata "Dispute Status" = R,
                  tabledata Device = Rm,
                  tabledata "Document Service" = m,
                  tabledata Drive = R,
                  tabledata Entitlement = m,
                  tabledata "Entitlement Set" = m,
                  tabledata "Event Subscription" = R,
                  tabledata "Feature Key" = R,
                  tabledata Field = R,
                  tabledata File = R,
                  tabledata Integer = R,
                  tabledata "Intelligent Cloud" = Rimd,
                  tabledata "Intelligent Cloud Status" = R,
                  tabledata Key = R,
                  tabledata Media = m,
                  tabledata "Media Set" = m,
                  tabledata "Membership Entitlement" = m,
                  tabledata "NAV App Installed App" = Rm,
                  tabledata "NAV App Setting" = R,
                  tabledata "Object Access Intent Override" = R,
                  tabledata "Object Metadata" = m,
                  tabledata "Object Options" = M,
                  tabledata Permission = m,
                  tabledata "Permission Set" = m,
                  tabledata "Profile Configuration Symbols" = IMD,
                  tabledata "Published Application" = R,
                  tabledata "Query Navigation" = R,
                  tabledata "Report Layout" = Rm,
                  tabledata "Scheduled Task" = m,
                  tabledata "Server Instance" = m,
                  tabledata "SID - Account ID" = R,
                  tabledata "Table Information" = R,
                  tabledata "Table Synch. Setup" = R,
                  tabledata "Tenant Profile" = IMD,
                  tabledata "Tenant Profile Extension" = IMD,
                  tabledata "Tenant Profile Page Metadata" = IMD,
                  tabledata "Tenant Profile Setting" = IMD,
                  tabledata "Tenant Web Service" = RIMD,
                  tabledata "Upgrade Blob Storage" = Rm,
                  tabledata User = RM,
                  tabledata "User Property" = Rimd,
                  report "Account Schedule" = X,
                  table "Activities Cue" = X,
                  table "Approvals Activities Cue" = X,
                  table "Business Chart User Setup" = X,
                  table "My Account" = X,
                  table "My Item" = X,
                  table "My Job" = X,
                  table "My Time Sheets" = X,
                  table "Power BI Chart Buffer" = X,
                  table "Power BI Context Settings" = X,
                  table "Power BI Displayed Element" = X,
                  table "Power BI Report Labels" = X,

                  tabledata "AAD Application" = R,
                  tabledata "Acc. Sched. Cell Value" = R,
                  tabledata "Acc. Sched. Chart Setup Line" = R,
                  tabledata "Acc. Sched. KPI Buffer" = R,
                  tabledata "Acc. Sched. KPI Web Srv. Line" = R,
                  tabledata "Acc. Sched. KPI Web Srv. Setup" = R,
                  tabledata "Acc. Schedule Line" = R,
                  tabledata "Acc. Schedule Line Entity" = R,
                  tabledata "Acc. Schedule Name" = R,
                  tabledata "Financial Report" = R,
                  tabledata "Financial Report User Filters" = RIMD,
                  tabledata "Account Schedules Chart Setup" = RIMD,
                  tabledata "Account Use Buffer" = R,
                  tabledata "Accounting Period" = R,
                  tabledata "Accounting Services Cue" = RIMD,
                  tabledata "Action Message Entry" = R,
                  tabledata "Activities Cue" = RIMD,
                  tabledata Activity = R,
                  tabledata "Activity Log" = RIMD,
                  tabledata "Activity Step" = R,
                  tabledata "ADCS User" = R,
                  tabledata "Additional Fee Setup" = R,
                  tabledata "Adjust Exchange Rate Buffer" = R,
                  tabledata "Administration Cue" = RIMD,
                  tabledata "Aged Report Entity" = R,
                  tabledata "Aging Band Buffer" = R,
                  tabledata "Alloc. Acc. Manual Override" = R,
                  tabledata "Alloc. Account Distribution" = R,
                  tabledata "Allocation Account" = R,
                  tabledata "Allocation Line" = R,
                  tabledata "Alternative Address" = R,
                  tabledata "Analysis by Dim. Parameters" = R,
                  tabledata "Analysis by Dim. User Param." = R,
                  tabledata "Analysis Column" = R,
                  tabledata "Analysis Column Template" = R,
                  tabledata "Analysis Dim. Selection Buffer" = R,
                  tabledata "Analysis Field Value" = R,
                  tabledata "Analysis Line" = R,
                  tabledata "Analysis Line Template" = R,
                  tabledata "Analysis Report Chart Line" = R,
                  tabledata "Analysis Report Chart Setup" = R,
                  tabledata "Analysis Report Name" = R,
                  tabledata "Analysis Selected Dimension" = R,
                  tabledata "Analysis Type" = R,
                  tabledata "Analysis View" = R,
                  tabledata "Analysis View Budget Entry" = R,
                  tabledata "Analysis View Entry" = R,
                  tabledata "Analysis View Filter" = R,
                  tabledata "API Entities Setup" = R,
                  tabledata "API Extension Upload" = r,
                  tabledata "Application Area Buffer" = R,
                  tabledata "Application Area Setup" = R,
                  tabledata "Applied Payment Entry" = R,
                  tabledata "Approval Comment Line" = R,
                  tabledata "Approval Entry" = R,
                  tabledata "Approval Workflow Wizard" = R,
                  tabledata "Approvals Activities Cue" = RIMD,
                  tabledata Area = R,
                  tabledata "Assemble-to-Order Link" = R,
                  tabledata "Assembly Comment Line" = R,
                  tabledata "Assembly Header" = R,
                  tabledata "Assembly Line" = R,
                  tabledata "Assembly Setup" = R,
                  tabledata "Assisted Company Setup Status" = R,
                  tabledata "ATO Sales Buffer" = R,
                  tabledata Attachment = R,
                  tabledata "Attachment Entity Buffer" = R,
                  tabledata Attendee = R,
                  tabledata "Autocomplete Address" = R,
                  tabledata "Availability at Date" = R,
                  tabledata "Availability Calc. Overview" = R,
                  tabledata "Average Cost Calc. Overview" = R,
                  tabledata "Avg. Cost Adjmt. Entry Point" = R,
                  tabledata "Azure AD App Setup" = R,
                  tabledata "Azure AD Mgt. Setup" = R,
                  tabledata "Azure AI Usage" = R,
                  tabledata "Balance Sheet Buffer" = R,
                  tabledata "Bank Acc. Reconciliation" = R,
                  tabledata "Bank Acc. Reconciliation Line" = R,
                  tabledata "Bank Acc. Rec. Match Buffer" = R,
                  tabledata "Bank Account" = R,
                  tabledata "Bank Account Balance Buffer" = R,
                  tabledata "Bank Account Ledger Entry" = R,
                  tabledata "Bank Account Posting Group" = R,
                  tabledata "Bank Account Statement" = R,
                  tabledata "Bank Account Statement Line" = R,
                  tabledata "Bank Clearing Standard" = R,
                  tabledata "Bank Export/Import Setup" = R,
                  tabledata "Bank Pmt. Appl. Rule" = R,
                  tabledata "Bank Pmt. Appl. Settings" = R,
                  tabledata "Bank Statement Matching Buffer" = R,
                  tabledata "Bank Stmt Multiple Match Line" = R,
                  tabledata "Bar Chart Buffer" = R,
                  tabledata "Base Calendar" = R,
                  tabledata "Base Calendar Change" = R,
                  tabledata "Batch Processing Parameter" = R,
                  tabledata "Batch Processing Session Map" = R,
                  tabledata Bin = R,
                  tabledata "Bin Content" = R,
                  tabledata "Bin Content Buffer" = R,
                  tabledata "Bin Creation Wksh. Name" = R,
                  tabledata "Bin Creation Wksh. Template" = R,
                  tabledata "Bin Creation Worksheet Line" = R,
                  tabledata "Bin Template" = R,
                  tabledata "Bin Type" = R,
                  tabledata "BOM Buffer" = R,
                  tabledata "BOM Component" = R,
                  tabledata "BOM Warning Log" = R,
                  tabledata "Booking Item" = R,
                  tabledata "Booking Mailbox" = R,
                  tabledata "Booking Mgr. Setup" = R,
                  tabledata "Booking Service" = R,
                  tabledata "Booking Service Mapping" = R,
                  tabledata "Booking Staff" = R,
                  tabledata "Booking Sync" = R,
                  tabledata "Budget Buffer" = R,
                  tabledata "Bus. Unit In Cons. Process" = R,
                  tabledata "Business Chart Buffer" = R,
                  tabledata "Business Chart Map" = R,
                  tabledata "Business Chart User Setup" = RIM,
                  tabledata "Business Relation" = R,
                  tabledata "Business Unit" = R,
                  tabledata "Business Unit Information" = R,
                  tabledata "Business Unit Setup" = R,
                  tabledata "Calendar Absence Entry" = R,
                  tabledata "Calendar Entry" = R,
#if not CLEAN24
                  tabledata "Calendar Event" = R,
                  tabledata "Calendar Event User Config." = R,
#endif
                  tabledata Campaign = R,
                  tabledata "Campaign Entry" = R,
                  tabledata "Campaign Status" = R,
                  tabledata "Campaign Target Group" = R,
                  tabledata "Cancelled Document" = R,
                  tabledata "Capacity Constrained Resource" = R,
                  tabledata "Capacity Ledger Entry" = R,
                  tabledata "Capacity Unit of Measure" = R,
                  tabledata "Cash Flow Account" = R,
                  tabledata "Cash Flow Account Comment" = R,
                  tabledata "Cash Flow Availability Buffer" = R,
                  tabledata "Cash Flow Azure AI Buffer" = R,
                  tabledata "Cash Flow Chart Setup" = RIMD,
                  tabledata "Cash Flow Forecast" = R,
                  tabledata "Cash Flow Forecast Entry" = R,
                  tabledata "Cash Flow Manual Expense" = R,
                  tabledata "Cash Flow Manual Revenue" = R,
                  tabledata "Cash Flow Report Selection" = R,
                  tabledata "Cash Flow Setup" = R,
                  tabledata "Cash Flow Worksheet Line" = R,
                  tabledata "Cause of Absence" = R,
                  tabledata "Cause of Inactivity" = R,
                  tabledata "CDS Available Virtual Table" = R,
                  tabledata "CDS BC Table Relation" = R,
                  tabledata "CDS Company" = R,
                  tabledata "CDS Connection Setup" = R,
                  tabledata "CDS Coupled Business Unit" = R,
                  tabledata "CDS Environment" = R,
                  tabledata "CDS Solution" = R,
                  tabledata "CDS Teammembership" = R,
                  tabledata "CDS Teamroles" = R,
                  tabledata "Certificate of Supply" = R,
                  tabledata "Change Global Dim. Header" = R,
                  tabledata "Change Global Dim. Log Entry" = R,
                  tabledata "Change Log Entry" = Ri,
                  tabledata "Change Log Setup (Field)" = R,
                  tabledata "Change Log Setup (Table)" = R,
                  tabledata "Change Log Setup" = R,
                  tabledata "Chart Definition" = R,
                  tabledata "Check Ledger Entry" = R,
                  tabledata "Close Income Statement Buffer" = R,
                  tabledata "Close Opportunity Code" = R,
                  tabledata "Column Layout" = R,
                  tabledata "Column Layout Name" = R,
                  tabledata "Comment Line" = R,
                  tabledata "Communication Method" = R,
                  tabledata "Company Information" = R,
                  tabledata "Company Size" = R,
                  tabledata Confidential = R,
                  tabledata "Confidential Information" = R,
                  tabledata "Config. Field Map" = R,
                  tabledata "Config. Line" = R,
                  tabledata "Config. Media Buffer" = R,
                  tabledata "Config. Package" = R,
                  tabledata "Config. Package Data" = R,
                  tabledata "Config. Package Error" = R,
                  tabledata "Config. Package Field" = R,
                  tabledata "Config. Package Filter" = R,
                  tabledata "Config. Package Record" = R,
                  tabledata "Config. Package Table" = R,
                  tabledata "Config. Question" = R,
                  tabledata "Config. Question Area" = R,
                  tabledata "Config. Questionnaire" = R,
                  tabledata "Config. Record For Processing" = R,
                  tabledata "Config. Related Field" = R,
                  tabledata "Config. Related Table" = R,
                  tabledata "Config. Selection" = R,
                  tabledata "Config. Setup" = R,
                  tabledata "Config. Table Processing Rule" = R,
                  tabledata "Config. Template Header" = R,
                  tabledata "Config. Template Line" = R,
                  tabledata "Config. Tmpl. Selection Rules" = R,
                  tabledata "Consolidation Account" = R,
                  tabledata "Cont. Duplicate Search String" = R,
                  tabledata Contact = R,
                  tabledata "Contact Alt. Addr. Date Range" = R,
                  tabledata "Contact Alt. Address" = R,
                  tabledata "Contact Business Relation" = R,
                  tabledata "Contact Dupl. Details Buffer" = R,
                  tabledata "Contact Duplicate" = R,
                  tabledata "Contact Industry Group" = R,
                  tabledata "Contact Job Responsibility" = R,
                  tabledata "Contact Mailing Group" = R,
                  tabledata "Contact Profile Answer" = R,
                  tabledata "Contact Value" = R,
                  tabledata "Contact Web Source" = R,
                  tabledata "Consolidation Process" = R,
                  tabledata "Consolidation Setup" = R,
                  tabledata "Copy Gen. Journal Parameters" = R,
                  tabledata "Copy Item Buffer" = R,
                  tabledata "Copy Item Parameters" = R,
                  tabledata "Cost Accounting Setup" = R,
                  tabledata "Cost Allocation Source" = R,
                  tabledata "Cost Allocation Target" = R,
                  tabledata "Cost Budget Buffer" = R,
                  tabledata "Cost Budget Entry" = R,
                  tabledata "Cost Budget Name" = R,
                  tabledata "Cost Budget Register" = R,
                  tabledata "Cost Center" = R,
                  tabledata "Cost Element Buffer" = R,
                  tabledata "Cost Entry" = R,
                  tabledata "Cost Journal Batch" = R,
                  tabledata "Cost Journal Line" = R,
                  tabledata "Cost Journal Template" = R,
                  tabledata "Cost Object" = R,
                  tabledata "Cost Register" = R,
                  tabledata "Cost Share Buffer" = R,
                  tabledata "Cost Type" = R,
                  tabledata "Country/Region" = R,
                  tabledata "Country/Region Translation" = R,
                  tabledata "Coupling Record Buffer" = R,
                  tabledata "Credit Trans Re-export History" = R,
                  tabledata "Credit Transfer Entry" = R,
                  tabledata "Credit Transfer Register" = R,
                  tabledata "Dataverse Entity Change" = Rd,
                  tabledata "CRM Account" = R,
                  tabledata "CRM Account Statistics" = R,
                  tabledata "CRM Annotation" = R,
                  tabledata "CRM Annotation Buffer" = R,
                  tabledata "CRM Annotation Coupling" = R,
                  tabledata "CRM Appmodule" = R,
                  tabledata "CRM BC Virtual Table Config." = R,
                  tabledata "CRM Businessunit" = R,
                  tabledata "CRM Company" = R,
                  tabledata "CRM Connection Setup" = R,
                  tabledata "CRM Contact" = R,
                  tabledata "CRM Contract" = R,
                  tabledata "CRM Customeraddress" = R,
                  tabledata "CRM Discount" = R,
                  tabledata "CRM Discounttype" = R,
                  tabledata "CRM Freight Terms" = R,
                  tabledata "CRM Full Synch. Review Line" = R,
                  tabledata "CRM Incident" = R,
                  tabledata "CRM Incidentresolution" = R,
                  tabledata "CRM Integration Record" = R,
                  tabledata "CRM Invoice" = R,
                  tabledata "CRM Invoicedetail" = R,
                  tabledata "CRM NAV Connection" = R,
                  tabledata "CRM Opportunity" = R,
                  tabledata "CRM Option Mapping" = R,
                  tabledata "CRM Organization" = R,
                  tabledata "CRM Payment Terms" = R,
                  tabledata "CRM Post" = R,
                  tabledata "CRM Post Buffer" = R,
                  tabledata "CRM Post Configuration" = R,
                  tabledata "CRM Pricelevel" = R,
                  tabledata "CRM Product" = R,
                  tabledata "CRM Productpricelevel" = R,
                  tabledata "CRM Quote" = R,
                  tabledata "CRM Quotedetail" = R,
                  tabledata "CRM Redirect" = R,
                  tabledata "CRM Role" = R,
                  tabledata "CRM Salesorder" = R,
                  tabledata "CRM Salesorderdetail" = R,
                  tabledata "CRM Shipping Method" = R,
                  tabledata "CRM Synch Status" = R,
                  tabledata "CRM Synch. Conflict Buffer" = R,
                  tabledata "CRM Synch. Job Status Cue" = R,
                  tabledata "CRM Systemuser" = R,
                  tabledata "CRM Systemuserroles" = R,
                  tabledata "CDS Field Security Profile" = R,
                  tabledata "CDS System User Profiles" = R,
                  tabledata "CRM Team" = R,
                  tabledata "CRM Transactioncurrency" = R,
                  tabledata "CRM Uom" = R,
                  tabledata "CRM Uomschedule" = R,
#if not CLEAN25
                  tabledata "FS Connection Setup" = R,
                  tabledata "FS Bookable Resource" = R,
                  tabledata "FS Bookable Resource Booking" = R,
                  tabledata "FS BookableResourceBookingHdr" = R,
                  tabledata "FS Customer Asset" = R,
                  tabledata "FS Customer Asset Category" = R,
                  tabledata "FS Project Task" = R,
                  tabledata "FS Resource Pay Type" = R,
                  tabledata "FS Work Order" = R,
                  tabledata "FS Work Order Incident" = R,
                  tabledata "FS Work Order Product" = R,
                  tabledata "FS Work Order Service" = R,
                  tabledata "FS Work Order Substatus" = R,
                  tabledata "FS Work Order Type" = R,
#endif
                  tabledata "CSV Buffer" = R,
                  tabledata "Curr. Exch. Rate Update Setup" = R,
                  tabledata Currency = R,
                  tabledata "Currency Amount" = R,
                  tabledata "Currency Exchange Rate" = R,
                  tabledata "Currency for Fin. Charge Terms" = R,
                  tabledata "Currency for Reminder Level" = R,
                  tabledata "Currency Total Buffer" = R,
                  tabledata "Current Salesperson" = R,
                  tabledata "Cust. Invoice Disc." = R,
                  tabledata "Cust. Ledger Entry" = R,
                  tabledata "Custom Address Format" = R,
                  tabledata "Custom Address Format Line" = R,
                  tabledata "Custom Report Layout" = R,
                  tabledata "Custom Report Selection" = R,
                  tabledata Customer = R,
                  tabledata "Customer Amount" = R,
                  tabledata "Customer Bank Account" = R,
                  tabledata "Customer Discount Group" = R,
                  tabledata "Customer Posting Group" = R,
                  tabledata "Customer Price Group" = R,
                  tabledata "Customer Sales Buffer" = R,
                  tabledata "Customer Templ." = R,
                  tabledata "Customized Calendar Change" = R,
                  tabledata "Customized Calendar Entry" = R,
                  tabledata "CV Ledger Entry Buffer" = R,
                  tabledata "Data Exch." = R,
                  tabledata "Data Exch. Column Def" = R,
                  tabledata "Data Exch. Def" = R,
                  tabledata "Data Exch. Field" = R,
                  tabledata "Data Exch. Field Mapping" = R,
                  tabledata "Data Exch. Field Mapping Buf." = R,
                  tabledata "Data Exch. Line Def" = R,
                  tabledata "Data Exch. Mapping" = R,
                  tabledata "Data Exch. Field Grouping" = R,
                  tabledata "Data Exch. FlowField Gr. Buff." = R,
                  tabledata "Data Exchange Type" = R,
                  tabledata "Data Exch. Table Filter" = R,
                  tabledata "Data Migration Entity" = R,
                  tabledata "Data Migration Error" = R,
                  tabledata "Data Migration Parameters" = R,
                  tabledata "Data Migration Setup" = R,
                  tabledata "Data Migration Status" = R,
                  tabledata "Data Migrator Registration" = R,
                  tabledata "Data Privacy Records" = R,
                  tabledata "DataExch-RapidStart Buffer" = R,
                  tabledata "Date Compr. Register" = R,
                  tabledata "Date Lookup Buffer" = R,
                  tabledata "Default Dimension" = R,
                  tabledata "Default Dimension Priority" = R,
                  tabledata "Deferral Header" = R,
                  tabledata "Deferral Header Archive" = R,
                  tabledata "Deferral Line" = R,
                  tabledata "Deferral Line Archive" = R,
                  tabledata "Deferral Posting Buffer" = R,
                  tabledata "Deferral Template" = R,
                  tabledata "Delivery Sorter" = R,
                  tabledata "Depreciation Book" = R,
                  tabledata "Depreciation Table Buffer" = R,
                  tabledata "Depreciation Table Header" = R,
                  tabledata "Depreciation Table Line" = R,
                  tabledata "Designer Diagnostic" = RIMD,
                  tabledata "Detailed Cust. Ledg. Entry" = R,
                  tabledata "Detailed CV Ledg. Entry Buffer" = R,
                  tabledata "Detailed Employee Ledger Entry" = R,
                  tabledata "Detailed Vendor Ledg. Entry" = R,
                  tabledata "Dim Correct Selection Criteria" = R,
                  tabledata "Dim Correction Blocked Setup" = R,
                  tabledata "Dim Correction Change" = R,
                  tabledata "Dim Correction Set Buffer" = R,
                  tabledata "Dim Correction Entry Log" = R,
                  tabledata Dimension = R,
                  tabledata "Dim. Value per Account" = R,
                  tabledata "Dimension Buffer" = R,
                  tabledata "Dimension Code Amount Buffer" = R,
                  tabledata "Dimension Code Buffer" = R,
                  tabledata "Dimension Combination" = R,
                  tabledata "Dimension Correction" = R,
                  tabledata "Dimension Entry Buffer" = R,
                  tabledata "Dimension ID Buffer" = R,
                  tabledata "Dimension Selection Buffer" = R,
                  tabledata "Dimension Set Entry" = R,
                  tabledata "Dimension Set Entry Buffer" = R,
                  tabledata "Dimension Set ID Filter Line" = R,
                  tabledata "Dimension Set Tree Node" = R,
                  tabledata "Dimension Translation" = R,
                  tabledata "Dimension Value" = R,
                  tabledata "Dimension Value Combination" = R,
                  tabledata "Dimensions Field Map" = R,
                  tabledata "Dimensions Template" = R,
                  tabledata "Direct Debit Collection" = R,
                  tabledata "Direct Debit Collection Entry" = R,
                  tabledata "Doc. Exch. Service Setup" = R,
                  tabledata "Document Attachment" = R,
                  tabledata "Document Entry" = R,
                  tabledata "Document Search Result" = R,
                  tabledata "Document Sending Profile" = R,
#if not CLEAN23
                  tabledata "Document Service Cache" = R,
#endif
                  tabledata "Drop Shpt. Post. Buffer" = R,
                  tabledata "Dtld. Price Calculation Setup" = R,
                  tabledata "Duplicate Price Line" = R,
                  tabledata "Duplicate Search String Setup" = R,
                  tabledata "Dynamic Request Page Entity" = R,
                  tabledata "Dynamic Request Page Field" = R,
                  tabledata "ECSL VAT Report Line" = R,
                  tabledata "ECSL VAT Report Line Relation" = R,
                  tabledata "Electronic Document Format" = R,
                  tabledata "Email Item" = R,
                  tabledata "Email Parameter" = R,
                  tabledata Employee = R,
                  tabledata "Employee Absence" = R,
                  tabledata "Employee Ledger Entry" = R,
                  tabledata "Employee Payment Buffer" = R,
                  tabledata "Employee Posting Group" = R,
                  tabledata "Employee Qualification" = R,
                  tabledata "Employee Relative" = R,
                  tabledata "Employee Statistics Group" = R,
                  tabledata "Employee Templ." = R,
                  tabledata "Employee Time Reg Buffer" = R,
                  tabledata "Employment Contract" = R,
                  tabledata "Entry No. Amount Buffer" = R,
                  tabledata "Entry Summary" = R,
                  tabledata "Entry/Exit Point" = R,
                  tabledata "Error Buffer" = R,
                  tabledata "Error Handling Parameters" = R,
                  tabledata "Error Message" = R,
                  tabledata "Error Message Register" = R,
                  tabledata "Excel Buffer" = R,
                  tabledata "Excel Template Storage" = R,
                  tabledata "Exch. Rate Adjmt. Reg." = R,
                  tabledata "Exch. Rate Adjmt. Ledg. Entry" = R,
                  tabledata "Exchange Contact" = R,
                  tabledata "Exchange Folder" = R,
                  tabledata "Exchange Object" = R,
                  tabledata "Exchange Service Setup" = R,
                  tabledata "Exchange Sync" = R,
#if not CLEAN24
                  tabledata "Exp. Phys. Invt. Tracking" = R,
#endif
                  tabledata "Exp. Invt. Order Tracking" = R,
                  tabledata "Experience Tier Buffer" = R,
                  tabledata "Experience Tier Setup" = R,
                  tabledata "Extended Text Header" = R,
                  tabledata "Extended Text Line" = R,
                  tabledata "FA Allocation" = R,
                  tabledata "FA Buffer Projection" = R,
                  tabledata "FA Class" = R,
                  tabledata "FA Date Type" = R,
                  tabledata "FA Depreciation Book" = R,
                  tabledata "FA G/L Posting Buffer" = R,
                  tabledata "FA Journal Batch" = R,
                  tabledata "FA Journal Line" = R,
                  tabledata "FA Journal Setup" = R,
                  tabledata "FA Journal Template" = R,
                  tabledata "FA Ledger Entry" = R,
                  tabledata "FA Location" = R,
                  tabledata "FA Matrix Posting Type" = R,
                  tabledata "FA Posting Group" = R,
                  tabledata "FA Posting Group Buffer" = R,
                  tabledata "FA Posting Type" = R,
                  tabledata "FA Posting Type Setup" = R,
                  tabledata "FA Reclass. Journal Batch" = R,
                  tabledata "FA Reclass. Journal Line" = R,
                  tabledata "FA Reclass. Journal Template" = R,
                  tabledata "FA Register" = R,
                  tabledata "FA Setup" = R,
                  tabledata "FA Subclass" = R,
                  tabledata Family = R,
                  tabledata "Family Line" = R,
                  tabledata "Field Buffer" = R,
                  tabledata "Field Monitoring Setup" = R,
                  tabledata "Filter Item Attributes Buffer" = R,
                  tabledata "Fin. Charge Comment Line" = R,
                  tabledata "Finance Charge Interest Rate" = R,
                  tabledata "Finance Charge Memo Header" = R,
                  tabledata "Finance Charge Memo Line" = R,
                  tabledata "Finance Charge Terms" = R,
                  tabledata "Finance Charge Text" = R,
                  tabledata "Finance Cue" = RIMD,
                  tabledata "Fixed Asset" = R,
                  tabledata "Flow Service Configuration" = R,
                  tabledata "Flow User Environment Buffer" = R,
                  tabledata "Flow User Environment Config" = R,
                  tabledata "G/L - Item Ledger Relation" = R,
                  tabledata "G/L Acc. Balance Buffer" = R,
                  tabledata "G/L Acc. Balance/Budget Buffer" = R,
                  tabledata "G/L Acc. Budget Buffer" = R,
                  tabledata "G/L Account (Analysis View)" = R,
                  tabledata "G/L Account" = R,
                  tabledata "G/L Account Category" = R,
                  tabledata "G/L Account Net Change" = R,
                  tabledata "G/L Account Where-Used" = R,
                  tabledata "G/L Budget Entry" = R,
                  tabledata "G/L Budget Name" = R,
                  tabledata "G/L Entry - VAT Entry Link" = R,
                  tabledata "G/L Entry" = R,
                  tabledata "G/L Register" = R,
                  tabledata "Gen. Business Posting Group" = R,
                  tabledata "Gen. Jnl. Allocation" = R,
                  tabledata "Gen. Jnl. Dim. Filter" = R,
                  tabledata "Gen. Journal Batch" = R,
                  tabledata "Gen. Journal Line" = R,
                  tabledata "Gen. Journal Template" = R,
                  tabledata "Gen. Product Posting Group" = R,
                  tabledata "General Ledger Setup" = R,
                  tabledata "General Posting Setup" = R,
                  tabledata "Generic Chart Captions Buffer" = R,
                  tabledata "Generic Chart Filter" = R,
                  tabledata "Generic Chart Memo Buffer" = R,
                  tabledata "Generic Chart Query Column" = R,
                  tabledata "Generic Chart Setup" = R,
                  tabledata "Generic Chart Y-Axis" = R,
                  tabledata Geolocation = R,
                  tabledata "Grounds for Termination" = R,
                  tabledata "Handled IC Inbox Jnl. Line" = R,
                  tabledata "Handled IC Inbox Purch. Header" = R,
                  tabledata "Handled IC Inbox Purch. Line" = R,
                  tabledata "Handled IC Inbox Sales Header" = R,
                  tabledata "Handled IC Inbox Sales Line" = R,
                  tabledata "Handled IC Inbox Trans." = R,
                  tabledata "Handled IC Outbox Jnl. Line" = R,
                  tabledata "Handled IC Outbox Purch. Hdr" = R,
                  tabledata "Handled IC Outbox Purch. Line" = R,
                  tabledata "Handled IC Outbox Sales Header" = R,
                  tabledata "Handled IC Outbox Sales Line" = R,
                  tabledata "Handled IC Outbox Trans." = R,
                  tabledata "HR Confidential Comment Line" = R,
                  tabledata "Human Resource Comment Line" = R,
                  tabledata "Human Resource Unit of Measure" = R,
                  tabledata "Human Resources Setup" = R,
                  tabledata "Hybrid Deployment Setup" = R,
                  tabledata "IC Bank Account" = R,
                  tabledata "IC Comment Line" = R,
                  tabledata "IC Dimension" = R,
                  tabledata "IC Dimension Value" = R,
                  tabledata "IC Document Dimension" = R,
                  tabledata "IC G/L Account" = R,
                  tabledata "IC Inbox Jnl. Line" = R,
                  tabledata "IC Inbox Purchase Header" = R,
                  tabledata "IC Inbox Purchase Line" = R,
                  tabledata "IC Inbox Sales Header" = R,
                  tabledata "IC Inbox Sales Line" = R,
                  tabledata "IC Inbox Transaction" = R,
                  tabledata "IC Inbox/Outbox Jnl. Line Dim." = R,
                  tabledata "IC Outbox Jnl. Line" = R,
                  tabledata "IC Outbox Purchase Header" = R,
                  tabledata "IC Outbox Purchase Line" = R,
                  tabledata "IC Outbox Sales Header" = R,
                  tabledata "IC Outbox Sales Line" = R,
                  tabledata "IC Outbox Transaction" = R,
                  tabledata "IC Partner" = R,
                  tabledata "IC Setup" = R,
                  tabledata "Image Analysis Setup" = R,
                  tabledata "Image Analysis Scenario" = R,
                  tabledata "Import G/L Transaction" = R,
                  tabledata "Incoming Document" = R,
                  tabledata "Incoming Document Approver" = R,
                  tabledata "Incoming Document Attachment" = R,
                  tabledata "Incoming Documents Setup" = R,
                  tabledata "Industry Group" = R,
                  tabledata "Ins. Coverage Ledger Entry" = R,
                  tabledata Insurance = R,
                  tabledata "Insurance Journal Batch" = R,
                  tabledata "Insurance Journal Line" = R,
                  tabledata "Insurance Journal Template" = R,
                  tabledata "Insurance Register" = R,
                  tabledata "Insurance Type" = R,
                  tabledata "Int. Table Config Template" = R,
                  tabledata "Integration Field Mapping" = R,
                  tabledata "Integration Synch. Job" = R,
                  tabledata "Integration Synch. Job Errors" = R,
                  tabledata "Integration Table Mapping" = R,
                  tabledata "Inter. Log Entry Comment Line" = R,
                  tabledata "Interaction Group" = R,
                  tabledata "Interaction Log Entry" = R,
                  tabledata "Interaction Merge Data" = R,
                  tabledata "Interaction Template" = R,
                  tabledata "Interaction Template Setup" = R,
                  tabledata "Interaction Tmpl. Language" = R,
                  tabledata "Intermediate Data Import" = R,
                  tabledata "Internal Movement Header" = R,
                  tabledata "Internal Movement Line" = R,
                  tabledata "Invalidated Dim Correction" = R,
                  tabledata "Inventory Adjmt. Entry (Order)" = R,
                  tabledata "Inventory Adjustment Buffer" = R,
                  tabledata "Inventory Buffer" = R,
                  tabledata "Inventory Comment Line" = R,
                  tabledata "Inventory Event Buffer" = R,
                  tabledata "Inventory Page Data" = R,
                  tabledata "Inventory Period" = R,
                  tabledata "Inventory Period Entry" = R,
                  tabledata "Inventory Posting Group" = R,
                  tabledata "Inventory Posting Setup" = R,
                  tabledata "Inventory Profile" = R,
                  tabledata "Inventory Profile Track Buffer" = R,
                  tabledata "Inventory Report Entry" = R,
                  tabledata "Inventory Report Header" = R,
                  tabledata "Inventory Setup" = R,
#if not CLEAN23
                  tabledata "Invoice Post. Buffer" = R,
#endif
                  tabledata "Invoice Posting Buffer" = R,
                  tabledata "Invoiced Booking Item" = R,
                  tabledata "Invt. Document Header" = R,
                  tabledata "Invt. Document Line" = R,
                  tabledata "Invt. Post to G/L Test Buffer" = R,
                  tabledata "Invt. Posting Buffer" = R,
                  tabledata "Invt. Receipt Header" = R,
                  tabledata "Invt. Receipt Line" = R,
                  tabledata "Invt. Shipment Header" = R,
                  tabledata "Invt. Shipment Line" = R,
                  tabledata "Isolated Certificate" = R,
                  tabledata "Issued Fin. Charge Memo Header" = R,
                  tabledata "Issued Fin. Charge Memo Line" = R,
                  tabledata "Issued Reminder Header" = R,
                  tabledata "Issued Reminder Line" = R,
                  tabledata Item = R,
                  tabledata "Item Amount" = R,
                  tabledata "Item Analysis View" = R,
                  tabledata "Item Analysis View Budg. Entry" = R,
                  tabledata "Item Analysis View Entry" = R,
                  tabledata "Item Analysis View Filter" = R,
                  tabledata "Item Application Entry" = R,
                  tabledata "Item Application Entry History" = R,
                  tabledata "Item Attr. Value Translation" = R,
                  tabledata "Item Attribute" = R,
                  tabledata "Item Attribute Translation" = R,
                  tabledata "Item Attribute Value" = R,
                  tabledata "Item Attribute Value Mapping" = R,
                  tabledata "Item Attribute Value Selection" = R,
                  tabledata "Item Availability Buffer" = R,
                  tabledata "Item Availability by Date" = R,
                  tabledata "Item Availability Line" = R,
                  tabledata "Item Budget Buffer" = R,
                  tabledata "Item Budget Entry" = R,
                  tabledata "Item Budget Name" = R,
                  tabledata "Item Category" = R,
                  tabledata "Item Charge" = R,
                  tabledata "Item Charge Assignment (Purch)" = R,
                  tabledata "Item Charge Assignment (Sales)" = R,
                  tabledata "Item Discount Group" = R,
                  tabledata "Item Entry Relation" = R,
                  tabledata "Item Identifier" = R,
                  tabledata "Item Journal Batch" = R,
                  tabledata "Item Journal Buffer" = R,
                  tabledata "Item Journal Line" = R,
                  tabledata "Item Journal Template" = R,
                  tabledata "Item Ledger Entry" = R,
                  tabledata "Item Picture Buffer" = R,
                  tabledata "Item Reference" = R,
                  tabledata "Item Register" = R,
                  tabledata "Item Statistics Buffer" = R,
                  tabledata "Item Substitution" = R,
                  tabledata "Item Templ." = R,
                  tabledata "Item Tracing Buffer" = R,
                  tabledata "Item Tracing History Buffer" = R,
                  tabledata "Item Tracking Code" = R,
                  tabledata "Item Tracking Comment" = R,
                  tabledata "Item Tracking Setup" = R,
                  tabledata "Item Translation" = R,
                  tabledata "Item Turnover Buffer" = R,
                  tabledata "Item Unit of Measure" = R,
                  tabledata "Item Variant" = R,
                  tabledata "Item Vendor" = R,
                  tabledata Job = R,
                  tabledata "Job Buffer" = R,
                  tabledata "Job Cue" = RIMD,
                  tabledata "Job Difference Buffer" = R,
                  tabledata "Job Entry No." = R,
#if not CLEAN25
                  tabledata "Job G/L Account Price" = R,
                  tabledata "Job Item Price" = R,
#endif
                  tabledata "Job Journal Batch" = R,
                  tabledata "Job Journal Line" = R,
                  tabledata "Job Journal Quantity" = R,
                  tabledata "Job Journal Template" = R,
                  tabledata "Job Ledger Entry" = R,
                  tabledata "Job Planning Line - Calendar" = R,
                  tabledata "Job Planning Line" = R,
                  tabledata "Job Planning Line Invoice" = R,
                  tabledata "Job Posting Buffer" = R,
                  tabledata "Job Posting Group" = R,
                  tabledata "Job Queue Category" = R,
                  tabledata "Job Queue Entry" = R,
                  tabledata "Job Queue Entry Buffer" = R,
                  tabledata "Job Queue Log Entry" = R,
                  tabledata "Job Queue Role Center Cue" = R,
                  tabledata "Job Register" = R,
#if not CLEAN25
                  tabledata "Job Resource Price" = R,
#endif
                  tabledata "Job Responsibility" = R,
                  tabledata "Job Task" = R,
                  tabledata "Job Task Dimension" = R,
                  tabledata "Job Usage Link" = R,
                  tabledata "Job WIP Buffer" = R,
                  tabledata "Job WIP Entry" = R,
                  tabledata "Job WIP G/L Entry" = R,
                  tabledata "Job WIP Method" = R,
                  tabledata "Job WIP Total" = R,
                  tabledata "Job WIP Warning" = R,
                  tabledata "Jobs Setup" = R,
                  tabledata "JSON Buffer" = R,
                  tabledata "Last Used Chart" = RIMD,
                  tabledata "Ledger Entry Matching Buffer" = R,
                  tabledata "License Agreement" = R,
                  tabledata "Line Fee Note on Report Hist." = R,
                  tabledata "Line Number Buffer" = R,
                  tabledata "Load Buffer" = R,
                  tabledata Location = R,
                  tabledata "Logged Segment" = R,
                  tabledata "Lot Bin Buffer" = R,
                  tabledata "Lot No. Information" = R,
                  tabledata "Machine Center" = R,
                  tabledata "Mailing Group" = R,
                  tabledata "Main Asset Component" = R,
                  tabledata Maintenance = R,
                  tabledata "Maintenance Ledger Entry" = R,
                  tabledata "Maintenance Registration" = R,
                  tabledata "Man. Integration Field Mapping" = R,
                  tabledata "Man. Integration Table Mapping" = R,
                  tabledata "Man. Int. Field Mapping" = R,
                  tabledata Manufacturer = R,
                  tabledata "Manufacturing Comment Line" = R,
                  tabledata "Manufacturing Cue" = RIMD,
                  tabledata "Manufacturing Setup" = R,
                  tabledata "Manufacturing User Template" = R,
                  tabledata "Marketing Setup" = R,
                  tabledata "Media Repository" = R,
                  tabledata "Memoized Result" = R,
                  tabledata "Miniform Function" = R,
                  tabledata "Miniform Function Group" = R,
                  tabledata "Miniform Header" = R,
                  tabledata "Miniform Line" = R,
                  tabledata "Misc. Article" = R,
                  tabledata "Misc. Article Information" = R,
                  tabledata "MS-QBD Setup" = R,
                  tabledata "My Account" = RIMD,
                  tabledata "My Customer" = RIMD,
                  tabledata "My Item" = RIMD,
                  tabledata "My Job" = RIMD,
                  tabledata "My Notifications" = RIMD,
                  tabledata "My Time Sheets" = RIMD,
                  tabledata "My Vendor" = RIMD,
                  tabledata "Name/Value Buffer" = R,
                  tabledata "Named Forward Link" = R,
                  tabledata "No. Series" = R,
                  tabledata "No. Series Line" = R,
                  tabledata "No. Series Relationship" = R,
                  tabledata "No. Series Tenant" = R,
                  tabledata "Nonstock Item" = R,
                  tabledata "Nonstock Item Setup" = R,
                  tabledata "Notification Context" = R,
                  tabledata "Notification Entry" = R,
                  tabledata "Notification Schedule" = R,
                  tabledata "Notification Setup" = R,
                  tabledata "O365 Brand Color" = R,
                  tabledata "O365 Device Setup Instructions" = R,
                  tabledata "O365 Getting Started" = R,
                  tabledata "O365 Getting Started Page Data" = R,
                  tabledata "O365 HTML Template" = R,
                  tabledata "O365 Payment Service Logo" = R,
                  tabledata "OAuth 2.0 Setup" = R,
                  tabledata "Object Translation" = R,
                  tabledata "OCR Service Document Template" = R,
                  tabledata "OCR Service Setup" = R,
                  tabledata "OData Initialized Status" = R,
                  tabledata "Office Add-in" = R,
                  tabledata "Office Add-in Context" = R,
                  tabledata "Office Add-in Setup" = RIMD,
                  tabledata "Office Admin. Credentials" = R,
                  tabledata "Office Contact Details" = R,
                  tabledata "Office Document Selection" = R,
                  tabledata "Office Invoice" = R,
                  tabledata "Office Job Journal" = R,
                  tabledata "Office Suggested Line Item" = R,
                  tabledata "Online Bank Acc. Link" = R,
                  tabledata "Online Map Parameter Setup" = R,
                  tabledata "Online Map Setup" = R,
                  tabledata Opportunity = R,
                  tabledata "Opportunity Entry" = R,
                  tabledata "Option Lookup Buffer" = r,
                  tabledata "Order Address" = R,
                  tabledata "Order Promising Line" = R,
                  tabledata "Order Promising Setup" = R,
                  tabledata "Order Tracking Entry" = R,
                  tabledata "Organizational Level" = R,
                  tabledata "Outstanding Bank Transaction" = R,
                  tabledata "Over-Receipt Code" = R,
                  tabledata "Overdue Approval Entry" = R,
                  tabledata "Package No. Information" = R,
                  tabledata "Payable Employee Ledger Entry" = R,
                  tabledata "Payable Vendor Ledger Entry" = R,
                  tabledata "Payment Application Proposal" = R,
                  tabledata "Vendor Payment Buffer" = R,
                  tabledata "Payment Export Data" = R,
                  tabledata "Payment Export Remittance Text" = R,
                  tabledata "Payment Jnl. Export Error Text" = R,
                  tabledata "Payment Matching Details" = R,
                  tabledata "Payment Method" = R,
                  tabledata "Payment Method Translation" = R,
                  tabledata "Payment Rec. Related Entry" = R,
                  tabledata "Pmt. Rec. Applied-to Entry" = R,
                  tabledata "Payment Registration Buffer" = R,
                  tabledata "Payment Registration Setup" = R,
                  tabledata "Payment Reporting Argument" = R,
                  tabledata "Payment Service Setup" = R,
                  tabledata "Payment Term Translation" = R,
                  tabledata "Payment Terms" = R,
                  tabledata "Payroll Import Buffer" = R,
                  tabledata "Payroll Setup" = R,
                  tabledata "Permission Buffer" = R,
                  tabledata "Permission Conflicts" = R,
                  tabledata "Permission Conflicts Overview" = R,
                  tabledata "Permission Set Buffer" = R,
                  tabledata "Permission Set Link" = r,
                  tabledata "Phys. Inventory Ledger Entry" = R,
                  tabledata "Phys. Invt. Comment Line" = R,
                  tabledata "Phys. Invt. Count Buffer" = R,
                  tabledata "Phys. Invt. Counting Period" = R,
                  tabledata "Phys. Invt. Item Selection" = R,
                  tabledata "Phys. Invt. Order Header" = R,
                  tabledata "Phys. Invt. Order Line" = R,
                  tabledata "Phys. Invt. Record Header" = R,
                  tabledata "Phys. Invt. Record Line" = R,
#if not CLEAN24
                  tabledata "Phys. Invt. Tracking" = R,
#endif
                  tabledata "Invt. Order Tracking" = R,
                  tabledata "Picture Entity" = R,
                  tabledata "Planning Assignment" = R,
                  tabledata "Planning Buffer" = R,
                  tabledata "Planning Component" = R,
                  tabledata "Planning Error Log" = R,
                  tabledata "Planning Routing Line" = R,
                  tabledata "Positive Pay Detail" = R,
                  tabledata "Positive Pay Entry" = R,
                  tabledata "Positive Pay Entry Detail" = R,
                  tabledata "Positive Pay Footer" = R,
                  tabledata "Positive Pay Header" = R,
                  tabledata "Post Code" = R,
                  tabledata "Post Value Entry to G/L" = R,
                  tabledata "Postcode Service Config" = R,
                  tabledata "Posted Approval Comment Line" = R,
                  tabledata "Posted Approval Entry" = R,
                  tabledata "Posted Assemble-to-Order Link" = R,
                  tabledata "Posted Assembly Header" = R,
                  tabledata "Posted Assembly Line" = R,
                  tabledata "Posted Deferral Header" = R,
                  tabledata "Posted Deferral Line" = R,
                  tabledata "Posted Docs. With No Inc. Buf." = R,
                  tabledata "Posted Gen. Journal Batch" = R,
                  tabledata "Posted Gen. Journal Line" = R,
                  tabledata "Posted Invt. Pick Header" = R,
                  tabledata "Posted Invt. Pick Line" = R,
                  tabledata "Posted Invt. Put-away Header" = R,
                  tabledata "Posted Invt. Put-away Line" = R,
                  tabledata "Posted Payment Recon. Hdr" = R,
                  tabledata "Posted Payment Recon. Line" = R,
                  tabledata "Posted Whse. Receipt Header" = R,
                  tabledata "Posted Whse. Receipt Line" = R,
                  tabledata "Posted Whse. Shipment Header" = R,
                  tabledata "Posted Whse. Shipment Line" = R,
#if not CLEAN23
                  tabledata "Power BI User Configuration" = RIMD,
                  tabledata "Power BI Report Configuration" = RIMD,
                  tabledata "Power BI User Status" = RIMD,
#endif
                  tabledata "Power BI Chart Buffer" = RIMD,
                  tabledata "Power BI Context Settings" = RIMD,
                  tabledata "Power BI Customer Reports" = R,
                  tabledata "Power BI Displayed Element" = RIMD,
                  tabledata "Power BI Report Labels" = R,
                  tabledata "Power BI Report Uploads" = R,
                  tabledata "Prepayment Inv. Line Buffer" = R,
                  tabledata "Price Asset" = R,
                  tabledata "Price Calculation Buffer" = R,
                  tabledata "Price Calculation Setup" = R,
                  tabledata "Price Line Filters" = R,
                  tabledata "Price List Header" = R,
                  tabledata "Price List Line" = R,
                  tabledata "Price Source" = R,
                  tabledata "Price Worksheet Line" = R,
                  tabledata "Printer Selection" = R,
                  tabledata "Prod. Order Capacity Need" = R,
                  tabledata "Prod. Order Comment Line" = R,
                  tabledata "Prod. Order Comp. Cmt Line" = R,
                  tabledata "Prod. Order Component" = R,
                  tabledata "Prod. Order Line" = R,
                  tabledata "Prod. Order Routing Line" = R,
                  tabledata "Prod. Order Routing Personnel" = R,
                  tabledata "Prod. Order Routing Tool" = R,
                  tabledata "Prod. Order Rtng Comment Line" = R,
                  tabledata "Prod. Order Rtng Qlty Meas." = R,
                  tabledata "Production BOM Comment Line" = R,
                  tabledata "Production BOM Header" = R,
                  tabledata "Production BOM Line" = R,
                  tabledata "Production BOM Version" = R,
                  tabledata "Production Forecast Entry" = R,
                  tabledata "Production Forecast Name" = R,
                  tabledata "Production Matrix  BOM Entry" = R,
                  tabledata "Production Matrix BOM Line" = R,
                  tabledata "Production Order" = R,
                  tabledata "Profile Designer Diagnostic" = RIMD,
                  tabledata "Profile Import" = RIMD,
                  tabledata "Profile Questionnaire Header" = R,
                  tabledata "Profile Questionnaire Line" = R,
#if not CLEAN24
                  tabledata "Pstd. Exp. Phys. Invt. Track" = R,
#endif
                  tabledata "Pstd.Exp.Invt.Order.Tracking" = R,
                  tabledata "Pstd. Phys. Invt. Order Hdr" = R,
                  tabledata "Pstd. Phys. Invt. Order Line" = R,
                  tabledata "Pstd. Phys. Invt. Record Hdr" = R,
                  tabledata "Pstd. Phys. Invt. Record Line" = R,
                  tabledata "Pstd. Phys. Invt. Tracking" = R,
                  tabledata "Purch. Comment Line" = R,
                  tabledata "Purch. Comment Line Archive" = R,
                  tabledata "Purch. Cr. Memo Entity Buffer" = R,
                  tabledata "Purch. Cr. Memo Hdr." = R,
                  tabledata "Purch. Cr. Memo Line" = R,
                  tabledata "Purch. Inv. Entity Aggregate" = R,
                  tabledata "Purch. Inv. Header" = R,
                  tabledata "Purch. Inv. Line" = R,
                  tabledata "Purch. Inv. Line Aggregate" = R,
#if not CLEAN25
                  tabledata "Purch. Price Line Disc. Buff." = R,
#endif
                  tabledata "Purch. Rcpt. Header" = R,
                  tabledata "Purch. Rcpt. Line" = R,
                  tabledata "Purchase Cue" = RIMD,
                  tabledata "Purchase Discount Access" = R,
                  tabledata "Purchase Header" = R,
                  tabledata "Purchase Header Archive" = R,
                  tabledata "Purchase Line" = R,
                  tabledata "Purchase Line Archive" = R,
#if not CLEAN25
                  tabledata "Purchase Line Discount" = R,
#endif
                  tabledata "Purchase Order Entity Buffer" = R,
                  tabledata "Purchase Prepayment %" = R,
#if not CLEAN25
                  tabledata "Purchase Price" = R,
#endif
                  tabledata "Purchase Price Access" = R,
                  tabledata "Purchases & Payables Setup" = R,
                  tabledata Purchasing = R,
                  tabledata "Put-away Template Header" = R,
                  tabledata "Put-away Template Line" = R,
                  tabledata Qualification = R,
                  tabledata "Quality Measure" = R,
                  tabledata "RapidStart Services Cue" = RIMD,
                  tabledata Rating = R,
                  tabledata "RC Headlines User Data" = R,
                  tabledata "Reason Code" = R,
                  tabledata "Receivables-Payables Buffer" = R,
                  tabledata "Reclas. Dimension Set Buffer" = R,
                  tabledata "Reconcile CV Acc Buffer" = R,
                  tabledata "Record Buffer" = R,
                  tabledata "Record Export Buffer" = R,
                  tabledata "Record Set Buffer" = R,
                  tabledata "Record Set Definition" = R,
                  tabledata "Record Set Tree" = R,
                  tabledata "Recorded Event Buffer" = R,
                  tabledata "Referenced XML Schema" = R,
                  tabledata "Registered Absence" = R,
                  tabledata "Registered Invt. Movement Hdr." = R,
                  tabledata "Registered Invt. Movement Line" = R,
                  tabledata "Registered Whse. Activity Hdr." = R,
                  tabledata "Registered Whse. Activity Line" = R,
                  tabledata "Relationship Mgmt. Cue" = RIMD,
                  tabledata Relative = R,
                  tabledata "Reminder Attachment Text" = R,
                  tabledata "Reminder Attachment Text Line" = R,
                  tabledata "Reminder Comment Line" = R,
                  tabledata "Reminder Email Text" = R,
                  tabledata "Reminder Header" = R,
                  tabledata "Reminder Level" = R,
                  tabledata "Reminder Line" = R,
                  tabledata "Reminder Terms" = R,
                  tabledata "Reminder Terms Translation" = R,
                  tabledata "Reminder Text" = R,
                  tabledata "Reminder Action Group" = R,
                  tabledata "Reminder Action" = R,
                  tabledata "Create Reminders Setup" = R,
                  tabledata "Issue Reminders Setup" = R,
                  tabledata "Send Reminders Setup" = R,
                  tabledata "Reminder Automation Error" = R,
                  tabledata "Reminder Action Group Log" = R,
                  tabledata "Reminder Action Log" = R,
                  tabledata "Reminder/Fin. Charge Entry" = R,
                  tabledata "Remit Address" = R,
                  tabledata "Report Inbox" = R,
                  tabledata "Report Layout Selection" = R,
                  tabledata "Report Layout Update Log" = R,
                  tabledata "Report List Translation" = R,
                  tabledata "Report Selection Warehouse" = R,
                  tabledata "Report Selections" = R,
                  tabledata "Report Totals Buffer" = R,
                  tabledata "Req. Wksh. Template" = R,
                  tabledata "Requisition Line" = R,
                  tabledata "Requisition Wksh. Name" = R,
                  tabledata "Res. Availability Buffer" = R,
                  tabledata "Res. Capacity Entry" = R,
                  tabledata "Res. Gr. Availability Buffer" = R,
                  tabledata "Res. Journal Batch" = R,
                  tabledata "Res. Journal Line" = R,
                  tabledata "Res. Journal Template" = R,
                  tabledata "Res. Ledger Entry" = R,
                  tabledata "Reservation Entry" = R,
                  tabledata "Reservation Entry Buffer" = R,
                  tabledata Resource = R,
#if not CLEAN25
                  tabledata "Resource Cost" = R,
#endif
                  tabledata "Resource Group" = R,
#if not CLEAN25
                  tabledata "Resource Price" = R,
                  tabledata "Resource Price Change" = R,
#endif
                  tabledata "Resource Register" = R,
                  tabledata "Resource Unit of Measure" = R,
                  tabledata "Resources Setup" = R,
                  tabledata "Responsibility Center" = R,
                  tabledata "Restricted Record" = R,
                  tabledata "Return Reason" = R,
                  tabledata "Return Receipt Header" = R,
                  tabledata "Return Receipt Line" = R,
                  tabledata "Return Shipment Header" = R,
                  tabledata "Return Shipment Line" = R,
                  tabledata "Returns-Related Document" = R,
                  tabledata "Reversal Entry" = R,
                  tabledata "Rlshp. Mgt. Comment Line" = R,
                  tabledata "RM Matrix Management" = R,
                  tabledata "Role Center Notifications" = R,
                  tabledata "Rounding Method" = R,
                  tabledata "Rounding Residual Buffer" = R,
                  tabledata "Routing Comment Line" = R,
                  tabledata "Routing Header" = R,
                  tabledata "Routing Line" = R,
                  tabledata "Routing Link" = R,
                  tabledata "Routing Personnel" = R,
                  tabledata "Routing Quality Measure" = R,
                  tabledata "Routing Tool" = R,
                  tabledata "Routing Version" = R,
                  tabledata "Sales & Receivables Setup" = R,
                  tabledata "Sales by Cust. Grp.Chart Setup" = R,
                  tabledata "Sales Comment Line" = R,
                  tabledata "Sales Comment Line Archive" = R,
                  tabledata "Sales Cr. Memo Entity Buffer" = R,
                  tabledata "Sales Cr.Memo Header" = R,
                  tabledata "Sales Cr.Memo Line" = R,
                  tabledata "Sales Cue" = RIMD,
                  tabledata "Sales Cycle" = R,
                  tabledata "Sales Cycle Stage" = R,
                  tabledata "Sales Discount Access" = R,
                  tabledata "Sales Document Icon" = R,
                  tabledata "Sales Header" = R,
                  tabledata "Sales Header Archive" = R,
                  tabledata "Sales Invoice Entity Aggregate" = R,
                  tabledata "Sales Invoice Header" = R,
                  tabledata "Sales Invoice Line" = R,
                  tabledata "Sales Invoice Line Aggregate" = R,
                  tabledata "Sales Line" = R,
                  tabledata "Sales Line Archive" = R,
#if not CLEAN25
                  tabledata "Sales Line Discount" = R,
#endif
                  tabledata "Sales Order Entity Buffer" = R,
                  tabledata "Sales Planning Line" = R,
                  tabledata "Sales Prepayment %" = R,
#if not CLEAN25
                  tabledata "Sales Price" = R,
#endif
                  tabledata "Sales Price Access" = R,
#if not CLEAN25
                  tabledata "Sales Price and Line Disc Buff" = R,
                  tabledata "Sales Price Worksheet" = R,
#endif
                  tabledata "Sales Quote Entity Buffer" = R,
                  tabledata "Sales Shipment Buffer" = R,
                  tabledata "Sales Shipment Header" = R,
                  tabledata "Sales Shipment Line" = R,
                  tabledata "Salesperson/Purchaser" = R,
                  tabledata Salutation = R,
                  tabledata "Salutation Formula" = R,
                  tabledata "Saved Segment Criteria" = R,
                  tabledata "Saved Segment Criteria Line" = R,
                  tabledata "SB Owner Cue" = RIMD,
                  tabledata Scrap = R,
                  tabledata "Segment Criteria Line" = R,
                  tabledata "Segment Header" = R,
                  tabledata "Segment History" = R,
                  tabledata "Segment Interaction Language" = R,
                  tabledata "Segment Line" = R,
                  tabledata "Segment Wizard Filter" = R,
                  tabledata "Selected Dimension" = R,
                  tabledata "Semi-Manual Execution Log" = R,
                  tabledata "Semi-Manual Test Wizard" = R,
                  tabledata "Sent Notification Entry" = R,
                  tabledata "SEPA Direct Debit Mandate" = R,
                  tabledata "Serial No. Information" = R,
                  tabledata "Service Connection" = R,
                  tabledata "Ship-to Address" = R,
                  tabledata "Shipment Method" = R,
                  tabledata "Shipment Method Translation" = R,
                  tabledata "Shipping Agent" = R,
                  tabledata "Shipping Agent Services" = R,
                  tabledata "Shop Calendar" = R,
                  tabledata "Shop Calendar Holiday" = R,
                  tabledata "Shop Calendar Working Days" = R,
                  tabledata "Sorting Table" = R,
                  tabledata "Source Code" = R,
                  tabledata "Source Code Setup" = R,
                  tabledata "Special Equipment" = R,
                  tabledata "Standard Address" = R,
                  tabledata "Standard Cost Worksheet" = R,
                  tabledata "Standard Cost Worksheet Name" = R,
                  tabledata "Standard Customer Sales Code" = R,
                  tabledata "Standard General Journal" = R,
                  tabledata "Standard General Journal Line" = R,
                  tabledata "Standard Item Journal" = R,
                  tabledata "Standard Item Journal Line" = R,
                  tabledata "Standard Purchase Code" = R,
                  tabledata "Standard Purchase Line" = R,
                  tabledata "Standard Sales Code" = R,
                  tabledata "Standard Sales Line" = R,
                  tabledata "Standard Task" = R,
                  tabledata "Standard Task Description" = R,
                  tabledata "Standard Task Personnel" = R,
                  tabledata "Standard Task Quality Measure" = R,
                  tabledata "Standard Task Tool" = R,
                  tabledata "Standard Text" = R,
                  tabledata "Standard Vendor Purchase Code" = R,
                  tabledata "Stockkeeping Unit" = R,
                  tabledata "Stockkeeping Unit Comment Line" = R,
                  tabledata Stop = R,
                  tabledata "Substitution Condition" = R,
                  tabledata "Support Contact Information" = R,
                  tabledata "SWIFT Code" = R,
                  tabledata "Table Config Template" = R,
                  tabledata "Table Filter" = R,
                  tabledata "Tariff Number" = R,
                  tabledata "Tax Area" = R,
                  tabledata "Tax Area Buffer" = R,
                  tabledata "Tax Area Line" = R,
                  tabledata "Tax Area Translation" = R,
                  tabledata "Tax Detail" = R,
                  tabledata "Tax Group" = R,
                  tabledata "Tax Group Buffer" = R,
                  tabledata "Tax Jurisdiction" = R,
                  tabledata "Tax Jurisdiction Translation" = R,
                  tabledata "Tax Rate Buffer" = R,
                  tabledata "Tax Setup" = R,
                  tabledata Team = R,
                  tabledata "Team Member Cue" = RIMD,
                  tabledata "Team Salesperson" = R,
                  tabledata "Temp Integration Field Mapping" = R,
                  tabledata TempStack = R,
                  tabledata "Tenant Config. Package File" = R,
                  tabledata "Terms And Conditions" = R,
                  tabledata "Terms And Conditions State" = R,
                  tabledata Territory = R,
                  tabledata "Text-to-Account Mapping" = R,
                  tabledata "Time Series Buffer" = R,
                  tabledata "Time Series Forecast" = R,
                  tabledata "Time Sheet Chart Setup" = R,
                  tabledata "Time Sheet Cmt. Line Archive" = R,
                  tabledata "Time Sheet Comment Line" = R,
                  tabledata "Time Sheet Detail" = R,
                  tabledata "Time Sheet Detail Archive" = R,
                  tabledata "Time Sheet Header" = R,
                  tabledata "Time Sheet Header Archive" = R,
                  tabledata "Time Sheet Line" = R,
                  tabledata "Time Sheet Line Archive" = R,
                  tabledata "Time Sheet Posting Entry" = R,
                  tabledata "Timeline Event" = R,
                  tabledata "Timeline Event Change" = R,
                  tabledata "To-do" = R,
                  tabledata "To-do Interaction Language" = R,
                  tabledata "Top Customers By Sales Buffer" = R,
                  tabledata "Total Value Insured" = R,
                  tabledata "Tracking Specification" = R,
                  tabledata "Trailing Sales Orders Setup" = R,
                  tabledata "Transaction Specification" = R,
                  tabledata "Transaction Type" = R,
                  tabledata "Transfer Header" = R,
                  tabledata "Transfer Line" = R,
                  tabledata "Transfer Receipt Header" = R,
                  tabledata "Transfer Receipt Line" = R,
                  tabledata "Transfer Route" = R,
                  tabledata "Transfer Shipment Header" = R,
                  tabledata "Transfer Shipment Line" = R,
                  tabledata "Transformation Rule" = R,
                  tabledata "Transport Method" = R,
                  tabledata "Trial Balance Cache" = R,
                  tabledata "Trial Balance Cache Info" = R,
                  tabledata "Trial Balance Entity Buffer" = R,
                  tabledata "Trial Balance Setup" = R,
                  tabledata Union = R,
                  tabledata "Unit of Measure" = R,
                  tabledata "Unit of Measure Translation" = R,
                  tabledata "Unlinked Attachment" = R,
                  tabledata "Unplanned Demand" = R,
                  tabledata "Untracked Planning Element" = R,
                  tabledata "User Preference" = R,
                  tabledata "User Security Status" = RIMD,
                  tabledata "User Setup" = R,
                  tabledata "User Task" = R,
                  tabledata "User Task Group" = R,
                  tabledata "User Task Group Member" = R,
                  tabledata "User Time Register" = R,
                  tabledata "User Tours" = RIMD,
                  tabledata "Value Entry" = R,
                  tabledata "Value Entry Relation" = R,
                  tabledata "VAT Amount Line" = R,
                  tabledata "VAT Assisted Setup Bus. Grp." = R,
                  tabledata "VAT Assisted Setup Templates" = R,
                  tabledata "VAT Business Posting Group" = R,
                  tabledata "VAT Clause" = R,
                  tabledata "VAT Clause by Doc. Type" = R,
                  tabledata "VAT Clause by Doc. Type Trans." = R,
                  tabledata "VAT Clause Translation" = R,
                  tabledata "VAT Entry" = R,
                  tabledata "VAT Posting Setup" = R,
                  tabledata "VAT Product Posting Group" = R,
                  tabledata "VAT Setup" = R,
                  tabledata "Alt. Cust. VAT Reg." = R,
                  tabledata "VAT Posting Parameters" = R,
                  tabledata "VAT Rate Change Conversion" = R,
                  tabledata "VAT Rate Change Log Entry" = R,
                  tabledata "VAT Rate Change Setup" = R,
                  tabledata "VAT Reg. No. Srv Config" = R,
                  tabledata "VAT Reg. No. Srv. Template" = R,
                  tabledata "VAT Registration Log" = R,
                  tabledata "VAT Registration Log Details" = R,
                  tabledata "VAT Registration No. Format" = R,
                  tabledata "VAT Report Archive" = R,
                  tabledata "VAT Report Error Log" = R,
                  tabledata "VAT Report Header" = R,
                  tabledata "VAT Report Line" = R,
                  tabledata "VAT Report Line Relation" = R,
                  tabledata "VAT Report Setup" = R,
                  tabledata "VAT Reports Configuration" = R,
                  tabledata "VAT Return Period" = R,
                  tabledata "VAT Setup Posting Groups" = R,
                  tabledata "VAT Statement Line" = R,
                  tabledata "VAT Statement Name" = R,
                  tabledata "VAT Statement Report Line" = R,
                  tabledata "VAT Statement Template" = R,
                  tabledata Vendor = R,
                  tabledata "Vendor Amount" = R,
                  tabledata "Vendor Bank Account" = R,
                  tabledata "Vendor Invoice Disc." = R,
                  tabledata "Vendor Ledger Entry" = R,
                  tabledata "Vendor Posting Group" = R,
                  tabledata "Vendor Purchase Buffer" = R,
                  tabledata "Vendor Templ." = R,
                  tabledata "Warehouse Activity Header" = R,
                  tabledata "Warehouse Activity Line" = R,
                  tabledata "Warehouse Basic Cue" = RIMD,
                  tabledata "Warehouse Class" = R,
                  tabledata "Warehouse Comment Line" = R,
                  tabledata "Warehouse Employee" = R,
                  tabledata "Warehouse Entry" = R,
                  tabledata "Warehouse Journal Batch" = R,
                  tabledata "Warehouse Journal Line" = R,
                  tabledata "Warehouse Journal Template" = R,
                  tabledata "Warehouse Reason Code" = R,
                  tabledata "Warehouse Receipt Header" = R,
                  tabledata "Warehouse Receipt Line" = R,
                  tabledata "Warehouse Register" = R,
                  tabledata "Warehouse Request" = R,
                  tabledata "Warehouse Setup" = R,
                  tabledata "Warehouse Shipment Header" = R,
                  tabledata "Warehouse Shipment Line" = R,
                  tabledata "Warehouse Source Filter" = R,
                  tabledata "Warehouse WMS Cue" = RIMD,
                  tabledata "Warehouse Worker WMS Cue" = RIMD,
                  tabledata "Web Source" = R,
                  tabledata "WF Event/Response Combination" = R,
                  tabledata "Where Used Base Calendar" = R,
                  tabledata "Where-Used Line" = R,
                  tabledata "Whse. Cross-Dock Opportunity" = R,
                  tabledata "Whse. Internal Pick Header" = R,
                  tabledata "Whse. Internal Pick Line" = R,
                  tabledata "Whse. Internal Put-away Header" = R,
                  tabledata "Whse. Internal Put-away Line" = R,
                  tabledata "Whse. Item Entry Relation" = R,
                  tabledata "Whse. Item Tracking Line" = R,
                  tabledata "Whse. Pick Request" = R,
                  tabledata "Whse. Put-away Request" = R,
                  tabledata "Whse. Worksheet Line" = R,
                  tabledata "Whse. Worksheet Name" = R,
                  tabledata "Whse. Worksheet Template" = R,
                  tabledata "Work Center" = R,
                  tabledata "Work Center Group" = R,
                  tabledata "Work Shift" = R,
                  tabledata "Work Type" = R,
                  tabledata "Workflow - Record Change" = R,
                  tabledata "Workflow - Table Relation" = R,
                  tabledata Workflow = R,
                  tabledata "Workflow Buffer" = R,
                  tabledata "Workflow Category" = R,
                  tabledata "Workflow Event" = R,
                  tabledata "Workflow Event Queue" = R,
                  tabledata "Workflow Record Change Archive" = R,
                  tabledata "Workflow Response" = R,
                  tabledata "Workflow Rule" = R,
                  tabledata "Workflow Step" = R,
                  tabledata "Workflow Step Argument" = R,
                  tabledata "Workflow Step Argument Archive" = R,
                  tabledata "Workflow Step Buffer" = R,
                  tabledata "Workflow Step Instance" = R,
                  tabledata "Workflow Step Instance Archive" = R,
                  tabledata "Workflow Table Relation Value" = R,
                  tabledata "Workflow User Group" = R,
                  tabledata "Workflow User Group Member" = R,
                  tabledata "Workflow Webhook Entry" = R,
                  tabledata "Workflow Webhook Notification" = R,
                  tabledata "Workflow Webhook Sub Buffer" = R,
                  tabledata "Workflow Webhook Subscription" = R,
                  tabledata "Workflows Entries Buffer" = R,
                  tabledata "XML Buffer" = R,
                  tabledata "XML Schema" = R,
                  tabledata "XML Schema Element" = R,
                  tabledata "XML Schema Restriction" = R,
                  tabledata Zone = R,

                  // Service
                  tabledata "Contract Change Log" = R,
                  tabledata "Contract Gain/Loss Entry" = R,
                  tabledata "Contract Group" = R,
                  tabledata "Contract Trend Buffer" = R,
                  tabledata "Contract/Service Discount" = R,
                  tabledata "Fault Area" = R,
                  tabledata "Fault Area/Symptom Code" = R,
                  tabledata "Fault Code" = R,
                  tabledata "Fault Reason Code" = R,
                  tabledata "Fault/Resol. Cod. Relationship" = R,
                  tabledata "Filed Service Contract Header" = R,
                  tabledata "Filed Contract Line" = R,
                  tabledata "Filed Serv. Contract Cmt. Line" = R,
                  tabledata "Filed Contract Service Hour" = R,
                  tabledata "Filed Contract/Serv. Discount" = R,
                  tabledata Loaner = R,
                  tabledata "Loaner Entry" = R,
                  tabledata "Repair Status" = R,
                  tabledata "Resolution Code" = R,
                  tabledata "Resource Location" = R,
                  tabledata "Resource Service Zone" = R,
                  tabledata "Resource Skill" = R,
                  tabledata "Serv. Price Adjustment Detail" = R,
                  tabledata "Serv. Price Group Setup" = R,
                  tabledata "Service Comment Line" = R,
                  tabledata "Service Comment Line Archive" = R,
                  tabledata "Service Contract Account Group" = R,
                  tabledata "Service Contract Header" = R,
                  tabledata "Service Contract Line" = R,
                  tabledata "Service Contract Template" = R,
                  tabledata "Service Cost" = R,
                  tabledata "Service Cr.Memo Header" = R,
                  tabledata "Service Cr.Memo Line" = R,
                  tabledata "Service Cue" = RIMD,
                  tabledata "Service Document Log" = R,
                  tabledata "Service Document Register" = R,
                  tabledata "Service Email Queue" = R,
                  tabledata "Service Header" = R,
                  tabledata "Service Header Archive" = R,
                  tabledata "Service Hour" = R,
                  tabledata "Service Invoice Header" = R,
                  tabledata "Service Invoice Line" = R,
                  tabledata "Service Item" = R,
                  tabledata "Service Item Component" = R,
                  tabledata "Service Item Group" = R,
                  tabledata "Service Item Line" = R,
                  tabledata "Service Item Line Archive" = R,
                  tabledata "Service Item Log" = R,
                  tabledata "Service Item Trend Buffer" = R,
                  tabledata "Service Ledger Entry" = R,
                  tabledata "Service Line" = R,
                  tabledata "Service Line Archive" = R,
                  tabledata "Service Line Price Adjmt." = R,
                  tabledata "Service Mgt. Setup" = R,
                  tabledata "Service Order Allocation" = R,
                  tabledata "Service Order Allocat. Archive" = R,
                  tabledata "Service Order Posting Buffer" = R,
                  tabledata "Service Order Type" = R,
                  tabledata "Service Price Adjustment Group" = R,
                  tabledata "Service Price Group" = R,
                  tabledata "Service Register" = R,
                  tabledata "Service Shelf" = R,
                  tabledata "Service Shipment Buffer" = R,
                  tabledata "Service Shipment Header" = R,
                  tabledata "Service Shipment Item Line" = R,
                  tabledata "Service Shipment Line" = R,
                  tabledata "Service Status Priority Setup" = R,
                  tabledata "Service Zone" = R,
                  tabledata "Skill Code" = R,
                  tabledata "Standard Service Code" = R,
                  tabledata "Standard Service Item Gr. Code" = R,
                  tabledata "Standard Service Line" = R,
                  tabledata "Symptom Code" = R,
                  tabledata "Troubleshooting Header" = R,
                  tabledata "Troubleshooting Line" = R,
                  tabledata "Troubleshooting Setup" = R,
                  tabledata "Warranty Ledger Entry" = R,
                  tabledata "Work-Hour Template" = R;
}
