codeunit 132219 "Library - Manufacturing OnPrem"
{
    Access = Internal;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"License Management Starter", 'OnAfterReduceDemodata', '', false, false)]
    local procedure OnAfterReduceDemodata()
    var
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        ProdOrderCapacityNeed: Record "Prod. Order Capacity Need";
        ProdOrderRoutingTool: Record "Prod. Order Routing Tool";
        ProdOrderRoutingPersonnel: Record "Prod. Order Routing Personnel";
        ProdOrderRtngQltyMeas: Record "Prod. Order Rtng Qlty Meas.";
        ProdOrderCommentLine: Record "Prod. Order Comment Line";
        ProdOrderRtngCommentLine: Record "Prod. Order Rtng Comment Line";
        ProdOrderCompCmtLine: Record "Prod. Order Comp. Cmt Line";
        WorkShift: Record "Work Shift";
        ShopCalendar: Record "Shop Calendar";
        ShopCalendarWorkingDays: Record "Shop Calendar Working Days";
        ShopCalendarHoliday: Record "Shop Calendar Holiday";
        WorkCenter: Record "Work Center";
        WorkCenterGroup: Record "Work Center Group";
        CalendarEntry: Record "Calendar Entry";
        MachineCenter: Record "Machine Center";
        CalendarAbsenceEntry: Record "Calendar Absence Entry";
        Stop: Record Stop;
        Scrap: Record Scrap;
        RoutingHeader: Record "Routing Header";
        RoutingLine: Record "Routing Line";
        Family: Record Family;
        FamilyLine: Record "Family Line";
        RoutingCommentLine: Record "Routing Comment Line";
        RoutingLink: Record "Routing Link";
        StandardTask: Record "Standard Task";
        ProductionBOMVersion: Record "Production BOM Version";
        CapacityUnitOfMeasure: Record "Capacity Unit of Measure";
        StandardTaskTool: Record "Standard Task Tool";
        StandardTaskPersonnel: Record "Standard Task Personnel";
        StandardTaskDescription: Record "Standard Task Description";
        StandardTaskQualityMeasure: Record "Standard Task Quality Measure";
        QualityMeasure: Record "Quality Measure";
        RoutingVersion: Record "Routing Version";
        ProductionMatrixBOMLine: Record "Production Matrix BOM Line";
        ProductionMatrixBOMEntry: Record "Production Matrix  BOM Entry";
        RoutingTool: Record "Routing Tool";
        RoutingPersonnel: Record "Routing Personnel";
        RoutingQualityMeasure: Record "Routing Quality Measure";
        PlanningRoutingLine: Record "Planning Routing Line";
        PlanningBuffer: Record "Planning Buffer";
        ProductionForecastName: Record "Production Forecast Name";
        ProductionForecastEntry: Record "Production Forecast Entry";
        RegisteredAbsence: Record "Registered Absence";
        CapacityConstrainedResource: Record "Capacity Constrained Resource";
    begin
        ProdOrderRoutingLine.DeleteAll();
        ProdOrderCapacityNeed.DeleteAll();
        ProdOrderRoutingTool.DeleteAll();
        ProdOrderRoutingPersonnel.DeleteAll();
        ProdOrderRtngQltyMeas.DeleteAll();
        ProdOrderCommentLine.DeleteAll();
        ProdOrderRtngCommentLine.DeleteAll();
        ProdOrderCompCmtLine.DeleteAll();
        WorkShift.DeleteAll();
        ShopCalendar.DeleteAll();
        ShopCalendarWorkingDays.DeleteAll();
        ShopCalendarHoliday.DeleteAll();
        WorkCenter.DeleteAll();
        WorkCenterGroup.DeleteAll();
        CalendarEntry.DeleteAll();
        MachineCenter.DeleteAll();
        CalendarAbsenceEntry.DeleteAll();
        Stop.DeleteAll();
        Scrap.DeleteAll();
        RoutingHeader.DeleteAll();
        RoutingLine.DeleteAll();
        Family.DeleteAll();
        FamilyLine.DeleteAll();
        RoutingCommentLine.DeleteAll();
        RoutingLink.DeleteAll();
        StandardTask.DeleteAll();
        ProductionBOMVersion.DeleteAll();
        CapacityUnitOfMeasure.DeleteAll();
        StandardTaskTool.DeleteAll();
        StandardTaskPersonnel.DeleteAll();
        StandardTaskDescription.DeleteAll();
        StandardTaskQualityMeasure.DeleteAll();
        QualityMeasure.DeleteAll();
        RoutingVersion.DeleteAll();
        ProductionMatrixBOMLine.DeleteAll();
        ProductionMatrixBOMEntry.DeleteAll();
        RoutingTool.DeleteAll();
        RoutingPersonnel.DeleteAll();
        RoutingQualityMeasure.DeleteAll();
        PlanningRoutingLine.DeleteAll();
        PlanningBuffer.DeleteAll();
        RegisteredAbsence.DeleteAll();
        ProductionForecastName.DeleteAll();
        ProductionForecastEntry.DeleteAll();
        CapacityConstrainedResource.DeleteAll();
    end;
}