// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.Finance.Analysis;

using Microsoft.Foundation.Reporting;
using Microsoft.Purchases.Payables;
using System.Telemetry;
using System.Utilities;

page 687 "Payment Practice Card"
{
    ApplicationArea = All;
    Caption = 'Payment Practice';
    PageType = Card;
    SourceTable = "Payment Practice Header";

    layout
    {
        area(Content)
        {
            group(General)
            {
                Caption = 'General';
                field("No."; Rec."No.")
                {
                    ToolTip = 'Specifies the number of the payment practice header.';
                }
                field("Reporting Scheme"; Rec."Reporting Scheme")
                {
                    Visible = false;
                }
                field("Aggregation Type"; Rec."Aggregation Type")
                {
                    ToolTip = 'Specifies the aggregation type of the payment practice.';
                }
                field("Header Type"; Rec."Header Type")
                {
                    ToolTip = 'Specifies the source for entries in the payment practice.';
                }
                field("Startind Date"; Rec."Starting Date")
                {
                    Caption = 'Starting Date';
                    ToolTip = 'Specifies the starting date of the payment practice.';
                }
                field("Ending Date"; Rec."Ending Date")
                {
                    ToolTip = 'Specifies the ending date of the payment practice.';
                }
                field("Generated On"; Rec."Generated On")
                {
                    Editable = false;
                    ToolTip = 'Specifies the date and time when the payment practice was generated.';
                }
                field("Generated By"; Rec."Generated By")
                {
                    Editable = false;
                    ToolTip = 'Specifies the user who generated the payment practice.';
                }
                field("Lines Exist"; Rec."Lines Exist")
                {
                    Editable = false;
                    ToolTip = 'Specifies whether the payment practice has lines.';
                    Visible = false;
                }
                field("Modified Manually"; Rec."Modified Manually")
                {
                    Editable = false;
                    ToolTip = 'Specifies whether the payment practice was modified manually.';
                }
            }
            group("Statistics")
            {
                Caption = 'Payment Statistics';
                field("Average Agreed Payment Period"; Rec."Average Agreed Payment Period")
                {
                    ToolTip = 'Specifies the average agreed payment period.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                field("Average Actual Payment Period"; Rec."Average Actual Payment Period")
                {
                    ToolTip = 'Specifies the average actual payment period.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                field("Pct Paid on Time"; Rec."Pct Paid on Time")
                {
                    ToolTip = 'Specifies the percentage paid on time.';

                    trigger OnDrillDown()
                    begin
                        ShowHeaderDataLines();
                    end;
                }
                group("Dispute and Retention")
                {
                    Caption = 'Dispute and Retention';
                    Visible = Rec."Reporting Scheme" = Rec."Reporting Scheme"::"Dispute & Retention";

                    field("Total Number of Payments"; Rec."Total Number of Payments")
                    {
                    }
                    field("Total Amount of Payments"; Rec."Total Amount of Payments")
                    {
                    }
                    field("Total Amt. of Overdue Payments"; Rec."Total Amt. of Overdue Payments")
                    {
                    }
                    field("Pct Overdue Due to Dispute"; Rec."Pct Overdue Due to Dispute")
                    {
                    }
                }
                group("Small Business Scheme")
                {
                    Caption = 'Small Business Scheme';
                    Visible = Rec."Reporting Scheme" = Rec."Reporting Scheme"::"Small Business";

                    field("Mode Payment Time"; Rec."Mode Payment Time")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }

                    field("Mode Payment Time Min."; Rec."Mode Payment Time Min.")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("Mode Payment Time Max."; Rec."Mode Payment Time Max.")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("Median Payment Time"; Rec."Median Payment Time")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("80th Percentile Payment Time"; Rec."80th Percentile Payment Time")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("95th Percentile Payment Time"; Rec."95th Percentile Payment Time")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("Pct Peppol Enabled"; Rec."Pct Peppol Enabled")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowHeaderDataLines();
                        end;
                    }
                    field("Pct Small Business Payments"; Rec."Pct Small Business Payments")
                    {
                        trigger OnDrillDown()
                        begin
                            ShowVendorInvoicesInReportPeriod();
                        end;
                    }
                }
            }
            part(Lines; "Payment Practice Lines")
            {
                ApplicationArea = All;
                SubPageLink = "Header No." = field("No.");
                UpdatePropagation = Both;
                Visible = true;
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(Generate)
            {
                Caption = 'Generate';
                ToolTip = 'Generates the data and lines for the payment practice.';
                Image = CashFlow;

                trigger OnAction()
                var
                    PaymentPractices: Codeunit "Payment Practices";
                    ConfirmManagement: Codeunit "Confirm Management";
                begin
                    if Rec."Lines Exist" then
                        if not ConfirmManagement.GetResponse(LinesWillBeDeletedQst, false) then
                            exit;

                    Rec.ClearHeader();
                    if not PaymentPractices.Generate(Rec) then
                        Message(NoEntriesFoundMsg);
                    UpdateVisibility();
                    CurrPage.Update();
                end;
            }
            action(Print)
            {
                Caption = 'Print';
                ToolTip = 'Prints the payment practice report.';
                Image = Print;

                trigger OnAction()
                begin
                    PrepareLayout(Rec."Aggregation Type", Rec."Reporting Scheme");
                    Rec.SetRecFilter();
                    Report.Run(Report::"Payment Practice", false, true, Rec);
                    FeatureTelemetry.LogUptake('0000KSV', 'Payment Practices', "Feature Uptake Status"::Used);
                end;
            }
        }
        area(Promoted)
        {
            actionref(Generate_Promoted; Generate)
            {
            }
            actionref(Print_Promoted; Print)
            {
            }
        }
    }

    trigger OnOpenPage()
    begin
        UpdateVisibility();
        CurrPage.Update();
    end;

    trigger OnAfterGetCurrRecord()
    begin
        UpdateVisibility();
    end;

    var
        FeatureTelemetry: Codeunit "Feature Telemetry";
        LinesWillBeDeletedQst: Label 'All previously generated lines will be deleted. Do you want to continue?';
        NoEntriesFoundMsg: Label 'The payment practice generator found no entries corresponding to the header type, starting and ending date.';

    local procedure PrepareLayout(PaymentPracticeLinesAggregator: Interface PaymentPracticeLinesAggregator; ReportingScheme: Enum "Paym. Prac. Reporting Scheme")
    var
        DesignTimeReportSelection: Codeunit "Design-time Report Selection";
    begin
        PaymentPracticeLinesAggregator.PrepareLayout();
        if ReportingScheme = ReportingScheme::"Small Business" then begin
            DesignTimeReportSelection.SetSelectedLayout('PaymentPractice_SmallBusinessLayout');
            FeatureTelemetry.LogUsage('0000KSU', 'Payment Practices', 'Small Business layout used.');
        end;
    end;

    local procedure ShowHeaderDataLines()
    var
        PaymentPracticeData: Record "Payment Practice Data";
    begin
        PaymentPracticeData.SetRange("Header No.", Rec."No.");
        Page.RunModal(Page::"Payment Practice Data List", PaymentPracticeData);
    end;

    local procedure ShowVendorInvoicesInReportPeriod()
    var
        VendorLedgerEntry: Record "Vendor Ledger Entry";
    begin
        VendorLedgerEntry.SetRange("Document Type", VendorLedgerEntry."Document Type"::Invoice);
        VendorLedgerEntry.SetRange("Posting Date", Rec."Starting Date", Rec."Ending Date");
        Page.RunModal(Page::"Vendor Ledger Entries", VendorLedgerEntry);
    end;

    local procedure UpdateVisibility()
    begin
        CurrPage.Lines.Page.UpdateVisibility(Rec."Aggregation Type", Rec."Header Type");
    end;
}