// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------
namespace Microsoft.DemoData.QualityManagement;

using Microsoft.DemoTool.Helpers;
using Microsoft.QualityManagement.Configuration.Result;

codeunit 5599 "Create QM Result Condit. Conf."
{
    InherentEntitlements = X;
    InherentPermissions = X;

    trigger OnRun()
    var
        ContosoQualityManagement: Codeunit "Contoso Quality Management";
        CreateQualityTest: Codeunit "Create Quality Test";
        CreateQualityInspResult: Codeunit "Create Quality Insp. Result";
        CreateQualityTestLookupValue: Codeunit "Create Quality Lookup Value";
        CreateQMInspTemplateHdr: Codeunit "Create QM Insp. Template Hdr";
    begin
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ApcPerGram(), 0, 0, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.Fail(), '>10000000', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ApcPerGram(), 0, 0, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ApcPerGram(), 0, 0, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.Pass(), '0..10000000', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.BrakesCheck(), 0, 0, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.BrakesCheck(), 0, 0, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.BrakesCheck(), 0, 0, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarContainment(), 0, 0, CreateQualityTest.CarContainment(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarContainment(), 0, 0, CreateQualityTest.CarContainment(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarContainment(), 0, 0, CreateQualityTest.CarContainment(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarRequestedDate(), 0, 0, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarRequestedDate(), 0, 0, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarRequestedDate(), 0, 0, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarType(), 0, 0, CreateQualityTest.CarType(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarType(), 0, 0, CreateQualityTest.CarType(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CarType(), 0, 0, CreateQualityTest.CarType(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ColiformCount(), 0, 0, CreateQualityTest.ColiformCount(), CreateQualityInspResult.Fail(), '>0.01', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ColiformCount(), 0, 0, CreateQualityTest.ColiformCount(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ColiformCount(), 0, 0, CreateQualityTest.ColiformCount(), CreateQualityInspResult.Pass(), '0..0.01', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CorrectiveAction(), 0, 0, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CorrectiveAction(), 0, 0, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CorrectiveAction(), 0, 0, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CustomerServiceRepre(), 0, 0, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CustomerServiceRepre(), 0, 0, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.CustomerServiceRepre(), 0, 0, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.DescriptionOfNonConf(), 0, 0, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.DescriptionOfNonConf(), 0, 0, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.DescriptionOfNonConf(), 0, 0, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.EcoliPresent(), 0, 0, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.Fail(), CreateQualityTestLookupValue.Present(), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.EcoliPresent(), 0, 0, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.EcoliPresent(), 0, 0, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Absent(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Explanation(), 0, 0, CreateQualityTest.Explanation(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Explanation(), 0, 0, CreateQualityTest.Explanation(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Explanation(), 0, 0, CreateQualityTest.Explanation(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.GearShiftCheck(), 0, 0, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.GearShiftCheck(), 0, 0, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.GearShiftCheck(), 0, 0, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.HandlebarAligned(), 0, 0, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.HandlebarAligned(), 0, 0, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.HandlebarAligned(), 0, 0, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrDetail(), 0, 0, CreateQualityTest.LblNcrDetail(), CreateQualityInspResult.Fail(), '<>0', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrDetail(), 0, 0, CreateQualityTest.LblNcrDetail(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrDetail(), 0, 0, CreateQualityTest.LblNcrDetail(), CreateQualityInspResult.Pass(), '<>0', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrPlannedAction(), 0, 0, CreateQualityTest.LblNcrPlannedAction(), CreateQualityInspResult.Fail(), '<>0', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrPlannedAction(), 0, 0, CreateQualityTest.LblNcrPlannedAction(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblNcrPlannedAction(), 0, 0, CreateQualityTest.LblNcrPlannedAction(), CreateQualityInspResult.Pass(), '<>0', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblVerification(), 0, 0, CreateQualityTest.LblVerification(), CreateQualityInspResult.Fail(), '<>0', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblVerification(), 0, 0, CreateQualityTest.LblVerification(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.LblVerification(), 0, 0, CreateQualityTest.LblVerification(), CreateQualityInspResult.Pass(), '<>0', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrClassification(), 0, 0, CreateQualityTest.NcrClassification(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrClassification(), 0, 0, CreateQualityTest.NcrClassification(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrClassification(), 0, 0, CreateQualityTest.NcrClassification(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrObjectiveEvidence(), 0, 0, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrObjectiveEvidence(), 0, 0, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrObjectiveEvidence(), 0, 0, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrRequirement(), 0, 0, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrRequirement(), 0, 0, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.NcrRequirement(), 0, 0, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Odor(), 0, 0, CreateQualityTest.Odor(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.BadOdor(), CreateQualityTestLookupValue.MildOdor()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Odor(), 0, 0, CreateQualityTest.Odor(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Odor(), 0, 0, CreateQualityTest.Odor(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.NoOdor(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageHeight(), 0, 0, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Fail(), '<15|>30', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageHeight(), 0, 0, CreateQualityTest.PackageHeight(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageHeight(), 0, 0, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Pass(), '15..30', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageLength(), 0, 0, CreateQualityTest.PackageLength(), CreateQualityInspResult.Fail(), '<15|>60', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageLength(), 0, 0, CreateQualityTest.PackageLength(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageLength(), 0, 0, CreateQualityTest.PackageLength(), CreateQualityInspResult.Pass(), '30..60', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageWidth(), 0, 0, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Fail(), '<10|>25', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageWidth(), 0, 0, CreateQualityTest.PackageWidth(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackageWidth(), 0, 0, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Pass(), '10..25', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackagingVisual(), 0, 0, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.Heavy(), CreateQualityTestLookupValue.Light()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackagingVisual(), 0, 0, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.PackagingVisual(), 0, 0, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Undamaged(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ReasonCode(), 0, 0, CreateQualityTest.ReasonCode(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ReasonCode(), 0, 0, CreateQualityTest.ReasonCode(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ReasonCode(), 0, 0, CreateQualityTest.ReasonCode(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.RootCauseFindings(), 0, 0, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.RootCauseFindings(), 0, 0, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.RootCauseFindings(), 0, 0, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ShippingLabel(), 0, 0, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ShippingLabel(), 0, 0, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.ShippingLabel(), 0, 0, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Temperature(), 0, 0, CreateQualityTest.Temperature(), CreateQualityInspResult.Fail(), '<-20|>5', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Temperature(), 0, 0, CreateQualityTest.Temperature(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.Temperature(), 0, 0, CreateQualityTest.Temperature(), CreateQualityInspResult.Pass(), '-20..5', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VerificationOfEffecti(), 0, 0, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VerificationOfEffecti(), 0, 0, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VerificationOfEffecti(), 0, 0, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VisualWeldCheck(), 0, 0, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VisualWeldCheck(), 0, 0, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Test, CreateQualityTest.VisualWeldCheck(), 0, 0, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 10000, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 10000, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 10000, CreateQualityTest.GearShiftCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 20000, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 20000, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 20000, CreateQualityTest.BrakesCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 30000, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 30000, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 30000, CreateQualityTest.VisualWeldCheck(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 40000, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.Fail(), 'No', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 40000, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.BicycleChecklist(), 0, 40000, CreateQualityTest.HandlebarAligned(), CreateQualityInspResult.Pass(), 'Yes', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 10000, CreateQualityTest.CarType(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 10000, CreateQualityTest.CarType(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 10000, CreateQualityTest.CarType(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 20000, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 20000, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 20000, CreateQualityTest.CarRequestedDate(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 30000, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 30000, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 30000, CreateQualityTest.NcrRequirement(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 40000, CreateQualityTest.NcrClassification(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 40000, CreateQualityTest.NcrClassification(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 40000, CreateQualityTest.NcrClassification(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 50000, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 50000, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 50000, CreateQualityTest.DescriptionOfNonConf(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 60000, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 60000, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 60000, CreateQualityTest.NcrObjectiveEvidence(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 70000, CreateQualityTest.CarContainment(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 70000, CreateQualityTest.CarContainment(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 70000, CreateQualityTest.CarContainment(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 80000, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 80000, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 80000, CreateQualityTest.RootCauseFindings(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 90000, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 90000, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 90000, CreateQualityTest.CorrectiveAction(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 100000, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 100000, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 100000, CreateQualityTest.VerificationOfEffecti(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 110000, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 110000, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Car(), 0, 110000, CreateQualityTest.CustomerServiceRepre(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 10000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.Heavy(), CreateQualityTestLookupValue.Light()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 10000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 10000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Undamaged(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 20000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Fail(), '<10|>25', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 20000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 20000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Pass(), '10..25', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 30000, CreateQualityTest.PackageLength(), CreateQualityInspResult.Fail(), '<30|>60', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 30000, CreateQualityTest.PackageLength(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 30000, CreateQualityTest.PackageLength(), CreateQualityInspResult.Pass(), '30..60', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 40000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Fail(), '<15|>60', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 40000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 40000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Pass(), '15..30', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 50000, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2|%3', CreateQualityTestLookupValue.BadPosition(), CreateQualityTestLookupValue.Blurred(), CreateQualityTestLookupValue.Damage()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 50000, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Packaging(), 0, 50000, CreateQualityTest.ShippingLabel(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Good(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 10000, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.Fail(), '>10000000', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 10000, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 10000, CreateQualityTest.ApcPerGram(), CreateQualityInspResult.Pass(), '0..10000000', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 20000, CreateQualityTest.ColiformCount(), CreateQualityInspResult.Fail(), '>0.01', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 20000, CreateQualityTest.ColiformCount(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 20000, CreateQualityTest.ColiformCount(), CreateQualityInspResult.Pass(), '0..0.01', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 30000, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.Fail(), CreateQualityTestLookupValue.Present(), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 30000, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Pathogen(), 0, 30000, CreateQualityTest.EcoliPresent(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Absent(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 10000, CreateQualityTest.Odor(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.BadOdor(), CreateQualityTestLookupValue.MildOdor()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 10000, CreateQualityTest.Odor(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 10000, CreateQualityTest.Odor(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.NoOdor(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 20000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.Heavy(), CreateQualityTestLookupValue.Light()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 20000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 20000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Undamaged(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 30000, CreateQualityTest.Temperature(), CreateQualityInspResult.Fail(), '<-20|>5', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 30000, CreateQualityTest.Temperature(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ProductionFood(), 0, 30000, CreateQualityTest.Temperature(), CreateQualityInspResult.Pass(), '-20..5', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 10000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Fail(), '<15|>30', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 10000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 10000, CreateQualityTest.PackageHeight(), CreateQualityInspResult.Pass(), '15..30', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 20000, CreateQualityTest.PackageLength(), CreateQualityInspResult.Fail(), '<30|>60', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 20000, CreateQualityTest.PackageLength(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 20000, CreateQualityTest.PackageLength(), CreateQualityInspResult.Pass(), '30..60', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 30000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Fail(), '<10|>25', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 30000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 30000, CreateQualityTest.PackageWidth(), CreateQualityInspResult.Pass(), '10..25', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 40000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Fail(), StrSubstNo('%1|%2', CreateQualityTestLookupValue.Heavy(), CreateQualityTestLookupValue.Light()), 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 40000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.Receive(), 0, 40000, CreateQualityTest.PackagingVisual(), CreateQualityInspResult.Pass(), CreateQualityTestLookupValue.Undamaged(), 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 10000, CreateQualityTest.ReasonCode(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 10000, CreateQualityTest.ReasonCode(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 10000, CreateQualityTest.ReasonCode(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);

        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 20000, CreateQualityTest.Explanation(), CreateQualityInspResult.Fail(), '<>''''', 1, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 20000, CreateQualityTest.Explanation(), CreateQualityInspResult.InProgress(), '', 0, Enum::"Qlty. Result Visibility"::"Configuration only");
        ContosoQualityManagement.InsertQltyIResultConditConf(Enum::"Qlty. Result Condition Type"::Template, CreateQMInspTemplateHdr.ScheduleChange(), 0, 20000, CreateQualityTest.Explanation(), CreateQualityInspResult.Pass(), '<>''''', 2, Enum::"Qlty. Result Visibility"::Promoted);
    end;
}
